const fs=require('fs'),path=require('path'),{spawn,execFileSync}=require('child_process'),pup=require('puppeteer');
const binary=path.resolve(process.argv[2]),root=JSON.parse(fs.readFileSync(process.argv[3])).root,dir=path.resolve(process.argv[4]);fs.mkdirSync(dir,{recursive:true});
(async()=>{const server=spawn(binary,['--root',root,'web']);let output='';server.stdout.on('data',d=>output+=d);while(!output.includes('/session/'))await new Promise(r=>setTimeout(r,100));const url=output.match(/http:\/\/\S+/)[0];const b=await pup.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});const errors=[],checks=[];let p,task;
try{p=await b.newPage();p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width:1440,height:1050});await p.goto(url);await p.waitForSelector('#tasks-body tr');await p.click('[data-view=brainstorm]');
const click=async(text,scope='body')=>p.locator(scope+' button::-p-text('+text+')').click();const fill=async(sel,v)=>{const tag=await p.$eval(sel,e=>e.tagName);if(tag==='SELECT'){await p.select(sel,v);return;}await p.click(sel,{clickCount:3});await p.type(sel,v)};const closed=()=>p.waitForFunction(()=>!document.querySelector('#modal').open);
await click('Examiner un RETEX issu de cette réponse','#brain-messages article:last-child');await fill('#field-problem','Exécuter le cas nominal de partage proposé par le brief');await fill('#field-proposal','Créer une simulation locale du cas nominal : copier un fichier témoin, vérifier son intégrité et produire un rapport de test. Aucun service réseau ni modification Wattson.');await fill('#field-risk','La simulation ne valide pas les droits ni la sécurité du gestionnaire Wattson réel.');await fill('#field-criteria','Une copie binaire est identique à la source ; une source absente est refusée ; aucun écrasement de destination existante. Tests exécutés et preuve indépendante.');await fill('#field-proof','À produire : rapport et résultats de tests de la tâche liée.');await p.click('#confirm');await closed();await p.click('#retex-list').catch(()=>{});await p.evaluate(()=>document.querySelector('#retex-list').parentElement.open=true);await click('Créer une tâche APEX','#retex-list');await p.click('#confirm');await closed();checks.push('real adopted brief → RETEX proposal → explicit APEX task creation');
async function action(a){await click('Piloter la tâche APEX','#retex-list');await p.waitForSelector('#field-action');task=(await p.$eval('#modal-title',e=>e.textContent)).split(' — ')[0];await p.select('#field-action',a)}
await action('accepted');await p.click('#confirm');await p.waitForSelector('#modal-error:not([hidden])');await p.keyboard.press('Escape');checks.push('premature acceptance refused');
await action('start');await p.select('#field-provider','claude');
const instruction=`Réalise cette tâche de recette dans cet espace isolé uniquement. Aucun accès réseau, aucune dépendance à installer, aucune délégation. Tu peux créer les fichiers et exécuter Python. Crée share_sim.py avec copy_shared(source, destination) : copie binaire exacte, FileNotFoundError si source absente, FileExistsError si destination existe, aucun écrasement. Utilise uniquement la bibliothèque standard. Crée test_share_sim.py avec unittest couvrant ces trois critères et un fichier binaire. Exécute python3 -m unittest -v test_share_sim. Après succès réel seulement, écris docs/${task}-handoff.md décrivant changements, commande, résultats et limites : simulation uniquement, aucune validation Wattson. Écris docs/${task}.json au format suivant en remplaçant les empreintes SHA256 par les empreintes réelles et la preuve par le rapport : {"method_version":"2","scope_id":"${task}","artifacts":{"share_sim.py":"SHA256","test_share_sim.py":"SHA256","docs/${task}-handoff.md":"SHA256"},"domains":{"quality":1},"checks":[{"id":"simulation","domain":"quality","mandatory":true,"gate":"delivery","penalty":100,"max_penalty":100,"severity":"major"}],"results":[{"id":"simulation","status":"PASS","count":0,"evidence":["docs/${task}-handoff.md"]}]}. Au plus deux corrections si test échoue ; sinon rapport de blocage sans PASS. Termine après livraison du rapport et du JSON ; ne modifie pas la base Swarm ou le Guide.`;
await fill('#field-instruction',instruction);await p.select('#field-capture','true');await p.click('#confirm');await closed();console.log('Real Claude worker launched: '+task);await p.waitForFunction(()=>Number(document.querySelector('#active-count').textContent)>0);await p.waitForFunction(()=>document.querySelector('#active-count').textContent==='0',{timeout:240000});await action('report');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#preview').textContent.includes('unittest'));await p.screenshot({path:dir+'/report.png'});await p.keyboard.press('Escape');checks.push('real Claude worker → report read through task modal');
const oracle=`import tempfile,pathlib,sys,json\nsys.path.insert(0,${JSON.stringify(root)})\nfrom share_sim import copy_shared\nwith tempfile.TemporaryDirectory() as t:\n p=pathlib.Path(t);a=p/'source';b=p/'destination';data=bytes(range(256))*17;a.write_bytes(data);copy_shared(a,b);assert b.read_bytes()==data\n try:copy_shared(a,b);raise AssertionError('overwrite accepted')\n except FileExistsError:pass\n assert b.read_bytes()==data\n try:copy_shared(p/'missing',p/'new');raise AssertionError('missing source accepted')\n except FileNotFoundError:pass\n assert not (p/'new').exists()\nprint('PASS independent binary copy, overwrite refusal, missing source refusal')`;
const observed=execFileSync('python3',['-c',oracle],{encoding:'utf8',cwd:root});fs.writeFileSync(dir+'/independent-check.txt',observed);fs.writeFileSync(dir+'/worker-tests.txt',execFileSync('python3',['-m','unittest','-v','test_share_sim'],{encoding:'utf8',cwd:root,stdio:['ignore','pipe','pipe']}));checks.push('independent behavioral oracle passed before acceptance; worker tests rerun');
await action('submit');await fill('#field-path','docs/'+task+'-handoff.md');await p.click('#confirm');await closed();await action('gate');await fill('#field-path','docs/'+task+'.json');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’enregistrement');await p.screenshot({path:dir+'/gate-review.png'});await p.click('#confirm');await closed();await action('accepted');await p.click('#confirm');await closed();checks.push('submit report → gate preview → gate registration → acceptance without waiver');
await click('Qualifier les preuves','#retex-list');await p.select('#field-nature','fait');await fill('#field-proof','Simulation vérifiée : '+task+' ; share_sim.py, test_share_sim.py et docs/'+task+'-handoff.md. Oracle indépendant : copie binaire exacte, source absente refusée, aucun écrasement. Limite : aucun service Wattson testé.');await p.click('#confirm');await closed();await click('Changer l’état du RETEX','#retex-list');await p.select('#field-note','verifie');await p.click('#confirm');await closed();await click('Proposer une leçon au Guide','#retex-list');await fill('#field-note','Dans cette recette isolée, terminer un processus ne suffisait pas : le rapport, les tests et une vérification indépendante ont précédé la gate et l’acceptation. Les tests prouvent uniquement la simulation locale de copie ; ils ne prouvent pas les droits ou la sécurité du service Wattson.');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Publier la leçon vérifiée');await p.click('#confirm');await closed();await p.waitForFunction(()=>document.querySelector('#retex-list').textContent.includes('Leçon publiée'));checks.push('qualify actual proof → verified RETEX → reviewed guide publication');
await p.reload();await p.waitForSelector('#tasks-body tr');await p.click('[data-view=brainstorm]');await p.evaluate(()=>document.querySelector('#retex-list').parentElement.open=true);await p.waitForFunction(()=>document.querySelector('#retex-list').textContent.includes('Leçon publiée'));for(const theme of ['etat','sombre']){if(await p.$eval('html',e=>e.dataset.theme)!==theme)await p.click('#theme');await p.screenshot({path:dir+'/'+theme+'-finished.png'});}checks.push('reload retains accepted task, verified RETEX and published lesson');if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync(dir+'/real-plan-ui.json',JSON.stringify({status:'PASS',root,task,provider:'claude',checks,errors,limit:'Single action derived from the prior brief in an isolated simulation; does not certify Wattson file manager or automatic full-plan conversion.'},null,2));console.log('Action plan end-to-end PASS');
}catch(e){fs.writeFileSync(dir+'/failure.txt',e.stack);if(p)await p.screenshot({path:dir+'/failure.png'});throw e}finally{await b.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
