const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),assert=require('assert/strict'),{spawn,execFile}=require('child_process'),{promisify}=require('util'),puppeteer=require('puppeteer');
const exec=promisify(execFile),binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]),root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-ai-ui-'));fs.mkdirSync(out,{recursive:true});let app,browser,mock;let calls=0;
(async()=>{
 await exec(binary,['--root',root,'init']);fs.symlinkSync('/bin/true',path.join(root,'claude'));fs.writeFileSync(path.join(root,'.swarm/providers.json'),JSON.stringify({schema_version:1,providers:{installed:{command:path.join(root,'claude'),args:[],env_allow:[]}}}));
 mock=http.createServer((req,res)=>{let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{calls++;const body=JSON.parse(raw);assert.equal(req.headers.authorization,'Bearer test-secret');assert.equal(body.model,'my/custom-model');assert.equal(body.tools,undefined);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify({message:'Connexion réussie',brief:'Un brief de test'})}}]}))})});await new Promise(r=>mock.listen(0,'127.0.0.1',r));
 app=spawn(binary,['--root',root,'web','127.0.0.1:0']);const url=await new Promise((resolve,reject)=>{let text='';app.stdout.on('data',d=>{text+=d;const m=text.match(/http:\/\/[^\s]+/);if(m)resolve(m[0])});app.on('exit',c=>reject(Error('server '+c)))});
 browser=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width:1450,height:1100});await p.goto(url);await p.waitForSelector('#connections-add');await p.click('[data-view="providers"]');await p.waitForFunction(()=>AIConnections.state);await p.click('#connections-add');await p.waitForSelector('#modal[open]');
 for(const [id,text] of Object.entries({connection_id:'custom',connection_label:'Mon modèle local',connection_url:`http://127.0.0.1:${mock.address().port}/v1`,connection_model:'my/custom-model',connection_key:'test-secret'}))await p.type('#field-'+id,text);
 for(const theme of ['etat','sombre']){await p.evaluate(t=>setTheme(t),theme);const missing=await p.evaluate(()=>{const css=[...document.styleSheets].flatMap(s=>[...s.cssRules].map(r=>r.cssText)).join(' '),style=getComputedStyle(document.documentElement);return [...new Set([...css.matchAll(/var\((--wattson-[\w-]+)/g)].map(m=>m[1]))].filter(t=>!style.getPropertyValue(t).trim())});assert.deepEqual(missing,[]);await p.screenshot({path:path.join(out,'ajouter-'+theme+'.png')})}
 const test=await p.$$('#modal-fields button');await test[test.length-1].click();await p.waitForFunction(()=>document.querySelector('#connection-test-result').textContent.includes('Réponse reçue'));assert.equal(calls,1);await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal').open);await p.waitForSelector('[data-connection="custom"]');
 const publicData=await p.evaluate(()=>api('/api/v1/providers/connections'));assert.equal(publicData.connections[0].has_key,true);assert.ok(!JSON.stringify(publicData).includes('test-secret'));
 const caps=await p.evaluate(()=>api('/api/v1/preparations/providers'));assert.equal(caps.providers.find(x=>x.provider==='api-custom').available,true);
 const stored=JSON.parse(fs.readFileSync(path.join(root,'.swarm/ai-connections.json'))).custom;const digest=require('crypto').createHash('sha256').update(JSON.stringify(stored)).digest('hex');
 // Use the actual generated subprocess arguments and the same output reader contract.
 const providers=JSON.parse((await exec(binary,['--root',root,'--json','providers','show'])).stdout);const provider=(providers.providers||providers).providers?.['api-custom']||(providers.providers||providers)['api-custom'];assert.ok(provider,JSON.stringify(providers));
 const child=spawn(provider.command,[...provider.args,'--json-schema','{"type":"object"}']);let output='';child.stdout.on('data',d=>output+=d);child.stdin.end('Prépare un brief de test');const code=await new Promise(r=>child.on('exit',r));assert.equal(code,0);assert.equal(JSON.parse(output).structured_output.message,'Connexion réussie');
 const prep=await browser.newPage();await prep.setViewport({width:1450,height:1100});await prep.goto(new URL('/prepare.html',url).href);await prep.waitForSelector('#organization-worker');await prep.evaluate(async()=>{const {PreparationConversion}=await import('/prephase-conversion.js');const c=new PreparationConversion(async route=>{const r=await fetch('/api/v1/'+route);return r.json()},async()=>null,()=>{});c.review={spec:{tasks:[]}};await c.setupOrganization();document.getElementById('conversion-organization').hidden=false;document.getElementById('conversion-dialog').showModal()});await prep.select('#organization-provider','api-custom');assert.ok(!(await prep.$$eval('#organization-worker option',els=>els.map(e=>e.value))).includes('api-custom'));await prep.select('#organization-worker','installed');for(const theme of ['etat','sombre']){await prep.evaluate(t=>document.documentElement.dataset.theme=t,theme);await prep.screenshot({path:path.join(out,'organisation-'+theme+'.png')})}await prep.close();
 await p.click('[data-connection="custom"] button');await p.waitForSelector('#field-connection_key');assert.equal(await p.$eval('#field-connection_key',e=>e.value),'');await p.select('#field-connection_enabled','no');await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal').open);await p.waitForFunction(()=>document.querySelector('[data-connection="custom"]')?.textContent.includes('Désactivée'));assert.match(await p.$eval('[data-connection="custom"]',e=>e.textContent),/Désactivée/);
 for(const theme of ['etat','sombre']){await p.evaluate(t=>setTheme(t),theme);await p.screenshot({path:path.join(out,'connexions-'+theme+'.png')})}
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'PASS',checks:['ajout personnalisé','test explicite','clé masquée et non relue','préparation disponible','vrai adaptateur subprocess JSON','désactivation','deux thèmes et jetons','aucune erreur JS']},null,2));console.log('PASS AI connections UI',root);
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(app)app.kill();if(mock)mock.close()});
