'use strict';
// C04 product recipe: real binary, isolated stores and Chromium. No provider is started.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {spawn,spawnSync}=require('node:child_process'),puppeteer=require(process.env.PUPPETEER_MODULE||'puppeteer');
if(!process.argv[2]||!process.argv[3])throw Error('usage: node tests/automation_ui.cjs BINAIRE DOSSIER');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]),temporary=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-c04-'));fs.mkdirSync(out,{recursive:true});
const cli=(root,args,input)=>{const result=spawnSync(binary,['--root',root,'--json',...args,...(input?['--input','-']:[])],{encoding:'utf8',input:input?JSON.stringify(input):undefined,maxBuffer:16*1024*1024});if(result.status!==0)throw Error(`CLI ${args.join(' ')}: ${result.stderr||result.error||result.status}`);return JSON.parse(result.stdout)};
const mutate=(root,args,revision,fields)=>cli(root,args,{schema_version:1,event_id:crypto.randomUUID(),expected_revision:revision,...fields}).work;
function fixture(root){fs.mkdirSync(root,{recursive:true});cli(root,['init']);let work=mutate(root,['work','create'],0,{title:'Programmes C04',objective:'Administrer les programmes sans départ implicite',scope:'root isolé',criteria:['parité'],next:'prévisualiser'});work=mutate(root,['task','add',work.id],work.revision,{id:'source',title:'Source',owner:'worker',deliverable:'docs/source.md',criteria:['preuve'],next:'attendre'});work=mutate(root,['task','add',work.id],work.revision,{id:'target',title:'Cible',owner:'worker',deliverable:'docs/target.md',criteria:['preuve'],depends:['source'],next:'attendre'});return work}
function start(root){const child=spawn(binary,['--root',root,'web','127.0.0.1:0'],{stdio:['ignore','pipe','pipe']});return new Promise((resolve,reject)=>{let text='';const timer=setTimeout(()=>reject(Error('server timeout '+text)),15000);const read=data=>{text+=data;const match=text.match(/http:\/\/[^\s]+\/session\/[^\s]+/);if(match){clearTimeout(timer);resolve({child,url:match[0]})}};child.stdout.on('data',read);child.stderr.on('data',read);child.on('exit',code=>reject(Error('server exit '+code+' '+text)))})}
async function openSettings(page){if(!await page.$eval('#automation details',node=>node.open))await page.click('#automation details summary');await page.waitForFunction(()=>document.querySelector('#automation-config [name=due_grace_seconds]').getBoundingClientRect().height>0)}
async function variant(browser,base,work,name,lang,theme){
 const root=path.join(temporary,name);fs.cpSync(base,root,{recursive:true});const server=await start(root),page=await browser.newPage(),console_errors=[],network_errors=[],expected=new Set(['400:/api/v1/automation/preview','409:/api/v1/automation/state','409:/api/v1/automation/config','400:/api/v1/automation/cancel']);
 page.setDefaultTimeout(25000);await page.setViewport({width:1440,height:1050});page.on('pageerror',error=>console_errors.push(String(error)));page.on('console',message=>{if(message.type()==='error'){const location=message.location().url||'';let pathname='';try{pathname=new URL(location).pathname}catch{}const status=message.text().match(/status of (\d+)/)?.[1];if(!status||!expected.has(status+':'+pathname))console_errors.push(message.text())}});page.on('requestfailed',request=>network_errors.push(request.url()+' '+request.failure()?.errorText));page.on('response',response=>{if(response.status()>=400&&!expected.has(response.status()+':'+new URL(response.url()).pathname))network_errors.push(response.status()+' '+response.url())});
 try{
  const url=new URL(server.url);url.searchParams.set('work',work.id);url.searchParams.set('lang',lang);await page.goto(url.href,{waitUntil:'domcontentloaded'});await page.waitForFunction(id=>snapshot?.work?.id===id&&document.querySelectorAll('.graph-arete').length>0,{},work.id);
  if(await page.$eval('html',node=>node.dataset.theme)!==theme)await page.click('#theme');assert.equal(await page.$eval('html',node=>node.dataset.theme),theme);
  const arrows=await page.$$eval('.graph-arete',nodes=>nodes.length);assert.ok(arrows>0,'graph arrows missing before program administration');
  if(await page.$eval('[data-view=automation]',node=>node.hidden))await page.click('#mode');await page.click('[data-view=automation]');await page.waitForFunction(()=>document.querySelector('#automation-config input'));
  await openSettings(page);const initialConfig=cli(root,['automation','params','show']),savedValues={...initialConfig.values,due_grace_seconds:initialConfig.values.due_grace_seconds+1};
  await page.$eval('#automation-config [name=due_grace_seconds]',(node,value)=>node.value=String(value),savedValues.due_grace_seconds);await page.click('#automation-config button[type=submit]');await page.waitForFunction(revision=>document.querySelector('#automation-config .assist-meta')?.textContent.includes(String(revision)),{},initialConfig.revision+1);
  const savedConfig=cli(root,['automation','params','show']);assert.equal(savedConfig.revision,initialConfig.revision+1);assert.equal(savedConfig.values.due_grace_seconds,savedValues.due_grace_seconds,'UI settings save did not persist');
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#automation-config [name=due_grace_seconds]'));assert.equal(await page.$eval('#automation-config [name=due_grace_seconds]',node=>Number(node.value)),savedValues.due_grace_seconds,'saved setting lost after reload');
  await openSettings(page);const unsavedDue=savedValues.due_grace_seconds+1;await page.$eval('#automation-config [name=due_grace_seconds]',(node,value)=>node.value=String(value),unsavedDue);const concurrentValues={...savedConfig.values,claim_lease_seconds:savedConfig.values.claim_lease_seconds+1};const concurrentConfig=cli(root,['automation','params','apply'],{schema_version:1,expected_revision:savedConfig.revision,values:concurrentValues});await page.click('#automation-config button[type=submit]');await page.waitForFunction(()=>document.querySelector('#automation-state').classList.contains('alert'));
  const settingsError=await page.$eval('#automation-state',node=>node.textContent);assert.match(settingsError,lang==='en'?/settings changed; reload before confirming/:/réglages modifiés ; recharger avant confirmation/);assert.equal(await page.$eval('#automation-config [name=due_grace_seconds]',node=>Number(node.value)),unsavedDue,'conflict discarded the visible draft');assert.deepEqual(cli(root,['automation','params','show']),concurrentConfig,'stale UI settings overwrote concurrent CLI values');
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#automation-config [name=due_grace_seconds]'));
  await page.$eval('#automation-create [name=name]',(node,value)=>node.value=value,'Programme '+name);await page.$eval('#automation-create [name=target]',(node,value)=>node.value=value,work.id);await page.$eval('#automation-create [name=start]',node=>node.value='2099-01-01T09:00:00');
  const before=cli(root,['work','show',work.id]).work,agentsBefore=cli(root,['agent','list',work.id]).agents.length;
  await page.click('#automation-preview');await page.waitForFunction(()=>!document.querySelector('#automation-preview-output').hidden&&!document.querySelector('#automation-create-confirm').disabled);assert.match(await page.$eval('#automation-preview-output',node=>node.textContent),/aucun départ implicite|no implicit start/i);assert.equal(cli(root,['automation','list']).length,0,'preview wrote schedule');
  await page.click('#automation-create-confirm');await page.waitForFunction(()=>document.querySelectorAll('#automation-list article[data-schedule]').length===1);const created=cli(root,['automation','list'])[0];assert.equal(created.schedule.state,'disabled');assert.equal(cli(root,['work','show',work.id]).work.revision,before.revision);assert.equal(cli(root,['agent','list',work.id]).agents.length,agentsBefore);
  const card=()=>`#automation-list article[data-schedule="${created.schedule.schedule_id}"]`;const createdText=await page.$eval(card(),node=>node.textContent);assert.match(createdText,lang==='en'?/Disabled.*Not validated.*Unknown.*Enable after authorization/is:/Désactivé.*Non validée.*Inconnu.*Activer après autorisation/is);assert.doesNotMatch(createdText,/\b(disabled|not_validated|enable_when_authorized)\b/,'machine codes leaked into program card');const enable=await page.$(card()+' .toolbar button:first-child');assert.equal(await enable.evaluate(node=>node.disabled),true,'unauthorized enable exposed');
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(id=>document.querySelector(`article[data-schedule="${id}"]`),{},created.schedule.schedule_id);assert.equal(cli(root,['automation','list']).length,1,'schedule lost after reload');
  cli(root,['automation','pause',created.schedule.schedule_id],{expected_revision:created.schedule.revision});await page.click(card()+' .toolbar button:last-child');await page.waitForFunction(()=>document.querySelector('#automation-state').classList.contains('alert'));assert.match(await page.$eval('#automation-state',node=>node.textContent),/modifi|changed|reload/i);
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(([id,label])=>document.querySelector(`article[data-schedule="${id}"]`)?.textContent.includes(label),{},[created.schedule.schedule_id,lang==='en'?'Paused':'Suspendu']);assert.equal(cli(root,['automation','show',created.schedule.schedule_id]).schedule.state,'paused');
  await page.$eval('#automation-create [name=timezone]',node=>node.value='Local');await page.$eval('#automation-create [name=name]',node=>node.value='Fuseau refusé');await page.$eval('#automation-create [name=target]',(node,value)=>node.value=value,work.id);await page.$eval('#automation-create [name=start]',node=>node.value='2099-01-01T09:00:00');await page.click('#automation-preview');await page.waitForFunction(()=>document.querySelector('#automation-state').classList.contains('alert'));const timezoneError=await page.$eval('#automation-state',node=>node.textContent);assert.match(timezoneError,lang==='en'?/explicit IANA timezone required; UTC is accepted/:/fuseau IANA explicite requis ; UTC est accepté/);if(lang==='en')assert.doesNotMatch(timezoneError,/fuseau|accepté/,'French timezone error leaked into English UI');
  const cancelResult=await page.evaluate(async()=>{const response=await fetch('/api/v1/automation/cancel',{method:'POST',headers:{'Content-Type':'application/json','X-Swarm-CSRF':csrf},body:JSON.stringify({occurrence_id:'missing-occurrence',expected_revision:1})});return {status:response.status,body:await response.text()}});assert.equal(cancelResult.status,400);assert.match(cancelResult.body,/unknown_occurrence/);
  const help=await page.$('#automation-help');await help.focus();await page.keyboard.press('Enter');await page.waitForSelector('#modal[open]');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#modal').open);assert.equal(await page.evaluate(node=>node===document.activeElement,help),true,'help focus not restored');
  assert.ok(await page.$$eval('.graph-arete',nodes=>nodes.length)>0,'graph removed by Programs UI');const screenshot=name+'.png';await page.screenshot({path:path.join(out,screenshot),fullPage:true});assert.deepEqual(console_errors,[]);assert.deepEqual(network_errors,[]);
  return {variant:name,screenshot,assertions:{preview_no_effect:true,save_reload:true,pause_cancel:true,conflict:true,timezone:true,permission:true,unknown_cost:true,focus_restore:true,no_implicit_launch:true,graph_preserved:true},console_errors,network_errors,schedule_id:created.schedule.schedule_id};
 }catch(error){await page.screenshot({path:path.join(out,name+'-failure.png'),fullPage:true});throw error}finally{await page.close();server.child.kill('SIGTERM')}
}
(async()=>{const base=path.join(temporary,'base'),work=fixture(base),browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',userDataDir:path.join(temporary,'chrome'),args:['--no-sandbox','--disable-dev-shm-usage']});try{const variants=[];for(const [name,lang,theme]of[['fr-sombre','fr','sombre'],['fr-etat','fr','etat'],['en-sombre','en','sombre'],['en-etat','en','etat']])variants.push(await variant(browser,base,work,name,lang,theme));const results={schema_version:1,surface:'swarm-product',environment:{platform:`${os.platform()} ${os.release()} ${os.arch()}`,browser:await browser.version(),binary,isolated_root:true,provider_started:false},variants};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2))}finally{await browser.close()}})().catch(error=>{fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:error.stack},null,2));console.error(error);process.exitCode=1});
