const fs=require('fs'),path=require('path'),{spawn,execFileSync}=require('child_process'),pup=require(process.env.PUPPETEER_MODULE||'puppeteer');
const binary=process.argv[2],dir=process.argv[3];fs.mkdirSync(dir,{recursive:true});
(async()=>{const root=execFileSync('python3',['tools/swarm-companion/tests/web_fixture.py',binary],{encoding:'utf8'}).trim();
fs.writeFileSync(root+'/provider.py',`#!/usr/bin/python3
import sys,re,time,json
from pathlib import Path
p=sys.stdin.read(); task=re.search(r'Tâche (brain-[^:]+):',p).group(1)
Path('last-prompt.txt').write_text(p)
print(json.dumps({'type':'system'}),flush=True)
time.sleep(2)
Path('docs/'+task+'-brainstorm.md').write_text('# Brainstorming APEX\\n\\nFaits : fixture de recette.\\nOptions : A simple, B modulaire.\\nQuestion : quel périmètre ?\\nMissions : analyse puis réalisation.\\nGates : tests à définir, aucun PASS revendiqué.\\n')
print(json.dumps({'type':'result','result':'# Brainstorming APEX\\nOptions : A simple, B modulaire. Question : quel périmètre ?','usage':{'input_tokens':10,'output_tokens':20}}),flush=True)
`);fs.chmodSync(root+'/provider.py',0o700);
const server=spawn(binary,['--root',root,'web']);let output='';server.stdout.on('data',d=>output+=d);while(!output.includes('/session/'))await new Promise(r=>setTimeout(r,100));const url=output.match(/http:\/\/\S+/)[0];const browser=await pup.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});const errors=[];try{const p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width:1440,height:1050});await p.goto(url);await p.waitForSelector('[data-task="UI-01"]');await p.waitForSelector('#mode');if(await p.evaluate(()=>document.body.dataset.mode)==='conduite'){await p.click('#mode');await p.waitForFunction(()=>document.body.dataset.mode==='expert')};await p.click('[data-view="brainstorm"]');
async function send(message){await p.type('#brain-question',message);await p.click('#brain-send');await p.waitForSelector('#modal[open] #field-provider',{visible:true});await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’envoi à l’IA');await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal').open);}
await p.type('#brain-question','Comparer les options avant de préparer les agents.');await p.click('#brain-send');await p.waitForSelector('#modal[open] #field-provider',{visible:true});for(const theme of ['etat','sombre']){if(await p.$eval('html',e=>e.dataset.theme)!==theme)await p.click('#cancel').then(()=>p.click('#theme')).then(()=>p.click('#brain-send'));await p.screenshot({path:dir+'/'+theme+'-dialog.png',fullPage:true});}
await p.keyboard.press('Escape');if(await p.$eval('#brain-messages',e=>e.querySelectorAll('article').length)!==0)throw Error('Cancel started agent');await p.click('#brain-send');await p.waitForSelector('#modal[open] #field-provider',{visible:true});await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’envoi à l’IA');await p.click('#confirm');await p.waitForFunction(()=>document.querySelectorAll('#brain-messages pre').length===1);await p.waitForFunction(()=>!document.querySelector('#brain-send').disabled);
await send('Je retiens B, sépare analyse et réalisation.');await p.waitForFunction(()=>document.querySelectorAll('#brain-messages pre').length===2);await p.waitForFunction(()=>!document.querySelector('#brain-send').disabled);const prompt=fs.readFileSync(root+'/last-prompt.txt','utf8');if(!prompt.includes('Comparer les options')||!prompt.includes('Quel périmètre')&&!prompt.includes('quel périmètre'))throw Error('Context missing');
await p.locator('#brain-messages article:last-child button::-p-text(Examiner et adopter ce brief)').click();await p.waitForSelector('#modal[open]',{visible:true});
await p.setRequestInterception(true);const failAdoption=req=>{if((req.postData()||'').includes('adopt-brief'))req.abort();else req.continue()};p.on('request',failAdoption);await p.click('#confirm');await p.waitForSelector('#modal-error:not([hidden])');if(await p.$eval('#confirm',e=>e.textContent)!=='Réessayer l’adoption')throw Error('No actionable adoption failure');for(const theme of ['etat','sombre']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);await p.screenshot({path:dir+'/'+theme+'-adoption-error.png'});}p.off('request',failAdoption);await p.setRequestInterception(false);await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal').open&&document.querySelector('#brief-current details').open);if(!(await p.$eval('#message',e=>e.textContent)).includes('Brief adopté et enregistré'))throw Error('Missing explicit adoption receipt');if(await p.evaluate(()=>document.activeElement.id)!=='brief-current')throw Error('Adopted brief not focused');for(const theme of ['etat','sombre']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);await p.screenshot({path:dir+'/'+theme+'-adoption-success.png'});}

await p.reload();await p.waitForSelector('[data-task="UI-01"]');await p.click('[data-view="brainstorm"]');await p.waitForFunction(()=>document.querySelectorAll('#brain-messages pre').length===2);for(const theme of ['etat','sombre']){if(await p.$eval('html',e=>e.dataset.theme)!==theme)await p.click('#theme');await p.screenshot({path:dir+'/'+theme+'-conversation.png',fullPage:true});}
await p.click('#brain-retex');if(!(await p.$eval('#brain-question',e=>e.value)).includes('trois quick wins'))throw Error('RETEX preset missing');await p.click('#brain-export');if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync(dir+'/ui.json',JSON.stringify({status:'PASS',root,checks:['cancel without launch','AI provider launch from UI','two turns with context','adopt after reading','persist across reload','both themes'],errors},null,2));console.log('PASS '+root);
}catch(e){fs.writeFileSync(dir+'/failure.txt',e.stack);throw e}finally{await browser.close();server.kill()}})().catch(e=>{console.error(e);process.exitCode=1});
