// Real provider integration through browser controls; isolated disposable work.
const fs=require('fs'),path=require('path'),{spawn,execFileSync}=require('child_process'),pup=require('puppeteer');
const binary=path.resolve(process.argv[2]),dir=path.resolve(process.argv[3]);fs.mkdirSync(dir,{recursive:true});
(async()=>{const root=execFileSync('python3',['tools/swarm-companion/tests/web_fixture.py',binary],{encoding:'utf8'}).trim();const config=JSON.parse(fs.readFileSync('.swarm/providers.json'));fs.writeFileSync(root+'/.swarm/providers.json',JSON.stringify({schema_version:1,providers:{claude:config.providers.claude}}));
const server=spawn(binary,['--root',root,'web']);let output='';server.stdout.on('data',d=>output+=d);for(let i=0;!output.includes('/session/');i++){if(i>100)throw Error('Server timeout');await new Promise(r=>setTimeout(r,100));}const url=output.match(/http:\/\/\S+/)[0];const browser=await pup.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const errors=[],checks=[];let page,testWork;
try{page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width:1440,height:1050});await page.goto(url);await page.waitForSelector('[data-task="UI-01"]');testWork=await page.$eval('#work',e=>e.value);await page.click('[data-view="brainstorm"]');
const nonce='BRIEF-'+Date.now();
async function send(text,count){await page.type('#brain-question',text);await page.click('#brain-send');await page.waitForSelector('#modal[open] #field-provider');await page.select('#field-provider','claude');await page.click('#confirm');await page.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’envoi à l’IA');const context=await page.$eval('#preview',e=>e.textContent);if(count===2&&!context.includes(nonce))throw Error('Prior exchange missing from actual context');await page.click('#confirm');await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.waitForFunction(n=>document.querySelectorAll('#brain-messages article').length===n&&!document.querySelector('#brain-send').disabled,{timeout:180000},count);const last=await page.$eval('#brain-messages article:last-child',e=>e.textContent);if(!last.includes(nonce))throw Error('Actual Claude response missing remembered marker: '+last.slice(-1000));console.log('Claude exchange '+count+' completed');}
await page.type('#brain-question','Essai annulé');await page.click('#brain-send');await page.click('#confirm');await page.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’envoi à l’IA');await page.keyboard.press('Escape');if(await page.$eval('#brain-messages',e=>e.children.length)>1)throw Error('Cancel launched a turn');await page.click('#brain-question',{clickCount:3});await page.keyboard.press('Backspace');checks.push('context preview cancelled without launch');
await send('Test de briefing uniquement. Aucun outil, aucun fichier à lire ou écrire, aucun code, aucune délégation. Réponds en moins de 80 mots : un brief de recette pour un partage de fichiers fictif, avec objectif, deux critères observables et condition d’arrêt. Inclus exactement ce repère : '+nonce+'.',1);checks.push('real Claude answer through browser send and context confirmation');
await send('Sans utiliser d’outil, rappelle le repère exact de notre précédent échange, puis propose une prochaine action de recette en une phrase. Aucun code ni changement de fichier.',2);checks.push('second real answer remembers prior exchange');
await page.locator('#brain-messages article:last-child button::-p-text(Examiner et adopter ce brief)').click();await page.waitForSelector('#modal[open]');const reviewed=await page.$eval('#preview',e=>e.textContent);await page.click('#modal-help-toggle');await page.click('#modal-help-toggle');await page.click('#confirm');await page.waitForFunction(()=>!document.querySelector('#modal').open&&document.querySelector('#brief-current details').open);if(await page.$eval('#brief-current pre',e=>e.textContent)!==reviewed)throw Error('Adopted text differs from reviewed text');checks.push('review, contextual help, adoption and exact saved text');
for(const theme of ['etat','sombre']){await page.click('#theme');if(await page.$eval('html',e=>e.dataset.theme)!==theme)await page.click('#theme');await page.screenshot({path:dir+'/'+theme+'-adopted.png'});}
await page.reload();await page.waitForSelector('[data-task="UI-01"]');await page.click('[data-view="brainstorm"]');await page.waitForSelector('#brief-current pre');if(await page.$eval('#brief-current pre',e=>e.textContent)!==reviewed)throw Error('Adoption not persisted');checks.push('reload retains both answers and exact adopted brief');
await page.type('#brain-question','Vérifier le prochain contexte sans envoyer.');await page.click('#brain-send');await page.click('#confirm');await page.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’envoi à l’IA');if(!(await page.$eval('#preview',e=>e.textContent)).includes(reviewed))throw Error('Adopted brief missing from next prompt');await page.keyboard.press('Escape');checks.push('adopted brief present in next prompt preview, cancelled before launch');
if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync(dir+'/real-ui.json',JSON.stringify({status:'PASS',root,provider:'claude',model_calls:2,checks,errors},null,2));console.log('Real briefing UI PASS');
}catch(e){fs.writeFileSync(dir+'/failure.txt',e.stack);if(page)await page.screenshot({path:dir+'/failure.png'});throw e}finally{await browser.close();server.kill();const listed=JSON.parse(execFileSync(binary,['--root',root,'--json','agent','list',testWork],{encoding:'utf8'}));for(const item of listed.agents||[]){const a=item.agent;if(['queued','running','starting','stopping'].includes(a.status))execFileSync(binary,['--root',root,'agent','stop',a.id]);}}})().catch(e=>{console.error(e);process.exitCode=1});
