'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawn,execFileSync}=require('node:child_process'),puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});let browser;
function cli(root,args,input){return JSON.parse(execFileSync(binary,['--root',root,'--json',...args,...(input?['--input','-']:[])],{encoding:'utf8',input:input?JSON.stringify(input):undefined}))}
async function start(root){const child=spawn(binary,['--root',root,'web','127.0.0.1:0']);return new Promise((resolve,reject)=>{let text='';const timer=setTimeout(()=>reject(Error('server timeout '+text)),20000);child.stdout.on('data',x=>{text+=x;const m=text.match(/http:\/\/[^\s]+\/session\/[^\s]+/);if(m){clearTimeout(timer);resolve({child,url:m[0]})}});child.stderr.on('data',x=>text+=x);child.on('exit',c=>{clearTimeout(timer);reject(Error(text+' exit '+c))})})}
(async()=>{browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox','--disable-dev-shm-usage']});const checks=[];
 try{for(const lang of ['fr','en'])for(const theme of ['sombre','etat']){
  const name=lang+'-'+theme,root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-targets-'+name+'-'));cli(root,['init']);const work=cli(root,['work','create'],{schema_version:1,event_id:'fixture',expected_revision:0,title:'Performance settings',objective:'Configure graph targets',scope:'isolated',criteria:['configuration persists']}).work;
  const server=await start(root),page=await browser.newPage(),errors=[],responses=[];page.setDefaultTimeout(25000);page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=400)responses.push([r.status(),new URL(r.url()).pathname])});await page.setViewport({width:1400,height:1000});
  try{const u=new URL(server.url);u.searchParams.set('work',work.id);u.searchParams.set('lang',lang);await page.goto(u.href);await page.waitForFunction(()=>snapshot?.work);await page.evaluate(t=>setTheme(t),theme);
   if(await page.$eval('[data-view="admin"]',e=>e.getClientRects().length===0))await page.click('#mode');await page.click('[data-view="admin"]');await page.waitForSelector('#graph-performance-edit:not([disabled])');
   assert.match(await page.$eval('#graph-performance-admin h3',e=>e.textContent),lang==='en'?/Graph performance targets/:/Objectifs de performance/);
   const original=cli(root,['run-limits','performance','show']);await page.click('#graph-performance-edit');await page.waitForSelector('#graph-performance-modal[open]');assert.equal(await page.evaluate(()=>document.activeElement.id),'performance-keyboard');
   for(const [selector,value]of [['#performance-keyboard','137'],['#performance-samples','7'],['#performance-reason','New responsiveness targets for isolated test']]){await page.click(selector);await page.keyboard.down('Control');await page.keyboard.press('A');await page.keyboard.up('Control');await page.type(selector,value)}
   await page.click('#performance-confirm');await page.waitForSelector('#performance-preview:not([hidden])');assert.equal(cli(root,['run-limits','performance','show']).revision,original.revision);await page.screenshot({path:path.join(out,'targets-'+name+'.png')});
   await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#graph-performance-modal'));assert.equal(await page.evaluate(()=>document.activeElement.id),'graph-performance-edit');assert.equal(cli(root,['run-limits','performance','show']).revision,0);
   await page.click('#graph-performance-edit');await page.waitForSelector('#performance-keyboard');await page.$eval('#performance-keyboard',e=>{e.value='137';e.dispatchEvent(new Event('input',{bubbles:true}))});await page.type('#performance-reason','New responsiveness targets for isolated test');await page.click('#performance-confirm');await page.waitForSelector('#performance-preview:not([hidden])');await page.click('#performance-confirm');await page.waitForFunction(()=>!document.querySelector('#graph-performance-modal'));let saved=cli(root,['run-limits','performance','show']);assert.equal(saved.values.keyboard_p95_ms,137);assert.equal(saved.history.length,1);
   await page.reload();await page.waitForSelector('#graph-performance-edit:not([disabled])');if(await page.$eval('[data-view="admin"]',e=>e.getClientRects().length===0))await page.click('#mode');await page.click('[data-view="admin"]');assert.match(await page.$eval('#graph-performance-admin',e=>e.textContent),/137/);
   await page.click('#graph-performance-edit');await page.type('#performance-reason','Expected conflict after concurrent CLI edit');const changed=cli(root,['run-limits','performance','apply'],{schema_version:1,event_id:'outside',expected_revision:saved.revision,values:{...saved.values,keyboard_p95_ms:143},reason:'Concurrent edit through the public CLI'}).config;
   await page.click('#performance-confirm');await page.waitForSelector('#performance-error:not([hidden])');assert.match(await page.$eval('#performance-error',e=>e.textContent),/Configuration modifiée|Configuration changed/);assert.equal(cli(root,['run-limits','performance','show']).revision,changed.revision);await page.keyboard.press('Escape');await page.click('#graph-performance-reload');await page.waitForFunction(()=>document.querySelector('#graph-performance-admin').textContent.includes('143'));await page.screenshot({path:path.join(out,'targets-saved-'+name+'.png')});
   assert.deepEqual(errors,[]);assert.deepEqual(responses,[[409,'/api/v1/graph-performance/preview']]);checks.push({variant:name,preview_no_write:true,persistence:true,cli_web_parity:true,stale_conflict:true,escape_focus:true,errors,expected_http_conflict:responses,config_revision:changed.revision});
  }finally{await page.close();server.child.kill('SIGTERM');fs.rmSync(root,{recursive:true,force:true})}
 }
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(checks,null,2));console.log(JSON.stringify(checks));
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
