'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn,execFileSync}=require('node:child_process');
let puppeteer;try{puppeteer=require('puppeteer')}catch(e){console.error('journey dependency missing: puppeteer');process.exit(3)}
const binary=path.resolve(process.argv[2]),report=path.resolve(process.argv[3]);fs.mkdirSync(report,{recursive:true});
if(!fs.existsSync(binary)){console.error('journey dependency missing: built swarm binary');process.exit(3)}
const externalURL=process.env.SWARM_JOURNEY_URL||'',project=process.env.SWARM_JOURNEY_ROOT||fs.mkdtempSync(path.join(report,'project-'));
if(!externalURL){execFileSync(binary,['--root',project,'init'],{encoding:'utf8'});for(const name of ['.claude/skills/apex/SKILL.md','tools/agent-workflows/CONTRACT.md']){const target=path.join(project,name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,'Méthode de recette isolée.\n')}const provider=path.join(project,'claude');fs.writeFileSync(provider,"#!/bin/sh\nif [ \"$1\" = \"--swarm-preflight\" ]; then printf '%s\\n' '{\"schema_version\":1,\"capabilities\":{\"process\":\"verified\",\"workspace_read\":\"verified\",\"workspace_write\":\"verified\"}}'; exit 0; fi\ncat >/dev/null\nprintf '%s\\n' '{\"type\":\"result\",\"result\":\"{}\"}'\n",{mode:0o700});fs.writeFileSync(path.join(project,'.swarm/providers.json'),JSON.stringify({schema_version:1,providers:{recette:{command:provider,preflight_required:true,preflight_args:['--swarm-preflight'],preflight_kind:'provider-context',preflight_capabilities:['process','workspace_read','workspace_write']}}}))}
const server=externalURL?null:spawn(binary,['--root',project,'web','127.0.0.1:0'],{stdio:['ignore','pipe','pipe']});let browser,page;
const plan=JSON.stringify({version:1,objective:'Créer un livrable vérifié',assumptions:[],questions:[],tasks:[{id:'T1',title:'Produire le livrable',role:'worker',scope:'docs',deliverable:'docs/resultat.md',depends:[],criteria:['Le livrable existe et est relu'],proof:'Commande de contrôle et rapport',entry:'Brief adopté',validation:'Exécuter le contrôle annoncé',delivery:'Livrable et preuve fraîche',stop:'Arrêter après deux échecs identiques',max_attempts:2,max_tool_calls:20}]},null,2);
async function fill(selector,value){await page.click(selector,{clickCount:3});await page.keyboard.press('Backspace');await page.type(selector,value)}
async function waitAction(value){await page.waitForFunction(v=>document.getElementById('advance')?.dataset.action===v,{},value)}
(async()=>{try{
 const url=externalURL||await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(Error('journey web server did not start')),15000);server.stdout.on('data',data=>{output+=data;const match=output.match(/http:\/\/\S+\/session\/\S+/);if(match){clearTimeout(timer);resolve(match[0])}});server.on('exit',code=>reject(Error('journey web server exited '+code)))});
 browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox'],userDataDir:fs.mkdtempSync(path.join(os.tmpdir(),'swarm-journey-browser-'))});page=await browser.newPage();page.setDefaultTimeout(15000);await page.setViewport({width:1280,height:900});const errors=[];page.on('pageerror',e=>errors.push(e.message));const sessionResponse=await page.goto(url,{waitUntil:'domcontentloaded'});assert.ok(sessionResponse?.ok(),`session bootstrap failed: ${sessionResponse?.status()??'no response'}`);const preparationResponse=await page.goto(new URL('/prepare.html',url).href,{waitUntil:'domcontentloaded'});assert.ok(preparationResponse?.ok(),`preparation page failed: ${preparationResponse?.status()??'no response'}`);
 await page.waitForSelector('#create-form:not([hidden])');await fill('#new-title','Parcours sans expertise');await fill('#new-need','Je veux un livrable documenté, contrôlé et traçable.');await page.click('#create');await page.waitForSelector('#documents:not([hidden])');const preparationID=new URL(page.url()).searchParams.get('id');assert.ok(preparationID,'preparation id absent after browser creation');
 await page.click('#advance');await page.waitForFunction(()=>document.getElementById('tab-brief').getAttribute('aria-selected')==='true');if(await page.$eval('#plain-editor',e=>e.hidden))await page.click('#editor-toggle');await fill('#plain-editor','# Brief\n\nObjectif : produire un livrable contrôlé.');await waitAction('save');await page.click('#advance');await waitAction('adopt');await page.click('#advance');await waitAction('plan');await page.click('#advance');await page.waitForFunction(()=>document.getElementById('tab-plan').getAttribute('aria-selected')==='true');await fill('#plain-editor',plan);await waitAction('save');await page.click('#advance');await waitAction('validate');await page.click('#advance');await waitAction('convert');
 await page.click('#history');await page.waitForSelector('#history-dialog[open]');assert.ok(await page.$$eval('#history-content details',nodes=>nodes.length)>=1,'plan history absent');await page.keyboard.press('Escape');
 await page.click('#advance');await page.waitForSelector('#conversion-dialog[open]');assert.equal(await page.$$eval('#conversion-missions li',nodes=>nodes.length),1);await page.select('#organization-provider','recette');await page.select('#organization-validation','human');await page.waitForFunction(()=>document.getElementById('organization-model').textContent.includes('Modèles résolus'));assert.match(await page.$eval('#summary-owner',e=>e.textContent),/recette/);assert.match(await page.$eval('#summary-workers',e=>e.textContent),/1/);assert.match(await page.$eval('#summary-review',e=>e.textContent),/recette/);assert.equal(await page.$eval('#conversion-confirm',e=>e.disabled),true,'authorization enabled before preflight');
 let authorizations=0;page.on('request',request=>{if(request.method()==='POST'&&request.url().endsWith('/preparations/command')){try{if(JSON.parse(request.postData()).action==='authorize-plan')authorizations++}catch{}}});await page.click('#organization-preflight');await page.waitForFunction(()=>document.getElementById('organization-preflight-status').classList.contains('success'));assert.match(await page.$eval('#organization-preflight-status',e=>e.textContent),/verified/);assert.equal(await page.$eval('#conversion-confirm',e=>e.disabled),false);assert.equal(authorizations,0,'preflight silently authorized or started work');
 for(const theme of ['etat','sombre']){if(await page.$eval('html',e=>e.dataset.theme)!==theme)await page.click('#theme');await page.screenshot({path:path.join(report,'journey-'+theme+'.png'),fullPage:true})}
 await page.click('#conversion-confirm');await page.waitForSelector('#conversion-dialog:not([open])');assert.equal(authorizations,1,'single explicit authorization command required');const state=await page.evaluate(async id=>(await fetch('/api/v1/preparations/show?id='+encodeURIComponent(id))).json(),preparationID);assert.ok(state.conversion?.released_at,'departure authorization not recorded');assert.equal(state.documents.plan.text,plan,'authorized plan revision changed');
 await page.click('#history');await page.waitForSelector('#history-dialog[open]');assert.ok(await page.$$eval('#history-content details',nodes=>nodes.length)>=1,'history lost after authorization');await page.keyboard.press('Escape');await page.setViewport({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(report,'result.json'),JSON.stringify({status:'PASS',preparation_id:preparationID,work_id:state.work_id,authorization_requests:authorizations,preflight:'verified',browser:await browser.version(),database_writes:'CLI init and browser/API only; no direct database access'},null,2));console.log('journey acceptance: PASS — browser need to explicit departure authorization');
}catch(e){fs.writeFileSync(path.join(report,'failure.txt'),e.stack);throw e}finally{await browser?.close();server?.kill('SIGTERM')}})().catch(e=>{console.error(e);process.exitCode=1});
