const fs=require('fs'),path=require('path'),{spawn,execFileSync}=require('child_process'),pup=require('puppeteer');
const binary=process.argv[2],dir=path.resolve(process.argv[3]);fs.mkdirSync(dir,{recursive:true});
(async()=>{
 const root=execFileSync('python3',['tools/swarm-companion/tests/web_fixture.py',binary],{encoding:'utf8'}).trim();
 execFileSync('python3',['-c',`import sqlite3,json,sys
p=sys.argv[1];c=sqlite3.connect(p+'/.swarm/state.db');row=c.execute('select id,body from works').fetchone();w=json.loads(row[1])
for i in range(6):
 q='Décision historique '+str(i);a='Réponse source ancienne '+str(i)
 w['tasks'].append(dict(id='old-'+str(i),title=q,brainstorm=True,question=q,response=a,answers=[dict(attempt='a'+str(i),text=a,at='2026-09-12')],status='blocked',criteria=[],depends=[],attempts=[]))
c.execute('update works set body=? where id=?',(json.dumps(w),row[0]));c.commit()`,root]);
 fs.writeFileSync(root+'/provider.py',`#!/usr/bin/python3
import sys,re,time,json,hashlib
from pathlib import Path
p=sys.stdin.read();task=re.search(r'Tâche ([^:]+):',p).group(1);Path('last-prompt.txt').write_text(p)
print(json.dumps({'type':'system'}),flush=True);time.sleep(1)
report='docs/'+task+'-handoff.md';Path(report).write_text('# Preuve de recette\\nParcours synthétique, aucun résultat métier.\\n')
e={'method_version':'2','scope_id':task,'artifacts':{report:hashlib.sha256(Path(report).read_bytes()).hexdigest()},'domains':{'quality':1},'checks':[{'id':'ui','domain':'quality','mandatory':True,'gate':'delivery','penalty':100,'max_penalty':100,'severity':'major'}],'results':[{'id':'ui','status':'PASS','count':0,'evidence':[report]}]};Path('docs/'+task+'.json').write_text(json.dumps(e))
print(json.dumps({'type':'result','result':'# RETEX de recette\\nConstat : une ancienne décision doit pouvoir être retrouvée.\\nProposition : joindre une réponse source.\\nCritère : vérifier le contexte transmis.'}),flush=True)
`);fs.chmodSync(root+'/provider.py',0o700);
 const server=spawn(binary,['--root',root,'web']);let output='';server.stdout.on('data',d=>output+=d);let deadline=Date.now()+10000;while(!output.includes('/session/')){if(Date.now()>deadline)throw Error('Server timeout');await new Promise(r=>setTimeout(r,100))}const url=output.match(/http:\/\/\S+/)[0];
 const browser=await pup.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const errors=[],checks=[];
 try{
 const p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width:1440,height:1100});await p.goto(url);await p.waitForSelector('[data-task="UI-01"]');await p.click('[data-view="brainstorm"]');
 async function click(text,scope='body'){await p.locator(scope+' button::-p-text('+text+')').click()}
 async function fill(sel,v){await p.click(sel,{clickCount:3});await p.type(sel,v)}
 async function closed(){await p.waitForFunction(()=>!document.querySelector('#modal').open)}
 async function shot(name){for(const theme of ['etat','sombre']){if(await p.$eval('html',e=>e.dataset.theme)!==theme){if(await p.$eval('#modal',e=>e.open)){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme)}else await p.click('#theme')}const css=['cockpit.css','cockpit-ux.css'].map(f=>fs.readFileSync('tools/swarm-companion/web/'+f,'utf8')).join('\n');const refs=[...css.matchAll(/var\((--wattson-[\w-]+)/g)].map(m=>m[1]);const missing=await p.evaluate(names=>names.filter(n=>!getComputedStyle(document.documentElement).getPropertyValue(n).trim()),refs);if(missing.length)throw Error('Undefined theme tokens '+missing);await p.screenshot({path:dir+'/'+theme+'-'+name+'.png',fullPage:!await p.$eval('#modal',e=>e.open)})}}
 await p.click('#brain-help');await p.waitForSelector('#help-search');await shot('help');await p.type('#help-search','introuvablexyz');await p.waitForFunction(()=>document.querySelector('#help-results-state').textContent.includes('Aucune'));await fill('#help-search','budget');await p.waitForSelector('[data-topic="budget"]');await p.keyboard.press('Escape');await closed();if(await p.evaluate(()=>document.activeElement.id)!=='brain-help')throw Error('Help focus not restored');checks.push('searchable help, no result, Escape and focus restoration');
 await p.click('.memory-search summary');
 await p.click('#brain-search-form button');await p.waitForFunction(()=>document.querySelector('#brain-search-state').textContent.includes('Saisissez'));
 await p.type('#brain-search','introuvable-xyz');await p.click('#brain-search-form button');await p.waitForFunction(()=>document.querySelector('#brain-search-state').textContent.includes('Aucun résultat'));
 await p.setRequestInterception(true);const abortSearch=req=>{if(req.url().endsWith('/api/v1/action')&&(req.postData()||'').includes('dialogue-search'))req.abort();else req.continue()};p.on('request',abortSearch);
 await fill('#brain-search','decision');await p.click('#brain-search-form button');await p.waitForFunction(()=>document.querySelector('#brain-search-state').textContent.includes('Recherche impossible'));p.off('request',abortSearch);await p.setRequestInterception(false);
 checks.push('search empty, no result and explicit network failure');
 await fill('#brain-search','decision');await p.click('#brain-search-form button');await p.waitForFunction(()=>document.querySelector('#brain-search-state').textContent.includes('6 réponse'));await click('Lire la réponse source','#brain-search-results');await p.waitForSelector('#modal[open]');if(!(await p.$eval('#preview',e=>e.textContent)).includes('ancienne 0'))throw Error('wrong source');await p.keyboard.press('Escape');await closed();await click('Joindre au prochain message','#brain-search-results');
 await p.type('#brain-question','Reprendre la décision ancienne');await p.click('#brain-send');await p.click('#modal-help-toggle');await p.waitForSelector('#modal-help:not([hidden])');await shot('contextual-help');await p.click('#modal-help-toggle');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’envoi à l’IA');const pre=await p.$eval('#preview',e=>e.textContent);if(!pre.includes('ancienne 0')||!pre.includes('Décision historique 0 ; Décision historique 1'))throw Error('missing selected or excluded context');await shot('context');
 await p.keyboard.press('Escape');await closed();if(fs.existsSync(root+'/last-prompt.txt'))throw Error('cancel launched agent');checks.push('search accents, original source, attachment and cancel without launch');
 await p.click('#brain-send');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’envoi à l’IA');
 fs.mkdirSync(root+'/.claude/field-guide',{recursive:true});fs.writeFileSync(root+'/.claude/field-guide/index.md','# Guide modifié pendant la revue\n');
 await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal-error').hidden&&document.querySelector('#modal-error').textContent.includes('Contexte modifié'));if(fs.existsSync(root+'/last-prompt.txt'))throw Error('Stale context launched agent');await p.keyboard.press('Escape');checks.push('changed guide invalidates exact prompt preview without launch');
 await p.click('#brain-send');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’envoi à l’IA');await p.click('#confirm');await closed();await p.waitForFunction(()=>document.querySelectorAll('#brain-messages article').length===7&&!document.querySelector('#brain-send').disabled);if(!fs.readFileSync(root+'/last-prompt.txt','utf8').includes('ancienne 0'))throw Error('attachment missing from real prompt');checks.push('preview and actual supervised provider prompt');
 await click('Contexte de cette tentative','#brain-messages');await p.waitForSelector('#modal[open]');if(!(await p.$eval('#preview',e=>e.textContent)).includes('ancienne 0'))throw Error('saved context missing');await p.keyboard.press('Escape');
 await click('Examiner un RETEX issu de cette réponse','#brain-messages');await fill('#field-problem','Retrouver une décision oubliée');await p.select('#field-nature','fait');await fill('#field-proposal','Afficher les échanges sélectionnés');await fill('#field-risk','Réponse provenant du mauvais travail');await fill('#field-criteria','Le prompt contient la réponse source choisie');await fill('#field-proof','Rapport de recette de la tâche APEX et gate associée');await shot('retex-edit');await p.click('#confirm');await closed();await p.click('#retex-list').catch(()=>{});await p.evaluate(()=>document.querySelector('#retex-list').parentElement.open=true);await p.waitForSelector('[data-retex]');
 await click('Créer une tâche APEX','#retex-list');await p.click('#confirm');await closed();await p.waitForFunction(()=>document.querySelector('#retex-list').textContent.includes('Piloter la tâche APEX'));await click('Changer l’état du RETEX','#retex-list');await p.select('#field-note','verifie');await p.click('#confirm');await p.waitForSelector('#modal-error:not([hidden])');await shot('verification-refused');await p.keyboard.press('Escape');checks.push('RETex source, editable fields, task creation and unverified rejection');
 await click('Exporter le RETEX en Markdown','#retex-list');await p.click('#confirm');await closed();await p.waitForFunction(()=>document.querySelector('#retex-list').textContent.includes('enregistré'));const exportFiles=fs.readdirSync(root+'/docs/retex/swarm');if(exportFiles.length!==1)throw Error('export missing');
 // Use the existing operator workflow from the browser for every task transition.
 await click('Piloter la tâche APEX','#retex-list');await p.waitForSelector('#modal[open] #field-provider');const title=await p.$eval('#modal-title',e=>e.textContent);const task=title.split(' — ')[0];await p.click('#confirm');await closed();await p.waitForFunction(()=>document.querySelector('#active-count').textContent==='0');await new Promise(r=>setTimeout(r,1500));
 async function taskAction(action){await click('Piloter la tâche APEX','#retex-list');await p.waitForSelector('#field-action');await p.select('#field-action',action)}
 await taskAction('submit');await fill('#field-path','docs/'+task+'-handoff.md');await p.click('#confirm');await closed();
 await taskAction('gate');await fill('#field-path','docs/'+task+'.json');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’enregistrement');await p.click('#confirm');await closed();
 await taskAction('accepted');await p.click('#confirm');await closed();
 await click('Changer l’état du RETEX','#retex-list');await p.select('#field-note','verifie');await p.click('#confirm');await closed();await p.waitForFunction(()=>document.querySelector('#retex-list').textContent.includes('Proposer une leçon'));
 await click('Proposer une leçon au Guide','#retex-list');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Publier la leçon vérifiée');await shot('guide-review');await p.click('#confirm');await closed();await p.waitForFunction(()=>document.querySelector('#retex-list').textContent.includes('Leçon publiée'));checks.push('task launch, submit, gate preview, acceptance, RETEX verification and reviewed guide publication through UI');
 await p.reload();await p.waitForSelector('[data-task="UI-01"]');await p.click('[data-view="brainstorm"]');await p.evaluate(()=>document.querySelector('#retex-list').parentElement.open=true);await p.waitForFunction(()=>document.querySelector('#retex-list').textContent.includes('Leçon publiée'));await shot('reloaded');checks.push('reload persistence in both themes');
 await p.setViewport({width:390,height:844});await shot('mobile');if(await p.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1))throw Error('mobile overflow');
 await p.click('#brain-help');await p.waitForSelector('#help-search');await shot('mobile-help');if(await p.$eval('#modal',e=>e.scrollWidth>e.clientWidth+1))throw Error('mobile dialog overflow');await p.keyboard.press('Escape');await closed();
 if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync(dir+'/ui.json',JSON.stringify({status:'PASS',root,url,checks,errors},null,2));console.log('PASS '+root);
 }catch(e){fs.writeFileSync(dir+'/failure.txt',e.stack);const pages=await browser.pages();await pages[pages.length-1].screenshot({path:dir+'/failure.png',fullPage:true});throw e}finally{await browser.close();server.kill()}
})().catch(e=>{console.error(e);process.exitCode=1});
