'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{spawn,execFileSync}=require('child_process'),puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const fixture=JSON.parse(execFileSync('python3',[path.join(__dirname,'pilotage_fixture.py'),binary],{encoding:'utf8'}));
execFileSync('python3',['-c',`import sqlite3,json,sys
c=sqlite3.connect(sys.argv[1]+'/.swarm/state.db');b=json.loads(c.execute("select body from agents where id='archive-204'").fetchone()[0]);b['progress']={'detail':'python3 import hashlib source-snapshot-end.json stable diff','action':'Exécution d’une commande'};c.execute("update agents set body=? where id='archive-204'",(json.dumps(b),));c.commit()`,fixture.root]);
let browser;const server=spawn(binary,['--root',fixture.root,'web','127.0.0.1:0'],{stdio:['ignore','pipe','pipe']});
(async()=>{
 const url=await new Promise(resolve=>{let s='';server.stdout.on('data',d=>{s+=d;const m=s.match(/http:\/\/\S+\/session\/\S+/);if(m)resolve(m[0])})});
 browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width:1440,height:1100});await page.goto(url);await page.waitForSelector('#pilot-view');await page.select('#work',fixture.works['12']);await page.waitForFunction(w=>snapshot?.work.id===w,{},fixture.works['12']);
 // Explicit view fixture: no provider or business mutation. Stop SSE so simulated states stay stable.
 await page.evaluate(()=>{stream?.close();const a=snapshot.agents.find(x=>x.agent.id==='archive-204').agent;a.status='running';a.ended='';a.usage={};a.progress={detail:'python3 import hashlib source-snapshot-end.json stable diff',action:'Exécution d’une commande',last_result_at:new Date().toISOString(),pending_tools:0};snapshot.pilotage.health[a.id]={process_state:'running',process_label:'Agent démarré',activity_state:'recent',activity_label:'Résultat public récent'};Pilot.inspect('agent',a.id)});
 await page.waitForSelector('#pilot-current-activity');
 const visible=await page.$eval('#pilot-current-activity',e=>e.innerText);assert.match(visible,/empreintes des fichiers/);assert.match(visible,/prochaine activité/);assert.match(visible,/fournisseur n’a pas transmis/);assert.doesNotMatch(visible,/python3|hashlib|Résultat public récent/);assert.equal(await page.$eval('#pilot-activity-details',e=>e.open),false);
 for(const theme of ['etat','sombre']){await page.evaluate(t=>setTheme(t),theme);await page.screenshot({path:path.join(out,theme+'.png'),fullPage:true})}
 await page.click('#pilot-activity-details summary');assert.match(await page.$eval('#pilot-activity-details',e=>e.innerText),/hashlib/);await page.evaluate(()=>{Pilot.inspectorKey='';PilotInspector.render()});assert.equal(await page.$eval('#pilot-activity-details',e=>e.open),true);
 const states=await page.evaluate(()=>{const f=(a,h)=>PilotInspector.activityExplanation(a,h);return {pending:f({status:'running',progress:{pending_tools:1}},{process_state:'running'}),old:f({status:'running',progress:{}},{process_state:'running',activity_state:'old'}),done:f({status:'completed',progress:{}},{process_state:'completed'}),lost:f({status:'running',progress:{}},{process_state:'unknown/supervisor-lost'}),stop:f({status:'running',progress:{}},{stop_requested:true}),stopped:f({status:'interrupted',progress:{}},{stop_requested:true}),unconfirmed:f({status:'running',progress:{}},{process_state:'running/unconfirmed',activity_state:'old'})}});
 assert.match(states.pending.state,/attend la réponse/);assert.match(states.old.state,/Aucune activité récente/);assert.match(states.done.state,/terminée/);assert.match(states.lost.state,/ne peut pas confirmer/);assert.match(states.stop.state,/arrêt a été demandé/);assert.doesNotMatch(states.stopped.state,/confirmation est attendue/);assert.match(states.unconfirmed.state,/ne peut pas confirmer/);assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'ui.json'),JSON.stringify({status:'PASS',checks:['explication humaine de la comparaison des sources','réponse outil distincte du livrable','coût inconnu expliqué','commande repliée et dépliable','état du repli préservé au rafraîchissement','attente outil, silence ancien, fin, perte superviseur et arrêt distingués','deux thèmes rendus'],errors},null,2));console.log('PASS activity explanation');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server.kill()});
