'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{spawn,spawnSync}=require('child_process'),puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-planning-ui-'));
function run(cmd,args,opts={}){const r=spawnSync(cmd,args,{encoding:'utf8',...opts});if(r.status!==0)throw Error(r.stderr);return r.stdout}
function cli(args,data){const result=JSON.parse(run(binary,['--root',root,'--json',...args,...(data?['--input','-']:[])],{input:data?JSON.stringify(data):undefined}));return result.work||result}
cli(['init']);run('git',['init'],{cwd:root});fs.writeFileSync(path.join(root,'readme.txt'),'fixture');run('git',['add','readme.txt'],{cwd:root});run('git',['-c','user.name=Test','-c','user.email=test@local','commit','-m','base'],{cwd:root});fs.writeFileSync(path.join(root,'.swarm/providers.json'),JSON.stringify({schema_version:1,providers:{claude:{command:'/home/fpizzi/.config/nvm/versions/node/v22.23.2/bin/claude',args:['-p','--output-format','stream-json','--verbose'],env_allow:[]}}}));
let w=cli(['work','create'],{schema_version:1,event_id:'create-ui',expected_revision:0,title:'Équipe autonome — recette',objective:'Vérifier la lisibilité du pilotage',scope:'recette',criteria:['révision contrôlée'],next:'préparer'});
const server=spawn(binary,['--root',root,'web','127.0.0.1:0']);let logs='';server.stdout.on('data',b=>logs+=b);server.stderr.on('data',b=>logs+=b);let browser;
(async()=>{for(let i=0;i<100&&!logs.match(/http:\/\/\S+/);i++)await new Promise(r=>setTimeout(r,50));const url=logs.match(/http:\/\/\S+/)[0];browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width:1400,height:1100});await page.goto(url+'?work='+w.id);await page.waitForFunction(()=>typeof Planning!=='undefined'&&snapshot?.work.id);
assert.equal(await page.evaluate(()=>snapshot.mission.organization.ready),false);
for(const theme of ['etat','sombre']){await page.evaluate(t=>setTheme(t),theme);await page.screenshot({path:path.join(out,'organisation-absente-'+theme+'.png'),fullPage:true})}
await page.click('#mission-primary');await page.waitForSelector('#modal[open]');assert.match(await page.$eval('#modal',e=>e.textContent),/Organisation de la mission/);await page.keyboard.press('Escape');
await page.evaluate(()=>Planning.enable());await page.waitForSelector('#field-planning-provider');await page.select('#field-planning-provider','claude');await page.type('#field-planning-args-0','diff\n--exit-code');await page.type('#field-planning-why-0','Compare les fichiers à la révision enregistrée.');
for(const theme of ['etat','sombre']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.screenshot({path:path.join(out,'activation-'+theme+'.png'),fullPage:true})}
await page.click('#confirm');await page.waitForFunction(()=>!!snapshot?.work.planning).catch(async e=>{console.error(await page.$eval('#modal',e=>e.textContent));throw e});await page.waitForSelector('#field-provider');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.getElementById('modal').open);
assert.ok(await page.$('#planning-ownership'));assert.equal(await page.$eval('#mission-summary h3',e=>e.textContent),'Mission à poursuivre');
await page.evaluate(()=>Planning.resume('pause'));await page.click('#confirm');await page.waitForFunction(()=>snapshot.work.planning.paused);
await page.evaluate(()=>Planning.details());await page.waitForSelector('#modal[open]');assert.match(await page.$eval('#modal',e=>e.textContent),/Vérifier la lisibilité/);await page.keyboard.press('Escape');
for(const theme of ['etat','sombre']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);const missing=await page.evaluate(()=>{const css=[...document.styleSheets].flatMap(s=>[...s.cssRules].map(r=>r.cssText)).join(' '),style=getComputedStyle(document.documentElement);return [...new Set([...css.matchAll(/var\((--wattson-[\w-]+)/g)].map(m=>m[1]))].filter(t=>!style.getPropertyValue(t).trim())});assert.deepEqual(missing,[]);await page.screenshot({path:path.join(out,'ownership-'+theme+'.png'),fullPage:true})}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'PASS',checks:['activation web avec contrôles','même état depuis CLI','pause persistée','retours en modale','aucun faux terminé sur travail vide','deux thèmes rendus sans jeton absent','aucune erreur JavaScript']},null,2));console.log('PASS planning UI');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.kill('SIGTERM')});
