const fs=require('fs'),path=require('path'),{spawn,execFileSync}=require('child_process'),pup=require(process.env.PUPPETEER_MODULE||'puppeteer');const binary=path.resolve(process.argv[2]),dir=path.resolve(process.argv[3]);fs.mkdirSync(dir,{recursive:true});
(async()=>{const root=execFileSync('python3',['tools/swarm-companion/tests/web_fixture.py',binary],{encoding:'utf8'}).trim();execFileSync('python3',['-c',`import sqlite3,json,sys,hashlib
c=sqlite3.connect(sys.argv[1]+'/.swarm/state.db');id,b=c.execute('select id,body from works').fetchone();w=json.loads(b);w['planning_brief']={'task':'seed','text':'Deux missions séquentielles de recette, aucune livraison Wattson.','sha256':hashlib.sha256(b'brief').hexdigest(),'at':'2026-09-12'};c.execute('update works set body=? where id=?',(json.dumps(w),id));c.commit()`,root]);
const mission=(id,depends)=>({id,title:'Mission '+id,role:'worker',scope:'docs uniquement',deliverable:'docs/'+id+'-handoff.md',depends,criteria:['Preuve de recette '+id],proof:'Rapport et gate',entry:'Dépendances acceptées',validation:'Test de recette',delivery:'Gate fraîche et revue',stop:'Deux corrections puis OODA',max_attempts:2,max_tool_calls:5});const plan={version:1,objective:'Plan de recette structuré',assumptions:[],questions:[{question:'Périmètre limité à la recette ?',answer:''}],tasks:[mission('T2',['T1']),mission('T1',[])]};fs.writeFileSync(root+'/plan.json',JSON.stringify(plan));
fs.writeFileSync(root+'/provider.py',`#!/usr/bin/python3
import sys,re,time,json,hashlib
from pathlib import Path
p=sys.stdin.read();Path('last-prompt.txt').write_text(p);task=re.search(r'Tâche ([^:]+):',p).group(1)
print(json.dumps({'type':'system'}),flush=True);time.sleep(1)
if 'CADRE OBLIGATOIRE DU PLAN' in p: result=Path('plan.json').read_text()
else:
 local=task.split('-')[-1];report='docs/'+local+'-handoff.md';Path(report).write_text('Rapport de recette '+local+' : preuve synthétique du workflow, pas de résultat Wattson.')
 e={'method_version':'2','scope_id':task,'artifacts':{report:hashlib.sha256(Path(report).read_bytes()).hexdigest()},'domains':{'quality':1},'checks':[{'id':'ui','domain':'quality','mandatory':True,'gate':'delivery','penalty':100,'max_penalty':100,'severity':'major'}],'results':[{'id':'ui','status':'PASS','count':0,'evidence':[report]}]};e['checks']=[dict(id=k,domain='quality',mandatory=True,gate=g,penalty=25,max_penalty=25,severity='major') for k,g in [('plan-entry','entry'),('plan-validation','validation'),('plan-delivery','delivery'),('plan-criterion-1','validation')]];e['results']=[dict(id=c['id'],status='PASS',count=0,evidence=[report]) for c in e['checks']];Path('docs/'+local+'.json').write_text(json.dumps(e));result='Rapport produit'
print(json.dumps({'type':'result','result':result}),flush=True)
`);fs.chmodSync(root+'/provider.py',0o700);
const server=spawn(binary,['--root',root,'web']);let out='';server.stdout.on('data',d=>out+=d);while(!out.includes('/session/'))await new Promise(r=>setTimeout(r,100));const b=await pup.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});let p;const errors=[],checks=[];try{p=await b.newPage();p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width:1440,height:1100});await p.goto(out.match(/http:\/\/\S+/)[0]);await p.waitForSelector('#tasks-body tr');await p.waitForSelector('#mode');if(await p.evaluate(()=>document.body.dataset.mode)==='conduite'){await p.click('#mode');await p.waitForFunction(()=>document.body.dataset.mode==='expert')};await p.click('[data-view=brainstorm]');const click=async(text,scope='body')=>p.locator(scope+' button::-p-text('+text+')').click();const fill=async(sel,v)=>{if(await p.$eval(sel,e=>e.tagName)==='SELECT')await p.select(sel,v);else{await p.click(sel,{clickCount:3});await p.keyboard.press('Backspace');await p.type(sel,v)}};const closed=()=>p.waitForFunction(()=>!document.querySelector('#modal').open);
await click('Préparer le plan d’action avec l’IA');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’envoi à l’IA');if(!(await p.$eval('#preview',e=>e.textContent)).includes('UNIQUEMENT par un objet JSON'))throw Error('missing imposed response framework');await p.click('#confirm');await closed();await p.waitForSelector('#brain-messages article');await p.waitForFunction(()=>!document.querySelector('#brain-send').disabled);await click('Examiner le plan d’action');await p.waitForSelector('#field-plan-objective');await p.click('#confirm');await p.waitForSelector('#modal-error:not([hidden])');if(!(await p.$eval('#modal-error',e=>e.textContent)).includes('Décision non résolue'))throw Error('unanswered question allowed');await fill('#field-plan-question-0','Oui, recette isolée.');await fill('#field-mission-1-depends','T2');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#modal-error').textContent.includes('Cycle'));await fill('#field-mission-1-depends','');await fill('#field-mission-0-title','Mission dépendante relue');
for(const theme of ['etat','sombre']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);await p.screenshot({path:dir+'/'+theme+'-review.png'});}await p.setViewport({width:390,height:844});await p.screenshot({path:dir+'/mobile-review.png'});if(await p.$eval('#modal',e=>e.scrollWidth>e.clientWidth+1))throw Error('mobile modal overflow');await p.setViewport({width:1440,height:1100});await p.click('#confirm');await closed();await p.waitForSelector('#action-plans .plan-task-line');if(await p.$$eval('#action-plans .plan-task-line',e=>e.length)!==2)throw Error('not atomic two task plan');checks.push('imposed JSON prompt; unresolved question and cycle rejected; edited plan committed atomically');
const ids=await p.$$eval('#tasks-body tr[data-task]',rows=>rows.map(r=>r.dataset.task).filter(id=>id.startsWith('plan-')));const t1=ids.find(id=>id.endsWith('-T1')),t2=ids.find(id=>id.endsWith('-T2'));
// La liste des actions vient d'un appel réseau : choisir avant qu'elle soit
// peuplée laisse l'action conseillée en place, sans erreur visible.
async function action(id,name){await p.click('[data-task="'+id+'"] button');await p.waitForSelector('#field-action');await p.waitForFunction(x=>[...document.querySelectorAll('#field-action option')].some(o=>o.value===x),{},name);await p.select('#field-action',name);await p.waitForFunction(x=>document.querySelector('#field-action').value===x,{},name)}
// Dépendance non acceptée. Depuis S28 le départ n'est plus proposé du tout :
// l'oracle des actions le retire et porte le motif sur le bouton de la tâche,
// avant toute tentative.
const motifDep=await p.$eval('[data-task="'+t2+'"] button',e=>e.title);
if(!/dépendance/i.test(motifDep))throw new Error('motif de dépendance illisible : '+motifDep);
await p.click('[data-task="'+t2+'"] button');await p.waitForSelector('#modal[open] #field-action',{visible:true});
const offertesDep=await p.$$eval('#field-action option',es=>es.map(e=>e.value));
if(offertesDep.includes('start'))throw new Error('départ proposé malgré une dépendance non acceptée : '+offertesDep.join(', '));
await p.keyboard.press('Escape');checks.push('dependent worker launch refused before any attempt');
for(const id of [t1,t2]){await action(id,'start');await p.click('#confirm');await closed();await p.waitForFunction(id=>document.querySelector('[data-task="'+id+'"] .badge').textContent==='À vérifier'||document.querySelector('[data-task="'+id+'"] .badge').textContent==='Bloquée',{timeout:30000},id);await action(id,'submit');await fill('#field-path','docs/'+id.split('-').at(-1)+'-handoff.md');await p.click('#confirm');await closed();await action(id,'gate');await fill('#field-path','docs/'+id.split('-').at(-1)+'.json');await fill('#field-name','Recette du plan');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’enregistrement');await p.click('#confirm');await closed();await action(id,'accepted');await p.click('#confirm');await closed();}
checks.push('both missions launch → submit → gate → accept in dependency order');await p.reload();await p.waitForSelector('#action-plans .plan-task-line');if(await p.$$eval('#action-plans .badge',els=>els.filter(e=>e.textContent==='Acceptée').length)!==2)throw Error('accepted plan not persisted');for(const theme of ['etat','sombre']){if(await p.$eval('html',e=>e.dataset.theme)!==theme)await p.click('#theme');await p.screenshot({path:dir+'/'+theme+'-completed.png'});}checks.push('reloaded plan retains two accepted tasks');if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync(dir+'/ui.json',JSON.stringify({status:'PASS',root,checks,errors},null,2));console.log('Structured plan UI PASS');}catch(e){fs.writeFileSync(dir+'/failure.txt',e.stack);if(p)await p.screenshot({path:dir+'/failure.png'});throw e}finally{await b.close();server.kill()}})().catch(e=>{console.error(e);process.exitCode=1});
