'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {spawn,execFileSync}=require('node:child_process');const puppeteer=require(process.env.PUPPETEER_MODULE||'puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-prephase-ui-'));
const cli=(args,data)=>JSON.parse(execFileSync(binary,['--root',root,...args,...(data?['--input','-']:[])],{encoding:'utf8',input:data?JSON.stringify(data):undefined}));cli(['init']);
for(const p of ['.claude/skills/apex/SKILL.md','.claude/commands/ks-feature.md','.claude/commands/ks-plan.md','.claude/skills/audit-pdca/SKILL.md','tools/agent-workflows/CONTRACT.md']){const full=path.join(root,p);fs.mkdirSync(path.dirname(full),{recursive:true});fs.writeFileSync(full,'Préparation seulement.');}
const chord=async(page,key)=>{await page.keyboard.down('Control');await page.keyboard.press(key);await page.keyboard.up('Control')};
const server=spawn(binary,['--root',root,'web','127.0.0.1:0']);let browser;const errors=[],external=[],checks=[],themes=[];const checkTheme=require('./prephase_theme.cjs');let conflictResponses=0;
(async()=>{
 const url=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('server timeout')),15000);server.stdout.on('data',b=>{const m=String(b).match(/http:\/\/\S+\/session\/\S+/);if(m){clearTimeout(timer);resolve(m[0])}});server.on('error',reject)});
 browser=await puppeteer.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage();await page.setViewport({width:1440,height:1000});
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('status of 409 (Conflict)'))errors.push(m.text())});page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(new URL(url).origin))external.push(r.url())});
 page.on('response',r=>{if(r.status()===409)conflictResponses++});
 await page.goto(url);await page.goto(new URL('/prepare.html',url).href);await page.waitForFunction(()=>document.getElementById('connection').textContent==='Connecté au projet');
 await page.type('#new-title','Refonte du besoin Swarm');await page.type('#new-need','Une préparation partagée entre web et CLI.');await page.click('#create');await page.waitForSelector('#documents:not([hidden])');await page.waitForSelector('#monaco:not([hidden]) .monaco-editor');
 const id=new URL(page.url()).searchParams.get('id');assert.ok(id);checks.push('Création du besoin par formulaire, Monaco local chargé');
 await page.click('#editor-toggle');await page.waitForSelector('#plain-editor:not([hidden])');await page.click('#plain-editor');await page.keyboard.press('End');await page.type('#plain-editor','\nLe texte est conservé.');
 await page.waitForFunction(()=>document.getElementById('save-state').textContent.startsWith('Enregistré'));assert.match(cli(['prepare','show',id]).documents.besoin.text,/conservé/);checks.push('Sauvegarde automatique web relue depuis le CLI');
 await page.click('#advance');await page.waitForFunction(()=>document.querySelector('#tab-brief').getAttribute('aria-selected')==='true');await page.type('#plain-editor','Objectif : une interface claire, sans lancement implicite.');await page.waitForFunction(()=>document.getElementById('save-state').textContent.startsWith('Enregistré'));await page.click('#advance');await page.waitForFunction(()=>document.getElementById('next-action').textContent.startsWith('Brief adopté'));
 checks.push('Brief rédigé puis adopté par son bouton explicite');
 await page.click('#tab-besoin');await page.waitForFunction(()=>document.getElementById('advance').textContent==='Ouvrir le plan');assert.match(await page.$eval('#next-action',e=>e.textContent),/^Brief adopté/);assert.match(await page.$eval('#chat-plan-status',e=>e.textContent),/Choisissez une IA/);assert.equal(await page.$eval('#chat-plan',e=>e.disabled),true);
 for(const theme of ['etat','sombre']){if(await page.$eval('html',e=>e.dataset.theme)!==theme)await page.click('#theme');await page.screenshot({path:path.join(out,'next-step-'+theme+'.png'),fullPage:true});}
 await page.click('#advance');await page.waitForFunction(()=>document.getElementById('tab-plan').getAttribute('aria-selected')==='true');await page.click('#tab-brief');checks.push('Brief adopté : accès direct au plan depuis le besoin ; IA manquante explicitement signalée');

 const current=cli(['prepare','show',id]);cli(['prepare','save',id],{version:1,action:'save',preparation_id:id,event_id:crypto.randomUUID(),expected_revision:current.revision,document:'brief',text:'Version modifiée depuis le CLI.'});
 await page.type('#plain-editor',' Ma correction web.');await page.waitForSelector('#conflict:not([hidden])');assert.match(await page.$eval('#plain-editor',e=>e.value),/correction web/);assert.equal(await page.$eval('#conflict-server',e=>e.textContent),'Version modifiée depuis le CLI.');
 for(const theme of ['etat','sombre']){if(await page.$eval('html',e=>e.dataset.theme)!==theme)await page.click('#theme');await page.screenshot({path:path.join(out,'conflit-'+theme+'.png'),fullPage:true});}
 await page.click('#conflict-keep');await page.waitForSelector('#conflict[hidden]');await page.waitForFunction(()=>document.getElementById('save-state').textContent.startsWith('Enregistré'));assert.match(cli(['prepare','show',id]).documents.brief.text,/correction web/);checks.push('Conflit CLI/web : texte conservé, comparaison et choix explicite');
 await page.click('#history');await page.waitForSelector('#history-dialog[open] details');assert.ok(await page.$$eval('#history-content details',es=>es.length)>=3);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'history');
 await page.click('#editor-toggle');await page.waitForSelector('#monaco:not([hidden])');
 for(const theme of ['etat','sombre']){if(await page.$eval('html',e=>e.dataset.theme)!==theme)await page.click('#theme');themes.push(await checkTheme(page));await page.screenshot({path:path.join(out,'monaco-'+theme+'.png'),fullPage:true});await page.click('#help');await page.screenshot({path:path.join(out,'aide-'+theme+'.png'),fullPage:true});await page.keyboard.press('Escape');}
 checks.push('Monaco, conflit et aide rendus dans les deux thèmes ; Échap restitue le focus');
 await page.focus('#monaco textarea');await chord(page,'End');await page.keyboard.sendCharacter(' Édition Monaco vérifiée.');await page.waitForFunction(()=>document.querySelector('#monaco .view-lines').textContent.replace(/\u00a0/g,' ').includes('Monaco vérifiée'));await page.waitForFunction(()=>document.getElementById('save-state').textContent.startsWith('Enregistré'));assert.match(cli(['prepare','show',id]).documents.brief.text,/Monaco vérifiée/);
 await page.click('#advance');await page.waitForFunction(()=>document.getElementById('advance').textContent==='Ouvrir le plan');await page.click('#advance');await page.waitForFunction(()=>document.querySelector('#tab-plan').getAttribute('aria-selected')==='true');await page.click('#plan-template');await page.waitForFunction(()=>document.getElementById('save-state').textContent.startsWith('Enregistré'));
 const plan={version:1,objective:'Recette de préparation',assumptions:[],questions:[],tasks:[{id:'T1',title:'Rédiger la synthèse',role:'worker',scope:'docs',deliverable:'docs/synthese.md',criteria:['Synthèse relue'],depends:[],proof:'Rapport et revue',entry:'Brief adopté',validation:'Revue du rapport',delivery:'Preuves actuelles',stop:'Arrêt sur blocage',max_attempts:2,max_tool_calls:20}]};
 await page.focus('#monaco textarea');await chord(page,'A');await page.keyboard.sendCharacter(JSON.stringify(plan,null,2));await page.waitForFunction(()=>document.getElementById('save-state').textContent.startsWith('Enregistré'));await page.click('#advance');await page.waitForFunction(()=>document.getElementById('next-action').textContent.startsWith('Plan vérifié')||!document.getElementById('error').hidden);fs.writeFileSync(path.join(out,'plan-state.json'),JSON.stringify(cli(['prepare','show',id]),null,2));assert.equal(await page.$eval('#error',e=>e.hidden?'':e.textContent),'');assert.equal(cli(['prepare','show',id]).plan_ready,true);
 for(let i=0;i<20;i++){const tab=['besoin','brief','plan'][i%3];await page.click('#tab-'+tab);await page.waitForFunction(k=>document.getElementById('tab-'+k).getAttribute('aria-selected')==='true',{},tab);}
 assert.equal(await page.$eval('#advance',e=>e.textContent),'Créer les missions');
 assert.ok(await page.evaluate(async()=>(await import('/lib/monaco/editor.js')).editor.getModels().length)<=3);checks.push('Saisie Monaco réelle, modèle JSON complété, plan vérifié et modèles bornés après 20 changements');

 await page.reload();await page.waitForSelector('#monaco:not([hidden]) .monaco-editor');assert.equal(await page.$eval('#title',e=>e.textContent),'Refonte du besoin Swarm');checks.push('Reprise persistante après rechargement');
 await page.setViewport({width:390,height:844});await page.reload();await page.waitForSelector('#plain-editor:not([hidden])');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});checks.push('Petit écran : éditeur texte et absence de débordement horizontal');
 assert.equal(conflictResponses,1);assert.deepEqual(external,[]);assert.deepEqual(errors,[]);
 const fallback=await browser.newPage();await fallback.setViewport({width:1280,height:900});await fallback.setRequestInterception(true);fallback.on('request',r=>r.url().endsWith('/lib/monaco/editor.js')?r.abort():r.continue());await fallback.goto(new URL('/prepare.html?id='+id,url).href);await fallback.waitForFunction(()=>document.getElementById('editor-state').textContent.includes('indisponible'));await fallback.waitForSelector('#plain-editor:not([hidden])');await fallback.screenshot({path:path.join(out,'secours.png'),fullPage:true});await fallback.close();checks.push('Échec du chargement Monaco : éditeur texte disponible');
 const lost=await browser.newPage();await lost.setViewport({width:390,height:844});await lost.goto(new URL('/prepare.html?id='+id,url).href);await lost.waitForSelector('#documents:not([hidden])');await lost.waitForSelector('#plain-editor:not([hidden])');let drop=true;await lost.setRequestInterception(true);lost.on('request',async r=>{if(drop&&r.method()==='POST'&&r.url().endsWith('/preparations/command')&&JSON.parse(r.postData()).action==='save'){drop=false;const response=await fetch(r.url(),{method:'POST',headers:r.headers(),body:r.postData()});assert.equal(response.status,200);await r.abort();}else await r.continue();});
 const revisionBefore=cli(['prepare','show',id]).revision;await lost.focus('#plain-editor');await chord(lost,'End');await lost.keyboard.sendCharacter(' Réponse HTTP perdue.');await lost.waitForFunction(()=>document.getElementById('save-state').textContent.startsWith('Non enregistré'));await lost.click('#save');await lost.waitForFunction(()=>document.getElementById('save-state').textContent.startsWith('Enregistré'));assert.equal(cli(['prepare','show',id]).revision,revisionBefore+1);await lost.close();checks.push('Réponse HTTP perdue après commit : récupération du reçu sans double sauvegarde');


 const failed=await browser.newPage();await failed.setViewport({width:390,height:844});await failed.goto(new URL('/prepare.html?id='+id,url).href);await failed.waitForSelector('#plain-editor:not([hidden])');const confirmed=cli(['prepare','show',id]);const savedText=confirmed.documents.besoin.text;await failed.click('#tab-besoin');await failed.waitForFunction(t=>document.getElementById('plain-editor').value===t,{},savedText);await failed.setRequestInterception(true);failed.on('request',r=>r.method()==='POST'&&r.url().endsWith('/preparations/command')?r.abort():r.continue());await failed.focus('#plain-editor');await chord(failed,'End');await failed.keyboard.sendCharacter(' TEXTE NON ENREGISTRE.');await failed.waitForFunction(()=>document.getElementById('save-state').textContent.startsWith('Non enregistré'));const downloadDir=path.join(out,'recovery-download');fs.mkdirSync(downloadDir,{recursive:true});const devtools=await failed.createCDPSession();await devtools.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:downloadDir});await failed.click('#download');await new Promise((resolve,reject)=>{const until=Date.now()+5000;const poll=()=>{if(fs.existsSync(path.join(downloadDir,'besoin.md')))resolve();else if(Date.now()>until)reject(Error('download missing'));else setTimeout(poll,50)};poll()});assert.equal(fs.readFileSync(path.join(downloadDir,'besoin.md'),'utf8'),savedText+' TEXTE NON ENREGISTRE.');assert.equal(cli(['prepare','show',id]).revision,confirmed.revision);await failed.close();const recovered=await browser.newPage();await recovered.setViewport({width:390,height:844});await recovered.goto(new URL('/prepare.html?id='+id,url).href);await recovered.waitForSelector('#plain-editor:not([hidden])');await recovered.waitForFunction(t=>document.getElementById('plain-editor').value===t,{},savedText);await recovered.close();checks.push('Sauvegarde refusée : état non enregistré, téléchargement exact et reprise de la dernière révision confirmée');
 const performancePage=await browser.newPage();await performancePage.setViewport({width:1440,height:1000});await performancePage.evaluateOnNewDocument(()=>{Storage.prototype.getItem=function(){throw new Error('Storage refused in recipe')};Storage.prototype.setItem=function(){throw new Error('Storage refused in recipe')}});
 const perfPrep=cli(['prepare','create'],{version:1,action:'create',event_id:crypto.randomUUID(),expected_revision:0,title:'Recette 16 Ko',text:process.env.SWARM_LONG_LINE_TEST?'a'.repeat(15900):'Une ligne de specification.\n'.repeat(600).slice(0,15900)});
 await performancePage.goto(new URL('/prepare.html?id='+perfPrep.id,url).href);await performancePage.waitForSelector('#monaco:not([hidden]) .monaco-editor');let start=Date.now();await performancePage.reload();await performancePage.waitForSelector('#monaco:not([hidden]) .monaco-editor');const warmMs=Date.now()-start;assert.ok(warmMs<=2000,'warm editor '+warmMs+'ms');
 await performancePage.focus('#monaco textarea');await chord(performancePage,'End');await performancePage.evaluate(()=>{window.inputTimes=[];document.addEventListener('keydown',e=>{if(e.key==='b'){const start=performance.now();requestAnimationFrame(()=>window.inputTimes.push(performance.now()-start))}},true)});await performancePage.keyboard.type('b'.repeat(50),{delay:5});await performancePage.waitForFunction(()=>window.inputTimes.length===50);const latency=await performancePage.evaluate(()=>window.inputTimes.sort((a,b)=>a-b));const p95=latency[Math.ceil(latency.length*.95)-1];assert.ok(p95<=100,'input p95 '+p95+'ms');checks.push('Stockage navigateur refusé : Monaco reste utilisable ; document proche de 16 Ko, ouverture chaude et latence mesurées');
 let activity=0;await performancePage.setRequestInterception(true);performancePage.on('request',r=>{if(r.url().includes('/preparations/dialogue?')){activity++;r.respond({status:200,contentType:'application/json',body:JSON.stringify([{id:'activity-test',preparation_id:perfPrep.id,provider:'recette',status:'running',created_at:'2026-09-16T00:00:00Z',question:'Activité '+activity,source_revision:1}])})}else r.continue()});
 const before=await performancePage.evaluate(async()=>{const m=(await import('/lib/monaco/editor.js')).editor.getModels()[0];const a=document.activeElement;return {text:m.getValue(),focus:a.className,selection:[a.selectionStart,a.selectionEnd],scroll:document.getElementById('monaco').scrollTop}});
 await performancePage.waitForFunction(()=>document.querySelector('.chat-question')?.textContent==='Activité 30',{timeout:65000});
 const after=await performancePage.evaluate(async()=>{const m=(await import('/lib/monaco/editor.js')).editor.getModels()[0];const a=document.activeElement;return {text:m.getValue(),focus:a.className,selection:[a.selectionStart,a.selectionEnd],scroll:document.getElementById('monaco').scrollTop}});assert.deepEqual(after,before);checks.push('30 actualisations d’activité : texte, focus, sélection et scroll inchangés');
 fs.writeFileSync(path.join(out,'performance.json'),JSON.stringify({warm_editor_ms:warmMs,input_p95_ms:p95,samples:latency.length,document_bytes:15950,activity_updates:activity,machine:{platform:os.platform(),arch:os.arch(),cpus:os.cpus().length,cpu:os.cpus()[0].model},browser:await browser.version()},null,2));await performancePage.close();
 const agents=execFileSync('python3',['-c',"import sqlite3,sys;print(sqlite3.connect(sys.argv[1]).execute('SELECT count(*) FROM agents').fetchone()[0])",path.join(root,'.swarm/state.db')],{encoding:'utf8'}).trim();assert.equal(agents,'0');
 fs.writeFileSync(path.join(out,'ui.json'),JSON.stringify({status:'PASS',root,checks,errors,external,themes,provider_launched:false},null,2));console.log(JSON.stringify({status:'PASS',checks,root}));
})().catch(e=>{fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.stack,errors,external},null,2));console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server.kill()});
