'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {spawn,execFileSync}=require('node:child_process'),puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-portal-model-'));
function cli(args,input){return JSON.parse(execFileSync(binary,['--root',root,'--json',...args,...(input?['--input','-']:[])],{encoding:'utf8',input:input?JSON.stringify(input):undefined})||'null')}
cli(['init']);const model=cli(['prepare','template','client-portal']);assert.equal(model.work_model.increments.length,5);
const app=spawn(binary,['--root',root,'web','127.0.0.1:0']);let browser;const errors=[];
(async()=>{
 const session=await new Promise((resolve,reject)=>{let s='';const timer=setTimeout(()=>reject(Error('startup timeout')),20000);app.stdout.on('data',x=>{s+=x;const m=s.match(/http:\/\/\S+\/session\/\S+/);if(m){clearTimeout(timer);resolve(m[0])}});app.on('exit',c=>reject(Error('server '+c)))}),base=new URL(session).origin;
 browser=await puppeteer.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
 await p.goto(session,{waitUntil:'domcontentloaded'});
 for(const lang of ['fr','en'])for(const theme of ['etat','sombre']){
  await p.setViewport({width:1440,height:1100});await p.goto(base+'/prepare.html?start=template&template=client-portal&lang='+lang);await p.waitForFunction(()=>document.querySelector('#template-dialog').open&&!document.querySelector('#template-use').disabled);
  await p.evaluate(theme=>localStorage.setItem('swarm-theme',theme),theme);await p.reload();await p.waitForFunction(()=>document.querySelector('#template-dialog').open&&!document.querySelector('#template-use').disabled);
  for(const inc of model.work_model.increments){await p.select('#template-increment',inc.id);const rendered=await p.$$eval('#template-work-graph [data-task-id]',es=>es.map(e=>e.dataset.taskId));assert.deepEqual(rendered,inc.plans[lang].tasks.map(t=>t.id));if(lang==='en')assert.deepEqual(await p.$$eval('#template-work-inspector dt',es=>es.map(e=>e.textContent)),['Scope','Prerequisite','Deliverable','Criteria and checks','Evidence','Validation','Stop and recovery','Proposed limits']);for(const task of inc.plans[lang].tasks){await p.select('#template-work-task',task.id);assert.ok((await p.$eval('#template-work-inspector',e=>e.textContent)).includes(task.criteria[0]))}}
  await p.select('#template-increment','documents');await p.$eval('#template-work-graph',e=>e.scrollIntoView({block:'start'}));await p.screenshot({path:path.join(out,'graph-'+lang+'-'+theme+'.png')});
  await p.$eval('[data-task-id="BACK"]',e=>e.focus());await p.keyboard.press('Enter');assert.equal(await p.$eval('#template-work-task',e=>e.value),'BACK');await p.keyboard.press('Tab');await p.keyboard.down('Shift');await p.keyboard.press('Tab');await p.keyboard.up('Shift');
  await p.type('#template-answer-objective','Texte utilisateur conservé');await p.select('#template-increment','session');assert.equal(await p.$eval('#template-answer-objective',e=>e.value),'Texte utilisateur conservé');
  await p.select('#template-choice','dashboard');assert.equal(await p.$eval('#template-work-model',e=>e.hidden),true);await p.select('#template-choice','client-portal');assert.equal(await p.$eval('#template-increment',e=>e.value),'session');
  for(const width of [1024,760,390,320]){await p.setViewport({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(await p.$eval('#template-dialog',e=>e.getBoundingClientRect().right<=innerWidth))}
  await p.$eval('#template-work-model',e=>e.scrollIntoView({block:'start'}));await p.screenshot({path:path.join(out,'mobile-'+lang+'-'+theme+'.png')});
  await p.keyboard.press('Escape');await p.waitForFunction(()=>document.activeElement.id==='template-open');
 }
 await p.setViewport({width:1440,height:1100});await p.goto(base+'/prepare.html?start=template&template=client-portal&lang=fr');await p.waitForFunction(()=>!document.querySelector('#template-use').disabled);await p.select('#template-increment','documents');
 const answers=Object.fromEntries(model.questions.map(q=>[q.id,'Réponse du client '+q.id]));for(const [id,text] of Object.entries(answers))await p.type('#template-answer-'+id,text);
 const expected=cli(['prepare','template-check','client-portal'],{language:'fr',increment:'documents',answers});
 await p.click('#template-check');await p.waitForFunction(()=>!document.querySelector('#template-check').disabled);assert.equal(await p.$eval('#template-preview',e=>e.textContent),expected.need);
 const downloads=path.join(out,'downloads');fs.mkdirSync(downloads,{recursive:true});const cdp=await p.createCDPSession();await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});const file=path.join(downloads,'client-portal-documents.json');if(fs.existsSync(file))fs.unlinkSync(file);await p.click('#template-work-export');await p.waitForFunction(()=>!document.querySelector('#template-work-export').disabled);for(let tries=0;tries<100&&!fs.existsSync(file);tries++)await new Promise(r=>setTimeout(r,100));assert.deepEqual(JSON.parse(fs.readFileSync(file,'utf8')),expected.work_plan);
 await p.setRequestInterception(true);let fail=true;const intercept=r=>r.url().endsWith('/preparations/template-check')&&fail?r.respond({status:503,contentType:'application/json',body:'{"error":"fixture outage"}'}):r.continue();p.on('request',intercept);
 await p.click('#template-use');await p.waitForSelector('#template-error:not([hidden])');assert.equal(await p.$eval('#new-need',e=>e.value),'');assert.equal(await p.$eval('#template-answer-objective',e=>e.value),answers.objective);fail=false;
 await p.click('#template-use');await p.waitForSelector('#template-dialog:not([open])');p.off('request',intercept);await p.setRequestInterception(false);
 await p.setRequestInterception(true);let planSaveFault=true;const saveIntercept=r=>r.url().endsWith('/preparations/command')&&r.postData()&&JSON.parse(r.postData()).document==='plan'&&planSaveFault?r.respond({status:503,contentType:'application/json',body:'{"error":"plan save fixture outage"}'}):r.continue();p.on('request',saveIntercept);
 await p.click('#create');await p.waitForFunction(()=>document.querySelector('#documents').hidden===false&&document.querySelector('#tab-plan').getAttribute('aria-selected')==='true');
 const id=new URL(p.url()).searchParams.get('id');await p.waitForSelector('#error:not([hidden])');assert.equal(cli(['prepare','list']).preparations.length,1,'save failure created duplicate preparation');planSaveFault=false;await p.click('#save');await p.waitForFunction(()=>/Enregistré/.test(document.querySelector('#save-state').textContent));p.off('request',saveIntercept);await p.setRequestInterception(false);let saved=cli(['prepare','show',id]);assert.deepEqual(JSON.parse(saved.documents.plan.text),expected.work_plan);assert.equal(saved.plan_ready,false);assert.equal(saved.adopted_brief,undefined);
 // Public engine conversion test with fixture decisions, never a provider or an execution.
 function command(action,fields={}){saved=cli(['prepare',action,id,'--input','-'],{version:1,event_id:require('node:crypto').randomUUID(),action,preparation_id:id,expected_revision:saved.revision,...fields});return saved}
 command('save',{document:'brief',text:'Explicit isolated recipe; no live portal or external effects.'});command('adopt-brief',{sha256:saved.documents.brief.sha256});
 const rejected=spawnSyncResult(['prepare','validate-plan',id,'--input','-'],{version:1,event_id:require('node:crypto').randomUUID(),action:'validate-plan',preparation_id:id,expected_revision:saved.revision,sha256:saved.documents.plan.sha256});assert.notEqual(rejected.status,0,'open decisions accepted');
 const plan=JSON.parse(saved.documents.plan.text);for(const q of plan.questions)q.answer='Explicit test fixture decision; no real execution authorization';command('save',{document:'plan',text:JSON.stringify(plan)});command('validate-plan',{sha256:saved.documents.plan.sha256});const review=cli(['prepare','conversion',id]);command('create-missions',{sha256:saved.documents.plan.sha256,expected_work_revision:review.work_revision});
 const work=cli(['work','show',saved.work_id]).work;assert.equal(work.tasks.length,8);assert.ok(work.tasks.every(t=>t.launch_held));assert.deepEqual(work.plans.at(-1).spec.tasks,plan.tasks);assert.deepEqual(cli(['agent','list',saved.work_id]).agents,[]);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'PASS',root,preparation:id,work:saved.work_id,checks:['FR/EN two themes','all increments and task criteria','keyboard and escape','responsive','answers preserved','CLI/HTTP parity','error recovery','export matches API','plan inserted and saved','plan save failure recovers without duplicate','open decisions rejected','public conversion preserves plan/dependencies','launch held/no agents']},null,2));console.log('PASS portal work model public journey');
 function spawnSyncResult(args,input){return require('node:child_process').spawnSync(binary,['--root',root,'--json',...args],{encoding:'utf8',input:JSON.stringify(input)})}
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();app.kill('SIGTERM')});
