'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{spawn,execFileSync}=require('child_process'),puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-templates-'));
const cli=(args,input)=>JSON.parse(execFileSync(binary,['--root',root,...args,...(input?['--input','-']:[])],{encoding:'utf8',input:input?JSON.stringify(input):undefined}));
cli(['init']);
for(const file of ['.claude/skills/apex/SKILL.md','.claude/skills/debug/SKILL.md','tools/agent-workflows/CONTRACT.md']){const p=path.join(root,file);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,'Preparation only.');}
const app=spawn(binary,['--root',root,'web','127.0.0.1:0']);let browser;const errors=[];
(async()=>{
 const url=await new Promise((resolve,reject)=>{let text='';app.stdout.on('data',v=>{text+=v;const m=text.match(/http:\/\/\S+\/session\/\S+/);if(m)resolve(m[0])});app.on('exit',c=>reject(Error('server exited '+c)))});
 browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});
 for(const lang of ['fr','en'])for(const theme of ['etat','sombre']){
 const p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width:1400,height:1000});await p.goto(url);
 await p.goto(new URL('/prepare.html?lang='+lang,url).href);await p.waitForFunction(()=>document.getElementById('connection').textContent.match(/Connecté au projet|Connected to project/));
 if(await p.$eval('html',e=>e.dataset.theme)!==theme)await p.click('#theme');
 await p.click('#template-open');await p.waitForFunction(()=>!document.getElementById('template-use').disabled);
 assert.equal(await p.$$eval('#template-choice option',es=>es.length),4);assert.doesNotMatch(await p.$eval('#template-dialog',e=>e.textContent),/\bKS\b|ks-|\bAPEX\b|\bPDCA\b/);
 await p.select('#template-choice','correction');assert.match(await p.$eval('#template-method',e=>e.textContent),/Diagnostic|Diagnosis/);
 assert.match(await p.$eval('#template-preview',e=>e.textContent),lang==='fr'?/Défaut observé/:/Observed defect/);
 await p.screenshot({path:path.join(out,`templates-${lang}-${theme}.png`)});
 const tokens=await p.$eval('#template-dialog',el=>{const s=getComputedStyle(el);return {background:s.backgroundColor,color:s.color,missing:['--wattson-carte','--wattson-texte','--wattson-champ'].filter(v=>!s.getPropertyValue(v).trim())}});assert.deepEqual(tokens.missing,[]);assert.notEqual(tokens.color,tokens.background);
 await p.keyboard.press('Escape');assert.equal(await p.$eval('#template-open',e=>e===document.activeElement),true);
 await p.click('#template-open');await p.waitForFunction(()=>!document.getElementById('template-use').disabled);await p.select('#template-choice','correction');await p.click('#template-use');await p.waitForSelector('#template-dialog:not([open])');
 const need=await p.$eval('#new-need',e=>e.value);assert.match(need,/correction v1/);
 await p.click('#template-open');await p.waitForFunction(()=>!document.getElementById('template-use').disabled);await p.select('#template-choice','product');await p.click('#template-use');await p.waitForSelector('#template-error:not([hidden])');assert.equal(await p.$eval('#new-need',e=>e.value),need);assert.equal(await p.$eval('#template-dialog',e=>e.open),true);
 await p.keyboard.press('Escape');await p.click('#create');await p.waitForSelector('#documents:not([hidden])');const id=new URL(p.url()).searchParams.get('id');const saved=cli(['prepare','show',id]);assert.equal(saved.documents.besoin.text,need);assert.equal(saved.method,'debug');assert.equal(await p.$eval('#method',e=>e.value),'debug');await p.close();
 }
 for(const lang of ['fr','en'])for(const theme of ['etat','sombre']){
 const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width:1400,height:1000});await page.goto(url);await page.goto(new URL('/prepare.html?lang='+lang,url).href);await page.waitForFunction(()=>document.getElementById('connection').textContent.match(/Connecté au projet|Connected to project/));if(await page.$eval('html',e=>e.dataset.theme)!==theme)await page.click('#theme');await page.click('#template-open');await page.waitForFunction(()=>!document.getElementById('template-use').disabled);
 assert.equal(await page.$$eval('#template-questions textarea',es=>es.length),8);assert.equal(await page.$$eval('#template-team article',es=>es.length),3);assert.equal(await page.$$eval('#template-team .template-role-method',es=>es.length),3);assert.match(await page.$eval('#template-team [data-role=planner] .template-role-method',e=>e.textContent),/analyse|analysis|Analyse|Analysis/);assert.match(await page.$eval('#template-team [data-role=reviewer] .template-role-method',e=>e.textContent),/Revue indépendante|Independent review/);assert.equal(await page.$$eval('#template-missing li',es=>es.length),8);
 await page.click('#template-missing button');assert.equal(await page.evaluate(()=>document.activeElement.id),'template-answer-objective');await page.type('#template-answer-objective','A bounded improvement');await page.click('#template-check');await page.waitForFunction(()=>!document.getElementById('template-check').disabled);assert.equal(await page.$$eval('#template-missing li',es=>es.length),7);assert.match(await page.$eval('#template-preview',e=>e.textContent),/A bounded improvement/);
 const answers={objective:'A bounded improvement'};for(const id of ['audience','scope','exclusions','constraints','acceptance','verification','recovery']){answers[id]='Answer for '+id;await page.type('#template-answer-'+id,answers[id])}
 await page.click('#template-check');await page.waitForFunction(()=>!document.getElementById('template-check').disabled);assert.equal(await page.$$eval('#template-missing li',es=>es.length),0);const checked=cli(['prepare','template-check','application'],{language:lang,answers});assert.equal(checked.need_complete,true);assert.equal(checked.launch_authorized,false);assert.equal(await page.$eval('#template-preview',e=>e.textContent),checked.need);
 await page.screenshot({path:path.join(out,`guided-${lang}-${theme}.png`)});await page.$eval('#template-team',el=>el.scrollIntoView());await page.screenshot({path:path.join(out,`team-${lang}-${theme}.png`)});
 await page.click('#template-use');await page.waitForSelector('#template-dialog:not([open])');assert.equal(await page.$eval('#new-need',e=>e.value),checked.need);assert.match(await page.$eval('#template-draft-status',e=>e.textContent),lang==='fr'?/Besoin renseigné/:/Requirements filled in/);await page.click('#create');await page.waitForSelector('#documents:not([hidden])');assert.equal(cli(['prepare','show',new URL(page.url()).searchParams.get('id')]).documents.besoin.text,checked.need);await page.close();
 }
 const failure=await browser.newPage();await failure.goto(url);await failure.goto(new URL('/prepare.html',url).href);await failure.waitForFunction(()=>document.getElementById('connection').textContent.match(/Connecté au projet|Connected to project/));await failure.click('#template-open');await failure.waitForFunction(()=>!document.getElementById('template-use').disabled);await failure.type('#template-answer-objective','Preserve this answer');await failure.setRequestInterception(true);failure.on('request',r=>r.url().includes('/template-check')?r.respond({status:503,contentType:'application/json',body:JSON.stringify({error:'Fixture unavailable'})}):r.continue());await failure.click('#template-use');await failure.waitForSelector('#template-error:not([hidden])');assert.equal(await failure.$eval('#new-need',e=>e.value),'');assert.equal(await failure.$eval('#template-answer-objective',e=>e.value),'Preserve this answer');await failure.keyboard.press('Escape');assert.equal(await failure.evaluate(()=>document.activeElement.id),'template-open');await failure.close();
 const pending=await browser.newPage();await pending.goto(url);await pending.goto(new URL('/prepare.html',url).href);await pending.waitForFunction(()=>document.getElementById('connection').textContent.match(/Connecté au projet|Connected to project/));await pending.click('#template-open');await pending.waitForFunction(()=>!document.getElementById('template-use').disabled);await pending.setRequestInterception(true);let held;const intercepted=new Promise(resolve=>pending.on('request',r=>{if(r.url().includes('/template-check')){held=r;resolve()}else r.continue()}));await pending.click('#template-use');await intercepted;await pending.keyboard.press('Escape');const response=cli(['prepare','template-check','application'],{language:'fr',answers:{}});await held.respond({status:200,contentType:'application/json',body:JSON.stringify(response)});await pending.waitForNetworkIdle();assert.equal(await pending.$eval('#new-need',e=>e.value),'');assert.equal(await pending.evaluate(()=>document.activeElement.id),'template-open');await pending.close();
 for(const theme of ['etat','sombre']){
 const mobile=await browser.newPage();await mobile.setViewport({width:390,height:844});await mobile.goto(url);await mobile.goto(new URL('/prepare.html?lang=fr',url).href);await mobile.waitForFunction(()=>document.getElementById('connection').textContent==='Connecté au projet');if(await mobile.$eval('html',e=>e.dataset.theme)!==theme)await mobile.click('#theme');await mobile.click('#template-open');await mobile.waitForFunction(()=>!document.getElementById('template-use').disabled);const bounds=await mobile.$eval('#template-dialog',el=>{const b=el.getBoundingClientRect();return {left:b.left,right:b.right,width:innerWidth}});assert.ok(bounds.left>=0&&bounds.right<=bounds.width,JSON.stringify(bounds));const closeBounds=await mobile.$eval('#template-dialog [data-close]',el=>{const b=el.getBoundingClientRect();return {top:b.top,bottom:b.bottom,height:innerHeight}});assert.ok(closeBounds.top>=0&&closeBounds.bottom<=closeBounds.height,JSON.stringify(closeBounds));await mobile.screenshot({path:path.join(out,`templates-mobile-${theme}.png`)});await mobile.keyboard.press('Escape');assert.equal(await mobile.$eval('#template-open',e=>e===document.activeElement),true);await mobile.close();
 }
 for(const file of ['ks-feature.md','ks-plan.md']){const p=path.join(root,'.claude/commands',file);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,'Preparation only.');}
 const p=await browser.newPage();await p.goto(url);await p.goto(new URL('/prepare.html?lang=en',url).href);await p.waitForFunction(()=>document.getElementById('connection').textContent==='Connected to project');await p.click('#template-open');await p.waitForFunction(()=>!document.getElementById('template-use').disabled);assert.match(await p.$eval('#template-method',e=>e.textContent),/Analysis and planning available/);await p.click('#template-use');await p.waitForSelector('#template-dialog:not([open])');await p.click('#create');await p.waitForSelector('#documents:not([hidden])');assert.equal(cli(['prepare','show',new URL(p.url()).searchParams.get('id')]).method,'apex');
 const debugPath=path.join(root,'.claude/skills/debug/SKILL.md');const debugSource=fs.readFileSync(debugPath);fs.unlinkSync(debugPath);
 const unavailable=await browser.newPage();unavailable.on('pageerror',e=>errors.push(e.message));await unavailable.goto(url);await unavailable.goto(new URL('/prepare.html?lang=en',url).href);await unavailable.waitForFunction(()=>document.getElementById('connection').textContent==='Connected to project');await unavailable.click('#template-open');await unavailable.waitForFunction(()=>!document.getElementById('template-use').disabled);await unavailable.select('#template-choice','correction');assert.match(await unavailable.$eval('#template-method',e=>e.textContent),/diagnosis method is unavailable/);await unavailable.click('#template-use');await unavailable.waitForSelector('#template-dialog:not([open])');await unavailable.click('#create');await unavailable.waitForSelector('#documents:not([hidden])');assert.equal(cli(['prepare','show',new URL(unavailable.url()).searchParams.get('id')]).method,'debug');assert.equal(await unavailable.$eval('#method-apply',e=>e.disabled),true);await unavailable.close();fs.writeFileSync(debugPath,debugSource);
 const agents=execFileSync('python3',['-c',"import sqlite3,sys;print(sqlite3.connect(sys.argv[1]).execute('select count(*) from agents').fetchone()[0])",path.join(root,'.swarm/state.db')],{encoding:'utf8'}).trim();assert.equal(agents,'0');assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'PASS',languages:['fr','en'],themes:['etat','sombre'],draft_preserved:true,cli_readback:true,analysis_available:true,debug_persisted:true,missing_debug_preserves_draft:true,guided_checks:true,cli_projection_equal:true,failed_check_preserves_answers:true,closed_dialog_ignores_late_response:true,agents:0,errors},null,2));console.log('PASS template selection, preservation, methods, persistence and no launches');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();app.kill()});
