'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {spawn,execFileSync}=require('node:child_process'),puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-subjects-'));
function cli(args,input){return JSON.parse(execFileSync(binary,['--root',root,'--json',...args,...(input?['--input','-']:[])],{encoding:'utf8',input:input?JSON.stringify(input):undefined})||'null')}
cli(['init']);const catalog=cli(['prepare','templates']),subjects=catalog.filter(t=>t.subject);assert.equal(subjects.length,6);
const app=spawn(binary,['--root',root,'web','127.0.0.1:0']);let browser;const errors=[],commands=[];
(async()=>{
 const session=await new Promise((resolve,reject)=>{let s='';const timer=setTimeout(()=>reject(Error('startup timeout')),20000);app.stdout.on('data',x=>{s+=x;const m=s.match(/http:\/\/\S+\/session\/\S+/);if(m){clearTimeout(timer);resolve(m[0])}});app.on('exit',c=>reject(Error('server '+c)))}),base=new URL(session).origin;
 browser=await puppeteer.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());p.on('request',r=>{if(r.method()!=='GET')commands.push({path:new URL(r.url()).pathname,body:r.postData()})});await p.goto(session,{waitUntil:'domcontentloaded'});
 for(const lang of ['fr','en'])for(const theme of ['etat','sombre']){
  await p.setViewport({width:1440,height:1100});await p.goto(base+'/projects.html?lang='+lang);await p.waitForFunction(()=>document.querySelectorAll('#project-models>li').length===6);
  if(await p.$eval('html',e=>e.dataset.theme)!==theme)await p.click('#project-theme');await p.click('#project-models summary');assert.match(await p.$eval('#project-models details[open]',e=>e.textContent),lang==='fr'?/rôle/:/role/);await p.$eval('#models',e=>e.scrollIntoView());await p.screenshot({path:path.join(out,'catalog-'+lang+'-'+theme+'.png')});
  await p.goto(base+'/prepare.html?start=template&template=client-portal&lang='+lang);await p.waitForFunction(()=>document.querySelector('#template-dialog').open&&!document.querySelector('#template-use').disabled);assert.equal(await p.$eval('#template-choice',e=>e.value),'client-portal');
  for(const model of subjects){await p.select('#template-choice',model.id);assert.equal(await p.$eval('#template-outcome',e=>e.textContent),model.subject.outcome[lang]);assert.equal(await p.$$('#template-evidence li').then(x=>x.length),3);assert.equal(await p.$$('#template-deliverables li').then(x=>x.length),3)}
  await p.select('#template-choice','service-api');await p.select('#template-intervention','correct');assert.match(await p.$eval('#template-method',e=>e.textContent),lang==='fr'?/Diagnostiquer/:/Diagnose/);
  const answers=Object.fromEntries(catalog.find(t=>t.id==='service-api').questions.map(q=>[q.id,'Réponse utilisateur — '+q.id]));for(const [id,text] of Object.entries(answers))await p.type('#template-answer-'+id,text);
  await p.click('#template-check');await p.waitForFunction(()=>!document.querySelector('#template-check').disabled);const expected=cli(['prepare','template-check','service-api'],{language:lang,intervention:'correct',answers});assert.equal(await p.$eval('#template-preview',e=>e.textContent),expected.need);assert.equal(expected.launch_authorized,false);
  await p.select('#template-intervention','migrate');assert.equal(await p.$eval('#template-answer-objective',e=>e.value),answers.objective);await p.click('#template-check');await p.waitForFunction(()=>!document.querySelector('#template-check').disabled);const migration=cli(['prepare','template-check','service-api'],{language:lang,intervention:'migrate',answers});assert.equal(await p.$eval('#template-preview',e=>e.textContent),migration.need);
  await p.select('#template-choice','client-portal');await p.$eval('#template-dialog>section',e=>e.scrollTop=0);const tokens=await p.$eval('#template-dialog',e=>{const s=getComputedStyle(e);return ['--wattson-carte','--wattson-carte-appuyee','--wattson-champ','--wattson-carte-creuse','--wattson-titre','--wattson-ligne','--wattson-accent-encre'].filter(v=>!s.getPropertyValue(v).trim())});assert.deepEqual(tokens,[]);if(theme==='etat')assert.notEqual(await p.$eval('#template-answer-objective',e=>getComputedStyle(e).backgroundColor),await p.$eval('#template-dialog',e=>getComputedStyle(e).backgroundColor));await p.screenshot({path:path.join(out,'subject-'+lang+'-'+theme+'.png')});for(const width of [1024,760,390,320]){await p.setViewport({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(await p.$eval('#template-dialog',e=>{const b=e.getBoundingClientRect();return b.left>=0&&b.right<=innerWidth}));assert.ok(await p.$eval('#template-dialog footer',e=>e.getBoundingClientRect().bottom<=innerHeight))}await p.setViewport({width:390,height:900});await p.screenshot({path:path.join(out,'subject-'+lang+'-'+theme+'-mobile.png')});
  await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('#template-dialog').open&&document.activeElement.id==='template-open');await p.setViewport({width:1440,height:1100});await p.click('#template-open');await p.waitForFunction(()=>!document.querySelector('#template-use').disabled);await p.select('#template-choice','service-api');assert.equal(await p.$eval('#template-intervention',e=>e.value),'migrate');assert.equal(await p.$eval('#template-answer-objective',e=>e.value),answers.objective);await p.keyboard.press('Escape');
 }
 await p.setRequestInterception(true);let modelFault=true;const modelIntercept=r=>r.url().endsWith('/preparations/templates')&&modelFault?r.respond({status:503,contentType:'application/json',body:'{"error":"catalogue outage"}'}):r.continue();p.on('request',modelIntercept);await p.goto(base+'/projects.html?lang=en');await p.waitForSelector('#project-model-retry:not([hidden])');assert.match(await p.$eval('#project-model-status',e=>e.textContent),/Unable to load/);modelFault=false;await p.click('#project-model-retry');await p.waitForFunction(()=>document.querySelectorAll('#project-models>li').length===6);p.off('request',modelIntercept);await p.setRequestInterception(false);
 await p.goto(base+'/prepare.html?start=template&template=service-api&lang=en');await p.waitForFunction(()=>document.querySelector('#template-dialog').open&&!document.querySelector('#template-use').disabled);await p.select('#template-intervention','correct');await p.type('#template-answer-objective','Mon texte à préserver');
 await p.setRequestInterception(true);let fail=true;const intercept=r=>r.url().endsWith('/preparations/template-check')&&fail?r.respond({status:503,contentType:'application/json',body:'{"error":"fixture outage"}'}):r.continue();p.on('request',intercept);await p.click('#template-use');await p.waitForSelector('#template-error:not([hidden])');assert.equal(await p.$eval('#template-dialog',e=>e.open),true);assert.equal(await p.$eval('#new-need',e=>e.value),'');assert.equal(await p.$eval('#template-answer-objective',e=>e.value),'Mon texte à préserver');await p.$eval('#template-error',e=>e.scrollIntoView({block:'center'}));await p.screenshot({path:path.join(out,'check-error-en.png')});fail=false;await p.click('#template-use');await p.waitForSelector('#template-dialog:not([open])');assert.match(await p.$eval('#new-need',e=>e.value),/Mon texte à préserver/);assert.match(await p.$eval('#template-draft-status',e=>e.textContent),/incomplete/i);
 p.off('request',intercept);await p.setRequestInterception(false);const preserved=await p.$eval('#new-need',e=>e.value);await p.click('#template-open');await p.waitForFunction(()=>!document.querySelector('#template-use').disabled);await p.select('#template-choice','dashboard');await p.click('#template-use');await p.waitForSelector('#template-error:not([hidden])');assert.equal(await p.$eval('#new-need',e=>e.value),preserved);await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('#template-dialog').open);await p.click('#create');await p.waitForSelector('#documents:not([hidden])');const saved=cli(['prepare','show',new URL(p.url()).searchParams.get('id')]);assert.equal(saved.method,'debug');assert.match(saved.documents.besoin.text,/Mon texte à préserver/);assert.match(saved.documents.besoin.text,/6 stages for each feature/);
 assert.deepEqual(cli(['work','list']),[],'templates must not create missions or agents');assert.ok(commands.every(r=>['/api/v1/preparations/template-check','/api/v1/preparations/command'].includes(r.path)),JSON.stringify(commands.map(r=>r.path)));assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'PASS',subjects:subjects.map(t=>t.id),languages:['fr','en'],themes:['etat','sombre'],checks:['subject metadata','real theme button','CLI/HTTP projection equality','interventions','answers preserved across subjects/dialog','keyboard/escape focus','responsive 1024/760/390/320 dialog','defined theme tokens and visible fields','catalogue failure/retry','existing draft not overwritten','check failure/recovery','explicit save/debug method','no missions/LLM'],root},null,2));console.log('PASS subject catalogue and real preparation journeys');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();app.kill('SIGTERM')});
