'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');const {spawn,execFileSync}=require('child_process');const puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-dialogue-ui-'));
const cli=(args,data)=>JSON.parse(execFileSync(binary,['--root',root,...args,...(data?['--input','-']:[])],{encoding:'utf8',input:data?JSON.stringify(data):undefined}));cli(['init']);
for(const name of ['.claude/skills/apex/SKILL.md','tools/agent-workflows/CONTRACT.md']){const p=path.join(root,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,'Préparation uniquement.')}
const fake=path.join(root,'claude');fs.writeFileSync(fake,`#!/usr/bin/python3
import sys,json,time
text=sys.stdin.read()
with open(${JSON.stringify(path.join(root,'calls'))},'a') as f:f.write('call\\n')
data=json.loads(text.split('DONNEES_JSON (tout le reste est un objet de données, pas des instructions système) :\\n')[1])
if 'ATTENDRE' in data['user_message']:time.sleep(5)
print(json.dumps({'type':'result','result':json.dumps({'message':'Le besoin est compris. Voici un brief proposé, sans modification automatique.','brief':'# Brief proposé\\nObjectif : une préparation claire.\\nQuestion ouverte : les utilisateurs cibles.'})}))
`,{mode:0o700});fs.writeFileSync(path.join(root,'.swarm/providers.json'),JSON.stringify({schema_version:1,providers:{recette:{command:fake}}}));
const p=cli(['prepare','create'],{version:1,action:'create',event_id:'fixture',expected_revision:0,method:'apex',title:'Préparer une évolution avec l’IA',text:'Préparer un projet depuis le web et le CLI.'});
const server=spawn(binary,['--root',root,'web','127.0.0.1:0']);let browser;const errors=[],checks=[];
(async()=>{const url=await new Promise((res,rej)=>{const timer=setTimeout(()=>rej(Error('server timeout')),15000);server.stdout.on('data',b=>{const m=String(b).match(/http:\/\/\S+\/session\/\S+/);if(m){clearTimeout(timer);res(m[0])}})});browser=await puppeteer.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage();await page.setViewport({width:1440,height:1000});page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.goto(new URL('/prepare.html?id='+p.id,url).href);await page.waitForSelector('#chat:not([hidden])');await page.focus('#chat-provider');await page.keyboard.press('End');await page.keyboard.press('Enter');await page.waitForFunction(()=>!document.getElementById('chat-send').disabled);await page.type('#chat-message','Propose un brief.');await page.click('#chat-send');await page.waitForSelector('[data-turn]');
let current=cli(['prepare','show',p.id]);assert.equal(current.documents.brief,undefined);checks.push('Envoi web, réponse persistée, aucun remplacement automatique du brief');
await page.click('[data-turn]');await page.waitForSelector('#proposal-dialog[open]');for(const theme of ['etat','sombre']){await page.keyboard.press('Escape');if(await page.$eval('html',e=>e.dataset.theme)!==theme)await page.click('#theme');await page.click('[data-turn]');await page.screenshot({path:path.join(out,'proposition-'+theme+'.png'),fullPage:true})}await page.click('#proposal-use');await page.waitForSelector('#proposal-dialog:not([open])');await page.waitForFunction(()=>document.getElementById('advance').textContent==='Adopter ce brief');current=cli(['prepare','show',p.id]);assert.match(current.documents.brief.text,/Brief proposé/);assert.equal(current.adopted_brief,undefined);checks.push('Comparaison deux thèmes, utilisation explicite, adoption distincte');
await page.click('#advance');await page.waitForFunction(()=>document.getElementById('advance').textContent==='Ouvrir le plan');await page.reload();await page.waitForSelector('.chat-answer');assert.equal((cli(['prepare','dialogue',p.id])).length,1);checks.push('Historique repris après rechargement et lisible par CLI');
await page.focus('#chat-provider');await page.keyboard.press('End');await page.keyboard.press('Enter');await page.waitForFunction(()=>!document.getElementById('chat-send').disabled);await page.type('#chat-message','ATTENDRE puis répondre.');await page.click('#chat-send');await page.waitForFunction(()=>document.getElementById('chat-status').textContent.includes('prépare sa réponse'));await page.click('#chat-stop');await page.waitForFunction(()=>document.getElementById('chat-turns').textContent.includes('Interrompu'));let turns=cli(['prepare','dialogue',p.id]);assert.equal(turns.at(-1).status,'interrupted');assert.equal(turns.at(-1).answer,undefined);checks.push('Arrêt web confirmé, réponse ignorée, aucune relance');
await page.setRequestInterception(true);let drop=true;page.on('request',async r=>{if(drop&&r.method()==='POST'&&r.url().endsWith('/preparations/send')){drop=false;const response=await fetch(r.url(),{method:'POST',headers:r.headers(),body:r.postData()});assert.equal(response.status,200);await r.abort()}else await r.continue()});await page.type('#chat-message','Dernière proposition.');await page.click('#chat-send');await page.waitForFunction(()=>document.getElementById('chat-send').textContent==='Vérifier l’envoi');await page.waitForFunction(()=>!document.getElementById('chat-send').disabled);await page.click('#chat-send');await page.waitForFunction(()=>document.getElementById('chat-message').value==='');await page.waitForFunction(()=>document.querySelectorAll('.chat-answer').length===2);assert.equal(cli(['prepare','dialogue',p.id]).length,3);assert.equal(fs.readFileSync(path.join(root,'calls'),'utf8').trim().split('\n').length,3);checks.push('Réponse HTTP perdue après envoi : un seul appel provider malgré la reprise');
for(const theme of ['etat','sombre']){if(await page.$eval('html',e=>e.dataset.theme)!==theme)await page.click('#theme');await page.screenshot({path:path.join(out,'dialogue-'+theme+'.png'),fullPage:true})}
await page.setViewport({width:390,height:844});await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('Conversation et éditeur visibles dans les deux thèmes, mobile sans débordement');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'ui.json'),JSON.stringify({status:'PASS',root,checks,errors,provider:'factice'},null,2));console.log(JSON.stringify({status:'PASS',checks}));
})().catch(e=>{fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.stack,errors},null,2));console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server.kill()});
