'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{spawn,execFileSync}=require('child_process'),puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]),root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-profile-select-ui-'));fs.mkdirSync(out,{recursive:true});let app,browser;
const cli=(args,input)=>JSON.parse(execFileSync(binary,['--root',root,'--json',...args,...(input?['--input','-']:[])],{input:input?JSON.stringify(input):undefined,encoding:'utf8'}));
(async()=>{try{
 cli(['init']);fs.writeFileSync(path.join(root,'AGENTS.md'),'SHARED_PRIVATE_INSTRUCTION');fs.mkdirSync(path.join(root,'.claude'),{recursive:true});fs.writeFileSync(path.join(root,'.claude/CLAUDE.md'),'CLAUDE_PRIVATE_INSTRUCTION');fs.writeFileSync(path.join(root,'.claude/settings.local.json'),'{"test":"PRIVATE_SETTINGS_CONTENT"}');
 let w=cli(['work','create'],{schema_version:1,event_id:'work',expected_revision:0,title:'Profile selection acceptance',objective:'Verify recorded project profiles',scope:'Isolated fake-provider fixture',criteria:['Profile shown correctly'],next:'Select'}).work;
 w=cli(['task','add',w.id],{schema_version:1,event_id:'task1',expected_revision:w.revision,id:'t1',title:'Recorded profile',deliverable:'report.md',criteria:['Recorded context'],next:'Fake provider output'}).work;
 w=cli(['task','add',w.id],{schema_version:1,event_id:'task2',expected_revision:w.revision,id:'t2',title:'Dependent task',deliverable:'report.md',criteria:['Keep dependency arrow'],depends:['t1'],next:'Wait'}).work;
 const command=path.join(root,'claude');fs.writeFileSync(command,'#!/bin/sh\ncat >/dev/null\nprintf \'%s\\n\' \'{"type":"result","result":"Fake provider finished"}\'\n',{mode:0o700});fs.writeFileSync(path.join(root,'.swarm/providers.json'),JSON.stringify({schema_version:1,providers:{claude:{command,args:['-p','--output-format','stream-json','--verbose']}}}));
 app=spawn(binary,['--root',root,'web','127.0.0.1:0']);const url=await new Promise((resolve,reject)=>{let text='';app.stdout.on('data',x=>{text+=x;const m=text.match(/http:\/\/[^\s]+/);if(m)resolve(m[0])});app.on('exit',c=>reject(Error('server '+c)))});
 browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});const errors=[],checks=[];let launched=null;
 for(const lang of ['fr','en']){
 const p=await browser.newPage();p.on('pageerror',e=>{errors.push(e.message);console.error("PAGE ERROR",e.message)});await p.setViewport({width:1400,height:1000});const u=new URL("/",url);u.searchParams.set('work',w.id);u.searchParams.set('lang',lang);u.searchParams.set('view','providers');await p.goto(url);await p.goto(u.href);await p.waitForSelector('#project-profile-choice');
 assert.equal(await p.$eval('#project-profile-choice option[value="gemini-root"]',e=>e.disabled),true);
 await p.select('#project-profile-choice','claude-project');await p.click('#project-profile-select');await p.waitForSelector('#modal[open]');
 const text=await p.$eval('#modal',e=>e.textContent);assert(text.includes('.claude/CLAUDE.md'));assert(!text.includes('PRIVATE_'));assert.match(text,lang==='fr'?/Exécutant/:/Worker/);
 assert.equal(cli(['project-profile','show']).enabled,lang==='en'); // first selection is still a read-only preview
 for(const theme of ['etat','sombre']){await p.evaluate(t=>setTheme(t),theme);await p.screenshot({path:path.join(out,`selection-${lang}-${theme}.png`)})}
 await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'project-profile-select');await p.click('#project-profile-select');await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal').open);assert.match(await p.$eval('#project-profile-config',e=>e.textContent),/\.claude/);assert.equal(cli(['project-profile','list']).active_source,'claude-project');checks.push(lang+': explicit selection, file/role preview, confirmation, Escape/focus and CLI parity');
 if(!launched){w=cli(['work','show',w.id]);w=w.work||w;launched=cli(['agent','start',w.id],{schema_version:1,event_id:'launch',expected_revision:w.revision,task_id:'t1',provider:'claude',workspace:root,instruction:'Print a fixture result; no real provider',role:'worker',timeout_seconds:20,capture_output:false}).agent;assert.equal(launched.workflow.project.source,'claude-project')}
 await p.select('#project-profile-choice','agents-root');await p.click('#project-profile-select');await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal').open);assert.equal(cli(['project-profile','list']).active_source,'agents-root');
 const viewURL=new URL("/",url);viewURL.searchParams.set('work',w.id);viewURL.searchParams.set('lang',lang);viewURL.searchParams.set('view','tasks');await p.goto(viewURL.href);await p.waitForSelector('[data-profile-line]');const profileText=await p.$eval('[data-task="t1"] [data-profile-line]',e=>e.textContent);assert.match(profileText,/\.claude/);assert((await p.$$('.graph-arete')).length>=1,'dependency arrow lost');checks.push(lang+': graph keeps arrows and original Claude profile after current selection changes');
 await p.evaluate(()=>showView('conduite'));await p.waitForSelector('#pilot-canvas',{visible:true});for(let i=0;i<6;i++)await p.click('#pilot-zoom-in');assert(await p.$eval('#pilot-canvas',e=>e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0));await p.$eval('#pilot-canvas',e=>e.scrollIntoView({block:'center'}));for(const theme of ['etat','sombre']){await p.evaluate(t=>setTheme(t),theme);await p.screenshot({path:path.join(out,`agent-${lang}-${theme}.png`)})}
 await p.evaluate(()=>showView('agents'));await p.waitForSelector('.profile-marker[data-profile-family="claude"]');const badgeText=await p.$eval('.profile-marker[data-profile-family="claude"]',e=>e.textContent);assert.match(badgeText,/\.claude/);assert(!badgeText.includes('AGENTS.md'));await p.$eval('.profile-marker[data-profile-family="claude"]',e=>e.scrollIntoView({block:'center'}));await p.screenshot({path:path.join(out,`agent-card-${lang}.png`)});await p.close();
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({checks,root,real_ai_calls:0},null,2));console.log(checks.join('\n'));
 }finally{if(browser)await browser.close();if(app)app.kill('SIGTERM')}})().catch(e=>{console.error(e);process.exitCode=1});
