'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{spawn,spawnSync}=require('child_process'),puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-provider-wait-ui-'));let app,browser;
function cli(args,input){const p=spawnSync(binary,['--root',root,'--json',...args,...(input?['--input','-']:[])],{input:input?JSON.stringify(input):undefined,encoding:'utf8'});assert.equal(p.status,0,p.stderr+p.stdout);return p.stdout?JSON.parse(p.stdout):null}
(async()=>{cli(['init']);const w=cli(['work','create'],{schema_version:1,event_id:'create',expected_revision:0,title:'Preparation settings QA',objective:'Configure preparation timeouts',scope:'isolated',criteria:['Admin values affect preparation'],next:'Configure'}).work;
app=spawn(binary,['--root',root,'web','127.0.0.1:0']);const url=await new Promise((resolve,reject)=>{let text='';app.stdout.on('data',x=>{text+=x;const m=text.match(/http:\/\/[^\s]+/);if(m)resolve(m[0])});app.on('exit',c=>reject(Error('server '+c)))});
browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});const errors=[],checks=[];
try{for(const lang of ['fr','en'])for(const theme of ['etat','sombre']){
 const p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});p.on('requestfailed',r=>errors.push(r.url()+': '+r.failure().errorText));p.setDefaultTimeout(30000);await p.setViewport({width:1440,height:1100});
 const u=new URL(url);u.searchParams.set('work',w.id);u.searchParams.set('view','admin');u.searchParams.set('lang',lang);await p.goto(u.href);await p.waitForFunction(()=>document.querySelector('#provider-wait-edit')&&!document.querySelector('#provider-wait-edit').disabled);await p.waitForFunction(()=>typeof csrf!=='undefined'&&csrf);await p.waitForFunction(()=>typeof snapshot!=='undefined'&&snapshot?.work&&!document.querySelector('#work').disabled);if(await p.$eval('[data-view="admin"]',e=>e.getClientRects().length===0))await p.click('#mode');if(!await p.$eval('[data-view="admin"]',e=>e.closest('details').open))await p.click('[data-nav-group="configuration"] > summary');await p.click('[data-view="admin"]');await p.waitForFunction(()=>!document.querySelector('#admin').hidden);await p.evaluate(t=>{document.documentElement.dataset.theme=t},theme);
 assert.match(await p.$eval('#provider-wait-admin',e=>e.textContent),lang==='en'?/Planner and reviewer agents/:/Agents responsables et vérificateurs/);
 const before=cli(['run-limits','provider-wait','show']);await p.click('#provider-wait-edit');assert.equal(await p.evaluate(()=>document.activeElement.id),'provider-wait-default');
 const set=async(id,value)=>p.$eval('#'+id,(e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}))},value);
 const next=before.values.silence_seconds+10;await set('provider-wait-default',-1);await set('provider-wait-reason','Préparation APEX complexe — recette');await p.$eval('#provider-wait-modal form',e=>e.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await p.waitForSelector('#provider-wait-error:not([hidden])');assert.equal(cli(['run-limits','provider-wait','show']).revision,before.revision);
 await p.$eval('#provider-wait-maximum',e=>e.closest('details').open=true);await set('provider-wait-default',next);await set('provider-wait-maximum',0);await p.click('#provider-wait-confirm');await p.waitForSelector('#provider-wait-preview:not([hidden])');assert.equal(cli(['run-limits','provider-wait','show']).revision,before.revision);
 await p.screenshot({path:path.join(out,lang+'-'+theme+'-preview.png'),fullPage:false});await p.click('#provider-wait-confirm');await p.waitForFunction(()=>!document.querySelector('#provider-wait-modal'));
 await p.waitForFunction(()=>!document.querySelector('#provider-wait-edit').disabled&&document.activeElement.id==='provider-wait-edit');const saved=cli(['run-limits','provider-wait','show']);assert.equal(saved.values.silence_seconds,next);assert.equal(saved.values.max_duration_seconds,0);assert.equal(saved.revision,before.revision+1);assert.equal(await p.evaluate(()=>document.activeElement.id),'provider-wait-edit');
 assert.equal(cli(['run-limits','provider-wait','show']).values.silence_seconds,next)
 await p.reload();await p.waitForFunction(value=>document.querySelector('#provider-wait-current')?.textContent.includes(String(value)),{},next);await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);await p.screenshot({path:path.join(out,lang+'-'+theme+'.png'),fullPage:false});
 await p.click('#provider-wait-edit');await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('#provider-wait-modal'));assert.equal(await p.evaluate(()=>document.activeElement.id),'provider-wait-edit');
 await p.setViewport({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await p.click('#provider-wait-edit');assert.equal(await p.evaluate(()=>document.querySelector('#provider-wait-modal').getBoundingClientRect().width<=innerWidth),true);await p.screenshot({path:path.join(out,lang+'-'+theme+'-mobile.png')});await p.keyboard.press('Escape');
 checks.push(lang+' / '+theme+': invalid refusal, preview without write, persisted save, reload, focus/Escape, mobile');await p.close();
}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({root,checks,errors},null,2));console.log(JSON.stringify({checks,errors}));}finally{await browser.close();app.kill('SIGTERM')}})().catch(e=>{console.error(e);if(app)app.kill('SIGTERM');if(browser)browser.close();process.exitCode=1});
