// End-to-end provider policy administration via rendered controls, in an isolated store.
const fs=require('fs'),cp=require('child_process'),assert=require('assert'),pup=require('/home/fpizzi/node_modules/puppeteer');
const binary=process.argv[2]||'/tmp/swarm-model-routing',outdir=process.argv[3]||'docs/plans/swarm-provider-routing/evidence';
(async()=>{
 fs.mkdirSync(outdir,{recursive:true});
 const fixture=JSON.parse(cp.execFileSync('python3',['tools/swarm-companion/tests/assist_fixture.py',binary,'tools/swarm-companion/tests/assist_provider.py'],{encoding:'utf8'}));
 const server=cp.spawn(binary,['--root',fixture.root,'web']);let log='';server.stdout.on('data',d=>log+=d);server.stderr.on('data',d=>log+=d);
 const wait=ms=>new Promise(r=>setTimeout(r,ms));for(let i=0;i<200&&!log.includes('/session/');i++)await wait(100);assert(log.includes('/session/'),log);
 const browser=await pup.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const checks=[],errors=[];
 try{
 const p=await browser.newPage();p.setDefaultTimeout(30000);p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width:1500,height:1100});await p.goto(log.match(/http:\/\/\S+/)[0]);await p.waitForSelector('#work option');await p.select('#work',fixture.work);await p.waitForSelector('[data-task="AS-01"]');
 await p.click('[data-view="providers"]');await p.waitForSelector('[data-provider="fixture-ok"]');
 const card='[data-provider="fixture-ok"]';assert((await p.$eval(card,e=>e.textContent)).includes('haiku'));checks.push('Administration accessible depuis la navigation ; catalogue local affiché');
 await p.click(card+' button');await p.waitForSelector('#field-work_level');await p.select('#field-work_level','simple');await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#preview').hidden);assert((await p.$eval('#preview',e=>e.textContent)).includes('POLITIQUE À ENREGISTRER'));
 for(const theme of ['etat','sombre']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);await p.screenshot({path:outdir+'/policy-modal-'+theme+'.png'})}
 await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('#modal').open);assert(await p.$eval(card+' button',e=>e===document.activeElement));assert.equal(JSON.parse(fs.readFileSync(fixture.root+'/.swarm/providers.json')).providers['fixture-ok'].model_policy,undefined);checks.push('Aperçu, annulation Échap et restitution du focus ; aucune mutation avant confirmation');
 await p.click(card+' button');await p.select('#field-work_level','simple');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’enregistrement'&&!document.querySelector('#confirm').disabled);await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal').open);assert.equal(JSON.parse(fs.readFileSync(fixture.root+'/.swarm/providers.json')).providers['fixture-ok'].model_policy.work_level,'simple');checks.push('Enregistrement confirmé par bouton, politique durable');
 await p.reload();await p.waitForSelector(card);assert((await p.$eval(card,e=>e.textContent)).includes('travaux simple'));checks.push('Réouverture directe de la page admin après rechargement');
 const downloads=fixture.root+'/downloads';fs.mkdirSync(downloads);const cdp=await p.createCDPSession();await cdp.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});await p.click('#providers-export');for(let i=0;i<100&&!fs.existsSync(downloads+'/swarm-model-policies.v1.json');i++)await wait(100);const exported=JSON.parse(fs.readFileSync(downloads+'/swarm-model-policies.v1.json'));assert(!JSON.stringify(exported).includes('command'));exported.policies['fixture-ok'].work_level='standard';await p.click('#providers-import');await p.type('#field-document',JSON.stringify(exported));await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#confirm').textContent==='Confirmer l’enregistrement');await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal').open);assert.equal(JSON.parse(fs.readFileSync(fixture.root+'/.swarm/providers.json')).providers['fixture-ok'].model_policy.work_level,'standard');checks.push('Export téléchargé et import versionné confirmé par les boutons');
 await p.click('#providers-import');await p.type('#field-document','{"version":1,"policies":{},"command":"evil"}');await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal-error').hidden);assert((await p.$eval('#modal-error',e=>e.textContent)).includes('Import limité'));await p.click('#cancel');checks.push('Import de commande rejeté dans la modale');
 for(const theme of ['etat','sombre']){await p.evaluate(t=>{document.documentElement.dataset.theme=t;window.scrollTo(0,0)},theme);await p.screenshot({path:outdir+'/admin-'+theme+'.png'})}
 await p.click(card+' button:nth-child(2)');await p.waitForSelector('#field-level');await p.waitForFunction(()=>!document.querySelector('#confirm').disabled);assert((await p.$eval('#model-selection',e=>e.textContent)).includes('haiku'));await p.select('#field-level','exigeant');await p.waitForFunction(()=>document.querySelector('#model-selection').textContent.includes('opus'));await p.select('#field-level','simple');await p.waitForFunction(()=>document.querySelector('#model-selection').textContent.includes('haiku'));
 await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#preview').hidden);assert((await p.$eval('#preview',e=>e.textContent)).includes('haiku'));await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal').open);await p.waitForFunction(()=>document.querySelector('#assist-answer').textContent.includes('Modèle utilisé :'));assert((await p.$eval('#assist-answer',e=>e.textContent)).includes('haiku'));checks.push('Test IA depuis la carte fournisseur : niveau choisi, aperçu exact, réponse et modèle conservés');
 await p.reload();await p.waitForFunction(()=>document.querySelector('#assist-answer').textContent.includes('haiku'));checks.push('Modèle de la réponse conservé après rechargement');
 await p.click('[data-view="tasks"]');await p.click('[data-task="AS-01"] button');await p.waitForSelector('#field-action');await p.select('#field-action','report');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#preview').textContent.includes('Rapport de fixture'));assert(await p.$eval('#modal-error',e=>e.hidden));await p.click('#cancel');checks.push('Changer de lancement vers lecture du rapport ne reste pas bloqué par une résolution de modèle en cours');
 assert.deepEqual(errors,[]);fs.writeFileSync(outdir+'/ui.json',JSON.stringify({fixture:fixture.root,checks,errors,at:new Date().toISOString()},null,2));console.log(checks.join('\n'));
 }finally{await browser.close();server.kill('SIGTERM')}
})().catch(e=>{console.error(e);process.exitCode=1});
