const assert=require('node:assert/strict');
const cp=require('node:child_process');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const puppeteer=require('puppeteer');

(async()=>{
 const binary=process.argv[2]||'/tmp/swarm-q9-companion';
 const fixture=cp.spawnSync('python3',['tests/web_fixture.py',binary],{encoding:'utf8'});if(fixture.status!==0||!fixture.stdout.trim())throw Error(fixture.stderr||fixture.error?.message||'Fixture indisponible');const root=fixture.stdout.trim();
 const output=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-q9-ui-'));
 const cli=(args,data)=>{const full=['--root',root,'--json',...args,...(data?['--input','-']:[])],r=cp.spawnSync(binary,full,{encoding:'utf8',input:data?JSON.stringify(data):undefined});if(r.status!==0)throw Error(r.stderr);return JSON.parse(r.stdout)};
 let target=cli(['work','create'],{schema_version:1,event_id:'q9-create',expected_revision:0,title:'Mission à supprimer en recette',objective:'Tester la corbeille Q9 sur une racine isolée.',scope:'Fixture temporaire uniquement.',criteria:['Cycle récupérable'],next:'Examiner un aperçu.'}).work;
 const server=cp.spawn(binary,['--root',root,'web']);let stdout='';server.stdout.on('data',d=>stdout+=d);server.stderr.on('data',d=>stdout+=d);
 const until=Date.now()+15000;while(!stdout.includes('http://')&&Date.now()<until)await new Promise(r=>setTimeout(r,50));
 const url=stdout.match(/http:\/\/\S+/)?.[0];if(!url)throw Error('Serveur indisponible : '+stdout);
 const browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome'});
 const page=await browser.newPage();page.setDefaultTimeout(20000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.setViewport({width:1440,height:1000});await page.goto(url);await page.waitForSelector('[data-view="manage"]');await page.click('[data-view="manage"]');await page.waitForFunction(()=>document.querySelectorAll('.mission-manager-item').length>=2);assert.equal(await page.$eval('#validation-status',e=>e.hidden),true);
  await page.type('#manage-search','supprimer en recette');await page.waitForFunction(()=>document.querySelectorAll('.mission-manager-item').length===1);await page.focus('.mission-manager-item');await page.keyboard.press('Enter');await page.waitForSelector('[data-lifecycle-action="delete"]');
  await page.select('#manage-state','archived');await page.waitForSelector('[data-manage-reveal]');assert.match(await page.$eval('#manage-status',e=>e.textContent),/sélectionnée est masquée/);await page.click('[data-manage-reveal]');assert.equal(await page.$eval('.mission-manager-item[aria-selected="true"]',e=>e.dataset.mission),target.id);
  await page.focus('#manage-help');await page.keyboard.press('Enter');await page.waitForSelector('#modal[open]');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement?.id),'manage-help');
  await page.click('[data-lifecycle-action="delete"]');await page.type('#field-mission_name',target.title);await page.click('#confirm');await page.waitForFunction(()=>!document.getElementById('preview').hidden);let listed=await page.evaluate(()=>fetch('/api/v1/lifecycle/missions').then(r=>r.json()));assert.equal(listed.find(x=>x.work_id===target.id).state,'active');const deletePreview=await page.$eval('#preview',e=>e.textContent);assert.match(deletePreview,/corbeille récupérable|corbeille/);assert.doesNotMatch(deletePreview,/sorties_terminal|pilotage_et_recus|preparations_liees/);
  await page.evaluate(()=>{const original=window.fetch.bind(window);let lose=true;window.fetch=async(...args)=>{const response=await original(...args);if(lose&&String(args[1]?.body||'').includes('"kind":"lifecycle-apply"')){lose=false;throw new TypeError('Failed to fetch')}return response}});await page.click('#confirm');await page.waitForFunction(()=>document.getElementById('modal-error').textContent.includes('Connexion au cockpit interrompue'));await page.click('#confirm');await page.waitForFunction(id=>document.querySelector('.mission-manager-item[aria-selected="true"]')?.dataset.mission===id&&document.querySelector('#manage-selection')?.textContent.includes('Dans la corbeille'),{},target.id);
  assert.ok(await page.$('[data-lifecycle-action="restore"]'));await page.click('[data-lifecycle-action="restore"]');await page.click('#confirm');await page.waitForFunction(()=>!document.getElementById('preview').hidden);await page.click('#confirm',{clickCount:2,delay:15});await page.waitForFunction(id=>document.querySelector('.mission-manager-item[aria-selected="true"]')?.dataset.mission===id&&document.querySelector('#manage-selection')?.textContent.includes('Active'),{},target.id);assert.match(await page.$eval('#message',e=>e.textContent),/Restauration terminée/);
  await page.click('[data-lifecycle-action="archive"]');await page.click('#confirm');await page.waitForFunction(()=>!document.getElementById('preview').hidden);await page.click('#confirm');await page.waitForFunction(()=>document.querySelector('#manage-selection')?.textContent.includes('Archivée'));assert.equal(await page.$eval('.mission-manager-item[aria-selected="true"]',e=>e.dataset.mission),target.id);
  await page.click('[data-lifecycle-action="restore"]');await page.click('#confirm');await page.waitForFunction(()=>!document.getElementById('preview').hidden);await page.click('#confirm');await page.waitForFunction(()=>document.querySelector('#manage-selection')?.textContent.includes('Active'));
  await page.click('[data-lifecycle-action="purge"]');await page.click('#confirm');await page.waitForFunction(()=>!document.getElementById('preview').hidden);assert.match(await page.$eval('#preview',e=>e.textContent),/preuves|reçus|fichiers/);assert.match(await page.$eval('#preview',e=>e.textContent),/Date limite/);for(const theme of ['etat','sombre']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.screenshot({path:path.join(output,'q9-modal-'+theme+'.png'),fullPage:true})}await page.keyboard.press('Escape');
  const themes={};for(const theme of ['etat','sombre']){await page.evaluate(t=>{document.documentElement.dataset.theme=t},theme);themes[theme]=await page.$eval('#manage-selection',e=>({background:getComputedStyle(e).backgroundColor,color:getComputedStyle(e).color,border:getComputedStyle(e).borderColor}));assert.notEqual(themes[theme].background,'rgba(0, 0, 0, 0)');await page.screenshot({path:path.join(output,'q9-'+theme+'.png'),fullPage:true})}
  assert.deepEqual(errors,[]);const result={status:'PASS',root,output,checks:['entrée Gérer les missions visible et alerte de validation locale masquée','recherche, sélection clavier et révélation après filtre masquant','aide modale, Échap et restitution du focus','suppression en deux confirmations avec nom exact','aucun effet au premier clic ni à l’aperçu','réponse réseau perdue puis rejeu du même identifiant de mutation','double clic sans double mutation','corbeille récupérable et restauration','archivage et restauration','aperçu traduit de purge sans application','sélection stable après suppression et restauration','rendus État et sombre avec jetons résolus'],themes};fs.writeFileSync(path.join(output,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
 }catch(e){console.error(await page.$eval('#modal',e=>e.textContent));await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw e}finally{await browser.close();server.kill()}
})().catch(e=>{console.error(e);process.exitCode=1});
