'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{spawn}=require('child_process'),puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]),root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-budget-ui-'));fs.mkdirSync(out,{recursive:true});let app,browser;
async function cli(args,input){return new Promise((resolve,reject)=>{const p=spawn(binary,['--root',root,'--json',...args,...(input?['--input','-']:[])]);let text='',err='';p.stdout.on('data',x=>text+=x);p.stderr.on('data',x=>err+=x);p.on('exit',c=>c?reject(Error(err||text)):resolve(text?JSON.parse(text):null));p.stdin.end(input?JSON.stringify(input):undefined)})}
(async()=>{
 await cli(['init']);let w=(await cli(['work','create'],{schema_version:1,event_id:'create',expected_revision:0,title:'Budget test',objective:'Verify budget changes',scope:'isolated',criteria:['No lost updates'],next:'Configure'})).work;
 const provider=path.join(root,'claude');fs.writeFileSync(provider,'#!/bin/sh\ncat >/dev/null\n',{mode:0o700});fs.writeFileSync(path.join(root,'.swarm/providers.json'),JSON.stringify({schema_version:1,providers:{claude:{command:provider,args:['-p','--output-format','stream-json','--verbose']}}}));
 w=await cli(['planning','enable',w.id],{schema_version:1,event_id:'enable',expected_revision:w.revision,provider:'claude',max_tasks:10,max_decisions:10,max_activations:15,max_review_calls:7});w=w.work||w;await cli(['mission','pause',w.id]);
 app=spawn(binary,['--root',root,'web','127.0.0.1:0']);const url=await new Promise((resolve,reject)=>{let text='';app.stdout.on('data',x=>{text+=x;const m=text.match(/http:\/\/[^\s]+/);if(m)resolve(m[0])});app.on('exit',c=>reject(Error('server '+c)))});
 browser=await puppeteer.launch({headless:true,args:['--no-sandbox']});const p=await browser.newPage();await p.setViewport({width:1400,height:1000});const errors=[];p.on('pageerror',e=>errors.push(String(e)));
 for(const lang of ['fr','en']){
  const u=new URL(url);u.searchParams.set('work',w.id);u.searchParams.set('lang',lang);await p.goto(u.href);await p.waitForFunction(()=>typeof snapshot!=='undefined' && snapshot?.work);
  await p.evaluate(()=>showView('conduite'));await p.click('#planning-ownership .planning-tree button');await p.waitForSelector('#modal[open]');await p.select('#field-inherit','false');await p.select('#field-level','exigeant');await p.waitForFunction(()=>modalContext.modelReady);
  const before=await cli(['role-model','show',w.id]);await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#preview').hidden&&!document.querySelector('#confirm').disabled);assert.equal((await cli(['role-model','show',w.id])).revision,before.revision);
  for(const theme of ['etat','sombre']){await p.evaluate(t=>setTheme(t),theme);await p.screenshot({path:path.join(out,'role-model-'+lang+'-'+theme+'.png')})}
  await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal').open);let after=await cli(['role-model','show',w.id]);assert.equal(after.planning.scopes[0].model_selection.route.model,'opus');assert.equal(after.planning.reviewer.model_route.model,lang==='fr'?'sonnet':'opus');assert.equal(after.planning.activations,0);
  await p.evaluate(()=>RoleModels.open('',true));await p.select('#field-level','exigeant');await p.waitForFunction(()=>modalContext.modelReady);await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#preview').hidden&&!document.querySelector('#confirm').disabled);await p.click('#confirm');await p.waitForFunction(()=>!document.querySelector('#modal').open);after=await cli(['role-model','show',w.id]);assert.equal(after.planning.reviewer.model_route.model,'opus');assert.equal(after.planning.reviewer.calls,0);assert.equal(after.planning.reviewer.max_calls,7);
  await p.click('#planning-ownership .planning-tree button');await p.keyboard.press('Escape');assert.match(await p.evaluate(()=>document.activeElement.textContent),/Modèle du responsable|Planner model/);
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'PASS',checks:['read-only preview','web CLI persistence','planner and reviewer independent','consumption preserved','FR EN both themes'],root},null,2));console.log('PASS role models UI');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(app)app.kill()});
