'use strict';
// Real browser, HTTP and Go-engine contract on four isolated copies of a
// synthetic completed-producer fixture. No provider is started.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{spawn}=require('child_process'),puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]||'/tmp/t2-recheck-evidence'),base=path.join(out,'base-store'),work=fs.readFileSync(path.join(out,'work-id.txt'),'utf8').trim();
function processJSON(args){return new Promise((resolve,reject)=>{const child=spawn(binary,args);let stdout='',stderr='';child.stdout.on('data',x=>stdout+=x);child.stderr.on('data',x=>stderr+=x);child.on('exit',code=>code?reject(Error(stderr||stdout)):resolve(stdout.trim()?JSON.parse(stdout):null))})}
async function journey(browser,lang,theme){
 const root=path.join(out,`store-${lang}-${theme}`);fs.cpSync(base,root,{recursive:true});let server;
 try{
  const before=await processJSON(['--root',root,'--json','work','show',work]),agentsBefore=await processJSON(['--root',root,'--json','agent','list',work]);
  server=spawn(binary,['--root',root,'web','127.0.0.1:0']);const url=await new Promise((resolve,reject)=>{let text='';server.stdout.on('data',x=>{text+=x;const match=text.match(/http:\/\/[^\s]+/);if(match)resolve(match[0])});server.stderr.on('data',x=>text+=x);server.on('exit',code=>reject(Error(`server ${code}: ${text}`))) });
  const page=await browser.newPage(),errors=[],failedRequests=[],actions=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',e=>{if(e.type()==='error')errors.push(e.text())});page.on('requestfailed',r=>failedRequests.push(r.url()));page.on('request',r=>{if(r.url().endsWith('/api/v1/action')&&r.method()==='POST')actions.push(JSON.parse(r.postData()))});await page.setViewport({width:1400,height:1000});
  const target=new URL(url);target.searchParams.set('work',work);target.searchParams.set('lang',lang);await page.goto(target.href);await page.waitForFunction(()=>typeof snapshot!=='undefined'&&snapshot?.work?.tasks?.some(t=>t.id==='t1'));
  if(await page.$eval('html',e=>e.dataset.theme)!==theme)await page.click('#theme');assert.equal(await page.$eval('html',e=>e.dataset.theme),theme);
  const evidenceChecks=await page.evaluate(()=>{
   const e={attempt_id:'new-attempt',revision:12,freshness:'fresh',report_review:{state:'passed',at:'now',limits:[]},controls:{state:'passed',items:[{id:'current-control',command:['go','test'],result:'passed',execution:'executed',wall_duration_ms:1200,cpu_duration_ms:null,cost:'unknown',tokens:'unknown'}],history:[{id:'historical-failure',command:['go','test'],result:'failed',execution:'executed',wall_duration_ms:3500,cpu_duration_ms:1000}],longest_measured:[{id:'historical-failure',wall_duration_ms:3500}]},acceptance:{state:'accepted'},limits:[]};
   const element=document.createElement('pre');element.id='t3-evidence-check';document.querySelector('main')?.append(element);if(!element.isConnected)document.body.append(element);
   SwarmEvidenceContract.render(element,e,typeof tr_web_planning_js==='function'?tr_web_planning_js:s=>s);
   const text=element.textContent,style=getComputedStyle(element);
   return {text,visible:element.getBoundingClientRect().height>0,color:style.color,background:style.backgroundColor,state:element.dataset.controlsState};
  });
  assert.equal(evidenceChecks.state,'passed');assert.equal(evidenceChecks.visible,true);assert.ok(evidenceChecks.text.indexOf('current-control')<evidenceChecks.text.indexOf('historical-failure'));assert.match(evidenceChecks.text,/1200 ms/);assert.match(evidenceChecks.text,/unknown/);assert.match(evidenceChecks.text,lang==='fr'?/Verdict actuel/:/Current verdict/);await page.screenshot({path:path.join(out,`evidence-${lang}-${theme}.png`)});
  const selector='[data-validation-recheck="t1"]';await page.waitForSelector(selector,{visible:true});await page.focus(selector);await page.keyboard.press('Enter');await page.waitForSelector('#modal[open]');assert.equal(await page.evaluate(()=>document.querySelector('#modal').contains(document.activeElement)),true);
  await page.select('#validation-mode','automatic');await page.click('#validation-add-control');const field=name=>`[data-validation-field="${name}"]`;await page.type(field('id'),'fresh-control');await page.type(field('args'),'version');await page.type(field('justification'),'Le contrôle public corrigé échoue si la commande devient invalide.');for(const box of await page.$$('[data-criterion]'))await box.click();
  await page.click('#confirm');await page.waitForFunction(()=>!document.querySelector('#preview').hidden&&!document.querySelector('#confirm').disabled);assert.match(await page.$eval('#preview',e=>e.textContent),lang==='fr'?/Recontrôle explicitement demandé/:/Explicit recheck requested/);assert.equal(actions.length,1);assert.equal(actions[0].kind,'validation-policy-preview');assert.equal(actions[0].validation_policy.recheck_completed,true);assert.equal(actions[0].expected_revision,before.work.revision);
  await page.screenshot({path:path.join(out,`preview-${lang}-${theme}.png`)});await page.click('#confirm');await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.waitForFunction(()=>snapshot.work.tasks.find(t=>t.id==='t1')?.status==='submitted');assert.equal(actions.length,2);assert.equal(actions[1].kind,'validation-policy-apply');assert.equal(actions[1].validation_policy.recheck_completed,true);assert.ok(actions[1].validation_policy.preview_token);assert.ok(actions[1].event_id);
  const after=await processJSON(['--root',root,'--json','work','show',work]),agentsAfter=await processJSON(['--root',root,'--json','agent','list',work]),task=after.work.tasks.find(t=>t.id==='t1');assert.equal(after.work.revision,before.work.revision+1);assert.equal(task.status,'submitted');assert.equal(task.attempts.length,1);assert.equal(task.attempts[0].id,before.work.tasks.find(t=>t.id==='t1').attempts[0].id);assert.equal(task.auto_validation,undefined);assert.equal(task.gate,undefined);assert.equal(agentsAfter.agents.length,agentsBefore.agents.length);assert.deepEqual(errors,[]);assert.deepEqual(failedRequests,[]);await page.close();
  return {lang,theme,preview_kind:actions[0].kind,apply_kind:actions[1].kind,recheck_preview:actions[0].validation_policy.recheck_completed,recheck_apply:actions[1].validation_policy.recheck_completed,revision_before:before.work.revision,revision_after:after.work.revision,attempt_id:task.attempts[0].id,producer_count_before:agentsBefore.agents.length,producer_count_after:agentsAfter.agents.length,status_after:task.status,stale_gate_invalidated:task.gate===undefined,stale_auto_validation_invalidated:task.auto_validation===undefined,console_errors:errors,failed_requests:failedRequests};
 }finally{if(server)server.kill('SIGTERM')}
}
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',userDataDir:path.join(out,'chrome-profile'),args:['--no-sandbox','--disable-dev-shm-usage','--disable-crash-reporter','--disable-breakpad']});try{const observations=[];for(const lang of ['fr','en'])for(const theme of ['etat','sombre'])observations.push(await journey(browser,lang,theme));const result={status:'PASS',fixture:'isolated synthetic completed producer; real candidate binary, HTTP API and browser; no provider',checks:['keyboard action','preview then apply','recheck_completed on both requests','revision advances once','same attempt','no new producer','stale gate and auto-validation invalidated','FR/EN','both themes','browser diagnostics'],observations};fs.writeFileSync(path.join(out,'browser-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2))}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
