'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {spawn,spawnSync}=require('node:child_process');
const puppeteer=require(process.env.PUPPETEER_MODULE||'puppeteer');
const binary=path.resolve(process.argv[2]),outDir=path.resolve(process.argv[3]);
fs.mkdirSync(outDir,{recursive:true});
const root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-q7-')),uuid=()=>require('node:crypto').randomUUID().replace(/-/g,'');
const run=(args,input)=>{const r=spawnSync(binary,['--root',root,'--json',...args],{encoding:'utf8',input});if(r.status!==0)throw new Error(r.stderr||'commande échouée');return r.stdout?JSON.parse(r.stdout):null};
const mutate=(args,revision,fields)=>run([...args,'--input','-'],JSON.stringify({schema_version:1,event_id:uuid(),expected_revision:revision,...fields})).work;
run(['init']);let work=mutate(['work','create'],0,{title:'Recette Q7',objective:'Configurer une politique sans JSON dans le web',scope:'racine isolée',criteria:['parcours visible'],next:'configurer'});
work=mutate(['task','add',work.id],work.revision,{id:'q7',title:'Valider objectivement',deliverable:'docs/q7.md',criteria:['Commande réussie','Preuve encore courante'],owner:'worker',next:'configurer'});
let server=spawn(binary,['--root',root,'web'],{stdio:['ignore','pipe','pipe']}),browser;
(async()=>{
 const url=await new Promise((resolve,reject)=>{let output='',errors='';const timer=setTimeout(()=>reject(Error('serveur web muet : '+errors)),10000);server.stderr.on('data',d=>errors+=d);server.on('error',reject);server.stdout.on('data',d=>{output+=d;const found=output.match(/http:\/\/[^\s]+\/session\/[^\s]+/);if(found){clearTimeout(timer);resolve(found[0])}})});
 browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome'});const page=await browser.newPage();page.setDefaultTimeout(15000);await page.setViewport({width:1280,height:1000});await page.goto(url+'?work='+work.id);await page.waitForFunction(()=>document.querySelector('#title')?.textContent==='Recette Q7');
 await page.click('#mode');await page.click('#tabs [data-view="tasks"]');const buttons=await page.$$('#tasks-body tr[data-task="q7"] button');assert.ok(buttons.length>=2);await buttons[1].focus();await page.keyboard.press('Enter');await page.waitForSelector('#modal[open] #validation-mode');
 assert.match(await page.$eval('#modal',e=>e.textContent),/suggestion IA/);assert.match(await page.$eval('#modal',e=>e.textContent),/Portée et limites/);
 await page.select('#validation-mode','automatic');await page.click('#validation-add-control');await page.type('[data-validation-field="id"]','go-version');await page.type('[data-validation-field="args"]','version');await page.type('[data-validation-field="justification"]','La version de Go est le critère objectif attendu.');for(const box of await page.$$('#validation-controls [data-criterion]'))await box.click();
 for(const theme of ['etat','sombre']){await page.evaluate(value=>document.documentElement.dataset.theme=value,theme);await page.screenshot({path:path.join(outDir,'validation-'+theme+'.png'),fullPage:true})}
 await page.click('#confirm');await page.waitForFunction(()=>document.querySelector('#preview').textContent.includes('Effet confirmé'));const before=await page.$eval('#preview',e=>e.textContent);assert.match(before,/contrôle structuré préautorisé/);assert.match(before,/300 secondes/);assert.match(before,/\["go","version"\]/);assert.match(before,/invalidés/);assert.match(before,/suggestion.*IA/i);
 await page.type('[data-validation-field="args"]','\nenv');assert.equal(await page.$eval('#preview',e=>e.hidden),true);assert.equal(await page.$eval('#confirm',e=>e.textContent),'Examiner l’effet');
 await page.click('#confirm');await page.waitForFunction(()=>document.querySelector('#preview').textContent.includes('Effet confirmé'));await page.click('#confirm');await page.waitForFunction(()=>!document.querySelector('#modal').open);
 let shown=run(['work','show',work.id]);assert.equal(shown.work.tasks[0].validation_policy.mode,'automatic');assert.deepEqual(shown.work.tasks[0].validation_policy.controls[0].command,['go','version','env']);assert.match(shown.work.tasks[0].validation_policy.controls[0].justification,/critère objectif/);
 run(['mission','pause',work.id]);await page.reload();await page.waitForFunction(()=>document.querySelector('#title')?.textContent==='Recette Q7');await page.click('#tabs [data-view="tasks"]');await (await page.$$('#tasks-body tr[data-task="q7"] button'))[1].click();await page.select('#validation-mode','automatic');await page.click('#confirm');await page.waitForFunction(()=>document.querySelector('#preview').textContent.includes('pause'));assert.match(await page.$eval('#preview',e=>e.textContent),/suspendus/);await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#modal').open);assert.match(await page.evaluate(()=>document.activeElement?.textContent||''),/Configurer les validations/);
 await page.keyboard.press('Enter');await page.waitForSelector('#modal[open] #validation-mode');await page.select('#validation-mode','remove');await page.click('#confirm');await page.waitForFunction(()=>document.querySelector('#preview').textContent.includes('Retirer la politique'));await page.click('#confirm');await page.waitForFunction(()=>!document.querySelector('#modal').open);shown=run(['work','show',work.id]);assert.equal(shown.work.tasks[0].validation_policy,undefined);
 fs.writeFileSync(path.join(outDir,'result.json'),JSON.stringify({status:'PASS',checks:['configuration sans JSON','aperçu puis confirmation','modification invalide aperçu','pause annoncée','retrait confirmé','clavier et restitution du focus','thèmes etat et sombre']},null,2));console.log('PASS Q7 web');
})().catch(error=>{console.error(error);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.kill()});
