'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process'),puppeteer=require('puppeteer');
const binary=path.resolve(process.argv[2]||'bin/swarm'),out=path.resolve(process.argv[3]||'test-results/version-ui'),root=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-version-ui-'));
const fixture=process.argv.includes('--fixture'),web=path.resolve(__dirname,'../web');fs.mkdirSync(out,{recursive:true});let server,browser,fixtureHealth;
const errors=[],failed=[],checks=[];
function run(args){return new Promise((resolve,reject)=>{const child=spawn(binary,args);let out='',err='';child.stdout.on('data',chunk=>out+=chunk);child.stderr.on('data',chunk=>err+=chunk);child.on('error',reject);child.on('exit',code=>code===0?resolve(out):reject(Error(`${args.join(' ')}: ${code}: ${err||out}`)))})}
async function start(){
 await run(['--root',root,'init']);if(fixture){const version=JSON.parse(await run(['--root',root,'--json','version']));fixtureHealth={state:'ready',message:'',next_step:'',volumes:[],version:{binary:version.binary,source:{available:true,commit:version.binary.commit,modified:version.binary.modified,compared:true,matches_binary:true},history:{schema_version:1,available:true,releases:[]}}};return 'http://swarm.test'}server=spawn(binary,['--root',root,'web','127.0.0.1:0']);
 return new Promise((resolve,reject)=>{let text='',err='';server.stdout.on('data',chunk=>{text+=chunk;const match=text.match(/http:\/\/[^\s]+/);if(match)resolve(match[0])});server.stderr.on('data',chunk=>err+=chunk);server.on('exit',code=>reject(Error(`server ${code}: ${err}`)))})
}
function diagnostics(page){page.on('pageerror',error=>errors.push(error.message));page.on('requestfailed',request=>failed.push(`${request.method()} ${request.url()} ${request.failure()?.errorText||''}`))}
async function installFixture(page,mode='normal'){
 if(!fixture)return null;await page.setRequestInterception(true);let release;
 const shell=surface=>`<!doctype html><html lang="fr" data-theme="etat"><head><meta charset="utf-8"><script src="/i18n-en.js" defer></script><script src="/i18n.js" defer></script><link rel="stylesheet" href="/wattson_themes.css"><link rel="stylesheet" href="/${surface==='cockpit'?'cockpit':'prephase'}.css"><script src="/runtime-health.js" defer></script></head><body>${surface==='cockpit'?'<aside class="rail"><div class="rail-bottom"><button id="version-open" type="button" data-version-open><span>Version et nouveautés</span><small id="server-version" data-version-summary role="status">Chargement de la version…</small></button></div></aside><main><section id="runtime-health" hidden></section></main>':'<header class="prep-header"><a class="brand">SWARM <span>Préparer</span></a><nav><button id="version-open" type="button" data-version-open>Version et nouveautés</button></nav></header><main><div class="prep-heading"><div><h1>Préparer un projet</h1></div><div class="prep-statuses"><span data-version-summary class="status info">Chargement de la version…</span></div></div></main>'}</body></html>`;
 page.on('request',async request=>{const url=new URL(request.url()),pathname=url.pathname;if(pathname==='/api/v1/runtime-health'){if(mode==='loading')await new Promise(resolve=>release=resolve);if(mode==='unavailable')return request.respond({status:503,contentType:'application/json',body:'{"error":"fixture unavailable"}'});return request.respond({status:200,contentType:'application/json',body:JSON.stringify(fixtureHealth)})}if(pathname==='/'||pathname==='/prepare.html')return request.respond({status:200,contentType:'text/html',body:shell(pathname==='/'?'cockpit':'prepare')});const file={'/i18n-en.js':'i18n-en.js','/i18n.js':'i18n.js','/runtime-health.js':'runtime-health.js','/wattson_themes.css':'wattson_themes.css','/cockpit.css':'cockpit.css','/prephase.css':'prephase.css'}[pathname];if(file)return request.respond({status:200,contentType:file.endsWith('.css')?'text/css':'text/javascript',body:fs.readFileSync(path.join(web,file))});return request.respond({status:204,body:''})});return ()=>release?.();
}
async function verifySurface(base,surface,lang,theme){
 const page=await browser.newPage();diagnostics(page);await installFixture(page);await page.setViewport({width:1440,height:1000});
 const url=new URL(surface==='cockpit'?'/' : '/prepare.html',base);url.searchParams.set('lang',lang);await page.goto(url.href);await page.waitForFunction(()=>!document.querySelector('[data-version-summary]').textContent.includes('Chargement')&&!document.querySelector('[data-version-summary]').textContent.includes('Loading'));
 await page.evaluate(value=>{document.documentElement.dataset.theme=value;localStorage.setItem('swarm-theme',value)},theme);
 const health=await page.evaluate(()=>fetch('/api/v1/runtime-health').then(response=>response.json())),summary=await page.$eval('[data-version-summary]',element=>element.textContent);
 assert.ok(summary.includes(health.version.binary.version),summary);assert.ok(summary.includes(health.version.binary.commit?.slice(0,12)|| (lang==='en'?'unknown':'inconnu')),summary);
 const buttonText=await page.$eval('[data-version-open]',element=>element.textContent);assert.match(buttonText,lang==='en'?/Version and what's new/:/Version et nouveautés/);
 await page.focus('[data-version-open]');await page.keyboard.press('Enter');await page.waitForSelector('#version-dialog[open]');
 const modal=await page.$eval('#version-dialog',element=>element.textContent);assert.match(modal,lang==='en'?/Running binary/:/Binaire lancé/);assert.match(modal,lang==='en'?/No published version has been declared yet/:/Aucune version publiée n’est encore déclarée/);
 const link=await page.$eval('#version-dialog a[href*="github.com/mo0ogly/swarm/commits/main"]',element=>({target:element.target,rel:element.rel,href:element.href}));assert.equal(link.target,'_blank');assert.match(link.rel,/noopener/);assert.equal(link.href,'https://github.com/mo0ogly/swarm/commits/main/');
 const colors=await page.$eval('#version-dialog a',a=>({ink:getComputedStyle(a).color,background:getComputedStyle(a.closest('section')).backgroundColor}));const luminance=value=>{const c=value.match(/[0-9.]+/g).slice(0,3).map(Number).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4});return .2126*c[0]+.7152*c[1]+.0722*c[2]};const l=[luminance(colors.ink),luminance(colors.background)].sort((a,b)=>b-a);assert.ok((l[0]+.05)/(l[1]+.05)>=4.5,'GitHub link contrast below 4.5:1');
 await page.screenshot({path:path.join(out,`${surface}-${lang}-${theme}.png`),fullPage:true});await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#version-dialog').open);assert.equal(await page.evaluate(()=>document.activeElement.id),'version-open');
 checks.push(`${surface} ${lang}/${theme}: binary version+commit, empty history, safe link, keyboard/Escape/focus`);await page.close();
}
async function verifyLoading(base){
 const page=await browser.newPage();diagnostics(page);let release;if(fixture)release=await installFixture(page,'loading');else{await page.setRequestInterception(true);page.on('request',async request=>{if(request.url().endsWith('/api/v1/runtime-health')){await new Promise(resolve=>release=resolve);return request.continue()}request.continue()})}
 await page.goto(new URL('/prepare.html?lang=fr',base).href);await page.waitForSelector('[data-version-open]');await page.click('[data-version-open]');await page.waitForSelector('#version-dialog[open]');assert.match(await page.$eval('#version-dialog',element=>element.textContent),/Chargement de la version et des nouveautés/);await page.screenshot({path:path.join(out,'loading-fr-etat.png')});release();await page.waitForFunction(()=>document.querySelector('[data-version-summary]').textContent!=='Chargement de la version…');checks.push(`loading state before delayed ${fixture?'fixture':'real'} runtime-health response`);await page.close();
}
async function verifyUnavailable(base){
 const page=await browser.newPage();diagnostics(page);if(fixture)await installFixture(page,'unavailable');else{await page.setRequestInterception(true);page.on('request',request=>request.url().endsWith('/api/v1/runtime-health')?request.respond({status:503,contentType:'application/json',body:'{"error":"fixture unavailable"}'}):request.continue())}
 await page.goto(new URL('/prepare.html?lang=en',base).href);await page.waitForFunction(()=>document.querySelector('[data-version-summary]').textContent==='Version unavailable');await page.evaluate(()=>document.documentElement.dataset.theme='sombre');await page.click('[data-version-open]');await page.waitForSelector('#version-dialog[open]');assert.match(await page.$eval('#version-dialog',element=>element.textContent),/Version and history unavailable/);await page.screenshot({path:path.join(out,'unavailable-en-sombre.png')});checks.push('explicit unavailable state on HTTP 503');await page.close();
}
(async()=>{try{
 const base=await start();browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});
 if(!fixture){const session=await browser.newPage();diagnostics(session);await session.goto(base,{waitUntil:'networkidle0'});await session.close()} // Authenticate through the actual session link before navigating away.
 for(const surface of ['cockpit','prepare'])for(const lang of ['fr','en'])for(const theme of ['etat','sombre'])await verifySurface(base,surface,lang,theme);
 await verifyLoading(base);await verifyUnavailable(base);assert.deepEqual(errors,[],'page errors');assert.deepEqual(failed,[],'unexpected failed requests');
 const status=fixture?'PARTIAL':'PASS';fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status,mode:fixture?'browser fixture; server socket unavailable':'real candidate server',root,binary,checks,errors,failed},null,2));console.log(`${status} version UI (${checks.length} checks; ${out})`);
}finally{await browser?.close();server?.kill('SIGTERM')}})().catch(error=>{fs.writeFileSync(path.join(out,'failure.txt'),error.stack);console.error(error);process.exitCode=1});
