'use strict';
const fs = require('node:fs');
const catalog = JSON.parse(fs.readFileSync('locales/en.json', 'utf8'));
fs.writeFileSync('web/i18n-en.js', "'use strict';\n// Generated by npm run i18n:build. Edit locales/en.json.\nglobalThis.SwarmEnglish = " + JSON.stringify(catalog, null, 2) + ';\n');
