"""Build an offline, bilingual lesson reader from the recorded storyboard."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
DATA=json.loads((ROOT/'storyboard.json').read_text())
HTML='''<!doctype html>
<html lang="fr" data-theme="etat"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Casa Pizza — Tutoriels Swarm</title>
<link rel="icon" href="swarm-logo.png" type="image/png">
<style>
:root{--bg:#f7f5ef;--surface:#fff;--ink:#16392f;--muted:#46594e;--line:#c7d3cb;--accent:#16392f;--on:#fff;--soft:#e9efe9;--focus:#97502f}
[data-theme=sombre]{--bg:#12241d;--surface:#1d342a;--ink:#eff5ee;--muted:#c0d0c4;--line:#476354;--accent:#d7eadb;--on:#152a20;--soft:#2a4436;--focus:#edb093}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:18px/1.55 system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:24px}.training-brand{display:flex;gap:18px;align-items:center;min-width:0}.swarm-logo{flex:none;width:108px;height:108px;object-fit:contain;padding:8px;background:var(--soft);filter:drop-shadow(0 0 1px var(--ink))}@media(max-width:650px){.training-brand{gap:12px}.swarm-logo{width:72px;height:72px}}header{display:flex;justify-content:space-between;gap:18px;flex-wrap:wrap;align-items:center}h1{font-size:32px;line-height:1.2;margin:12px 0}h2{font-size:25px}h3{font-size:21px}p{max-width:85ch}a{color:var(--ink)}button,select{font:inherit;border:1px solid var(--line);border-radius:8px;padding:10px 16px;background:var(--surface);color:var(--ink);cursor:pointer}button:focus-visible,select:focus-visible,a:focus-visible,summary:focus-visible{outline:3px solid var(--focus);outline-offset:3px}button[aria-current=true],.primary{background:var(--accent);color:var(--on)}button:disabled{opacity:.5;cursor:default}nav{display:flex;gap:10px;flex-wrap:wrap;margin:22px 0}.panel{border:1px solid var(--line);padding:20px;border-radius:12px;background:var(--surface);margin:18px 0}.secondary{background:var(--soft)}.tools{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.muted{color:var(--muted)}img,video{width:100%;height:auto;border:1px solid var(--line);border-radius:7px;background:var(--surface)}video{max-height:680px}figure{margin:0}.stepmeta{display:flex;gap:16px;justify-content:space-between;align-items:baseline;flex-wrap:wrap}#step-result{font-size:20px}summary{cursor:pointer;font-weight:600;padding:8px 0}details{border-top:1px solid var(--line);padding:8px 0}ol li{margin:12px 0}.download{display:flex;gap:16px;flex-wrap:wrap}#video-caption{min-height:3em}footer{margin:28px 0;color:var(--muted)}@media(max-width:650px){main{padding:14px}.panel{padding:14px}h1{font-size:28px}button{padding:9px 12px}}
</style>
<main>
<header><div class="training-brand"><img class="swarm-logo" src="swarm-logo.png" width="108" height="108" alt=""><div><span class="muted">CASA PIZZA · SWARM</span><h1 id="title"></h1></div></div><div class="tools"><label for="language" id="language-label"></label><select id="language"><option value="fr">Français</option><option value="en">English</option></select><button id="theme" type="button"></button></div></header>
<p id="intro"></p><p class="muted" id="scope"></p>
<nav id="chapters" aria-label="Chapters"></nav>
<section class="panel" aria-labelledby="lesson-title"><h2 id="lesson-title"></h2><p id="related"></p><div class="tools"><button id="step-mode" type="button"></button><button id="video-mode" type="button"></button></div>
<div id="steps"><div class="stepmeta"><h3 id="step-action"></h3><span id="counter" class="muted"></span></div><figure><img id="step-image" alt=""></figure><p id="step-result" role="status" aria-live="polite"></p><div class="tools"><button id="previous" type="button"></button><button id="next" type="button" class="primary"></button></div></div>
<div id="video-box" hidden><p class="muted" id="video-note"></p><video id="video" controls preload="none" playsinline></video><p id="video-caption" aria-live="off"></p><div class="tools"><label for="speed" id="speed-label"></label><select id="speed"><option value="0.75">0.75×</option><option value="1" selected>1×</option><option value="1.5">1.5×</option></select></div></div>
</section>
<section class="panel secondary"><h2 id="exercise-title"></h2><p id="question"></p><details id="solution"><summary id="answer-title"></summary><p id="answer"></p></details><details><summary id="transcript-title"></summary><ol id="transcript"></ol></details></section>
<section class="panel"><h2 id="downloads-title"></h2><div class="download"><a id="download-video" download></a><a id="download-gif" download></a><a id="download-text" download></a></div><p id="gif-note" class="muted"></p><h3 id="guides-title"></h3><p id="resource-language" role="status" aria-live="polite"></p><p><a id="download-guide" download></a></p><p id="kit-downloads" hidden><a id="download-kit" download></a></p></section>
<section class="panel secondary" id="graph-intro" aria-labelledby="graph-intro-title" hidden><h2 id="graph-intro-title">Le graphe et ses contrôles — présentation en français</h2><p>63 secondes : zoom, branches, prérequis et configuration d’un contrôle. Capture réelle montée, sans lancement d’agent ; configuration annulée.</p><video id="graph-intro-video" controls preload="none" playsinline poster="media/graph-overview-fr-poster.png" aria-label="Présentation du graphe Swarm en français"><source src="media/graph-overview-fr.mp4" type="video/mp4"><track kind="subtitles" src="media/graph-overview-fr.vtt" srclang="fr" label="Français"></video><p><a href="media/graph-overview-fr.mp4" download>Télécharger la présentation MP4 en français</a></p></section>
<footer id="footer"></footer>
</main>
<script>
const DATA=__DATA__;
const TEXT={fr:{title:'Apprendre Swarm avec Casa Pizza',language:'Langue',theme:'Changer de thème',intro:'Regardez une étape, reproduisez-la dans votre atelier, puis vérifiez son résultat. Quatre modules complètent les 36 chapitres existants des guides PDF.',scope:'Captures réelles du 9 octobre 2026, montées en séquences fixes avec légendes. Ce ne sont pas des vidéos continues. Aucun appel à un fournisseur IA pendant la capture. Plan à six tâches non exécuté ; paramètres de contrôle prévisualisés puis annulés. Commande fictive jouée manuellement.',step:'Pas à pas',video:'Vidéo courte',prev:'Étape précédente',next:'Étape suivante',exercise:'À vous de vérifier',answer:'Voir le corrigé',transcript:'Lire toutes les étapes',downloads:'Emporter ce module',mp4:'Télécharger la vidéo MP4',gif:'Télécharger l’aperçu GIF',txt:'Télécharger la transcription',gifnote:'Le GIF est un aperçu réduit. Pour lire confortablement ou éviter les animations, utilisez le mode pas à pas. Rien ne démarre automatiquement.',guides:'Continuer dans les guides PDF',speed:'Vitesse',videonote:'Sans audio. Les légendes sont intégrées à la vidéo ; la transcription reste disponible ci-dessous.',footer:'Fonctionne hors ligne après extraction du kit. Aucun CDN, aucune police distante, aucune télémétrie. L’application de référence et les noms des tâches restent en français ; les explications sont bilingues.',related:['Guide : chapitres 8 à 11 et 17 à 20.','Guide : chapitres 21 à 26.','Guide : chapitres 27 à 30.','Guide : chapitres 31 à 34.']},en:{title:'Learn Swarm with Casa Pizza',language:'Language',theme:'Change theme',intro:'Watch a step, repeat it in your workshop, then verify its result. Four modules complement the original 36 chapters in the PDF guides.',scope:'Real screenshots captured on 9 October 2026, edited into still sequences with captions. These are not continuous screencasts. No AI provider call during capture. Six-task plan unexecuted; check settings previewed then cancelled. Fictitious order advanced manually.',step:'Step by step',video:'Short video',prev:'Previous step',next:'Next step',exercise:'Check your understanding',answer:'Show the answer',transcript:'Read all steps',downloads:'Take this module with you',mp4:'Download MP4 video',gif:'Download GIF preview',txt:'Download transcript',gifnote:'The GIF is a reduced preview. Use step-by-step mode for comfortable reading or to avoid motion. Nothing starts automatically.',guides:'Continue in the PDF guides',speed:'Speed',videonote:'No audio. Captions are burned into the video; a transcript is available below.',footer:'Works offline after extracting the kit. No CDN, remote fonts or telemetry. The reference app and task names remain in French; explanations are bilingual.',related:['Guide: chapters 8–11 and 17–20.','Guide: chapters 21–26.','Guide: chapters 27–30.','Guide: chapters 31–34.']}};
const RESOURCES={fr:{guide:'Formation_Swarm_Casa_Pizza.pdf',kit:'Kit_Formation_Swarm_Casa_Pizza.zip',guideLabel:'Télécharger le guide PDF français — 38 pages',kitLabel:'Télécharger le kit complet français ZIP',notice:'Langue des ressources : français. Vidéos, GIF, transcriptions, guide PDF et kit suivent la langue choisie ci-dessus.'},en:{guide:'Swarm_Casa_Pizza_Training_EN.pdf',kit:'Swarm_Casa_Pizza_Training_Kit_EN.zip',guideLabel:'Download the English PDF guide — 38 pages',kitLabel:'Download the complete English ZIP kit',notice:'Resource language: English. Videos, GIFs, transcripts, PDF guide and kit follow the language selected above.'}};
const $=id=>document.getElementById(id);let lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'fr';let index=Math.max(0,DATA.modules.findIndex(m=>m.id===location.hash.slice(1)));let currentStep=0;let mode='steps';
function put(id,text){$(id).textContent=text}
function updateStep(){const m=DATA.modules[index],s=m.steps[currentStep];put('step-action',s.action[lang]);put('counter',`${currentStep+1} / ${m.steps.length}`);$('step-image').src='frames/'+s.frame.replace('{lang}',lang)+'.png';$('step-image').alt=s.action[lang]+'. '+s.result[lang];put('step-result',s.result[lang]);$('previous').disabled=currentStep===0;$('next').disabled=currentStep===m.steps.length-1}
function render(){$('graph-intro').hidden=lang!=='fr';$('graph-intro-video').pause();$('kit-downloads').hidden=location.protocol==='file:';const t=TEXT[lang],m=DATA.modules[index],resources=RESOURCES[lang];put('resource-language',resources.notice);put('download-guide',resources.guideLabel);$('download-guide').href='../'+resources.guide;put('download-kit',resources.kitLabel);$('download-kit').href='../'+resources.kit;document.documentElement.lang=lang;$('language').value=lang;for(const [id,k] of Object.entries({'title':'title','language-label':'language','theme':'theme','intro':'intro','scope':'scope','step-mode':'step','video-mode':'video','previous':'prev','next':'next','exercise-title':'exercise','answer-title':'answer','transcript-title':'transcript','downloads-title':'downloads','download-video':'mp4','download-gif':'gif','download-text':'txt','gif-note':'gifnote','guides-title':'guides','speed-label':'speed','video-note':'videonote','footer':'footer'}))put(id,t[k]);put('lesson-title',m.title[lang]);put('related',t.related[index]);put('question',m.question[lang]);put('answer',m.answer[lang]);$('solution').open=false;$('chapters').replaceChildren();DATA.modules.forEach((mod,i)=>{const b=document.createElement('button');b.type='button';b.textContent=`${i+1}. ${mod.title[lang]}`;b.setAttribute('aria-current',i===index?'true':'false');b.onclick=()=>{index=i;currentStep=0;location.hash=mod.id;render()};$('chapters').append(b)});$('transcript').replaceChildren();m.steps.forEach(s=>{const li=document.createElement('li');const strong=document.createElement('strong');strong.textContent=s.action[lang];li.append(strong,document.createElement('br'),document.createTextNode(s.result[lang]));$('transcript').append(li)});$('video').pause();$('video').src='media/'+m.id+'-'+lang+'.mp4';$('video').poster='media/'+m.id+'-'+lang+'-poster.jpg';$('video').playbackRate=Number($('speed').value);$('download-video').href=$('video').getAttribute('src');$('download-gif').href='media/'+m.id+'-'+lang+'.gif';$('download-text').href='media/'+m.id+'-'+lang+'.txt';put('video-caption',m.steps[0].action[lang]+' — '+m.steps[0].result[lang]);setMode(mode);updateStep()}
function setMode(next){mode=next;$('steps').hidden=mode!=='steps';$('video-box').hidden=mode!=='video';$('step-mode').setAttribute('aria-current',mode==='steps');$('video-mode').setAttribute('aria-current',mode==='video');if(mode==='steps')$('video').pause()}
$('language').onchange=()=>{lang=$('language').value;const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url);render()};$('theme').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='etat'?'sombre':'etat'};$('previous').onclick=()=>{currentStep=Math.max(0,currentStep-1);updateStep()};$('next').onclick=()=>{currentStep=Math.min(DATA.modules[index].steps.length-1,currentStep+1);updateStep()};$('step-mode').onclick=()=>setMode('steps');$('video-mode').onclick=()=>setMode('video');$('speed').onchange=()=>{$('video').playbackRate=Number($('speed').value)};$('video').ontimeupdate=()=>{const m=DATA.modules[index],s=m.steps[Math.min(m.steps.length-1,Math.floor($('video').currentTime/6))];put('video-caption',s.action[lang]+' — '+s.result[lang])};render();
</script></html>'''
rendered=HTML.replace('__DATA__',json.dumps(DATA,ensure_ascii=False))
css=rendered.split('<style>')[1].split('</style>')[0]
js=rendered.split('<script>')[1].split('</script>')[0]
(ROOT/'player.css').write_text(css.strip()+'\n')
(ROOT/'player.js').write_text(js.strip()+'\n')
rendered=rendered.replace('<style>'+css+'</style>','<link rel="stylesheet" href="player.css">').replace('<script>'+js+'</script>','<script src="player.js" defer></script>')
(ROOT/'index.html').write_text(rendered)
print('Offline player built.')
