'use strict';
const $=id=>document.getElementById(id);
const labels={todo:'À faire',running:'En cours',blocked:'Bloquée',submitted:'À vérifier',accepted:'Acceptée',waived:'Dérogation',abandoned:'Abandonnée',acknowledged:'Acquittée',queued:'En attente',starting:'Démarrage',stopping:'Arrêt demandé',completed:'Terminé',interrupted:'Interrompu',failed:'Échec'};
const active=a=>['queued','starting','running','stopping'].includes(a.status);
let csrf='',work='',snapshot=null,stream=null,view='tasks',modalContext=null,returnFocus=null,logCursor=0,logBack=[],logPage=null,follow=false,busy=false,tasksKey='',agentsKey='',decisionsKey='';
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
function notice(text,error=false){$('message').hidden=!text;$('message').textContent=text;$('message').className='notice '+(error?'alert':'info')}
async function api(path,data){const opts={headers:{}};if(data!==undefined){opts.method='POST';opts.headers={'Content-Type':'application/json','X-Swarm-CSRF':csrf};opts.body=JSON.stringify(data)}const r=await fetch(path,opts);const text=await r.text();let value;try{value=JSON.parse(text)}catch{throw new Error(text||r.statusText)}if(!r.ok)throw new Error(value.error||r.statusText);return value}
async function act(kind,fields={}){return api('/api/v1/action',{kind,work,expected_revision:modalContext?.revision??snapshot.work.revision,event_id:crypto.randomUUID(),...fields})}
function badge(status){return node('span',labels[status]||status,'badge '+(['accepted','completed','acknowledged'].includes(status)?'success':['blocked','failed','interrupted','waived'].includes(status)?'attention':'info'))}
function selectOptions(select,options,current){select.replaceChildren();for(const [value,label]of options){const o=node('option',label);o.value=value;select.append(o)}if(options.some(x=>x[0]===current))select.value=current}
function button(text,fn){const b=node('button',text);b.type='button';b.addEventListener('click',fn);return b}
function field(name,label,value='',options=null,multiline=false){const l=node('label',label);const e=node(options?'select':multiline?'textarea':'input');e.name=name;e.id='field-'+name;if(options)selectOptions(e,options,value);else e.value=value;l.htmlFor=e.id;l.append(e);$('modal-fields').append(l);return e}
function openModal(title,description,context={}){returnFocus=document.activeElement;modalContext={revision:snapshot?.work.revision,...context};$('modal-title').textContent=title;$('modal-description').textContent=description;$('modal-context').textContent=snapshot?.work.title||'SWARM';$('modal-fields').replaceChildren();$('preview').hidden=true;$('modal-error').hidden=true;$('confirm').hidden=false;$('confirm').disabled=false;$('confirm').textContent='Confirmer';$('modal').showModal()}
function closeModal(){$('modal').close();returnFocus?.focus();modalContext=null}
function preview(text){$('preview').textContent=text;$('preview').hidden=false}
async function taskDialog(id,agentID){try{const d=await api('/api/v1/task?work='+encodeURIComponent(work)+'&task='+encodeURIComponent(id));const t=d.task;openModal(t.id+' — '+t.title,t.deliverable,{task:t.id,data:d,agent:agentID});preview(d.review);const a=field('action','Action','start',[['start','Lancer un agent'],['retry','Relancer une tentative'],['stop','Arrêter une tentative'],['reconcile','Réconcilier son état'],['report','Lire le rapport'],['submit','Soumettre le rapport'],['gate','Examiner et enregistrer une gate'],['accepted','Accepter après revue'],['override','Accepter par dérogation motivée'],['todo','Rouvrir la tâche'],['assign','Changer le responsable']]);a.addEventListener('change',()=>taskFields(a.value));taskFields('start')}catch(e){notice(e.message,true)}}
function taskFields(action){const d=modalContext.data;const actionNode=$('field-action').parentNode;$('modal-fields').replaceChildren(actionNode);$('field-action').value=action;modalContext.action=action;modalContext.gatePreview=false;$('confirm').disabled=false;$('preview').hidden=true;$('confirm').textContent=action==='report'?'Lire le rapport':action==='gate'?'Examiner la gate':'Confirmer';$('modal-error').hidden=true;
 if(['start','retry'].includes(action)){preview('Périmètre : '+snapshot.work.scope+'\nLivrable : '+d.task.deliverable+'\nCritères : '+(d.task.criteria||[]).join(' ; '));if(action==='start'){field('provider','Fournisseur','',Object.keys(snapshot.providers?.providers||{}).sort().map(x=>[x,x]));field('role','Rôle','worker',[['worker','Worker — réalise la tâche'],['planner','Planner — planifie sans coder'],['subplanner','Subplanner — planifie un sous-périmètre']]);field('workspace','Espace de travail',snapshot.root)}field('instruction','Consigne',d.task.next||'',null,true);field('capture','Capture détaillée des sorties','false',[['false','Désactivée — activité structurée seulement'],['true','Activée — sorties conservées, 1 Mio maximum']])}
 if(['retry','stop','reconcile'].includes(action)){field('agent','Tentative',modalContext.agent,snapshot.agents.filter(x=>x.agent.task_id===d.task.id).map(x=>[x.agent.id,x.agent.provider+' · '+(labels[x.observed_status]||x.observed_status)+' · '+x.agent.started]))}
 if(['report','submit','gate'].includes(action)){const files=action==='gate'?d.gates:d.reports;field('path',action==='gate'?'Document de gate':'Rapport',files[0]||'',files.length?files.map(x=>[x,x]):null)}
 if(action==='override'){field('note','Motif de la dérogation','',null,true);preview('Les contrôles ne deviennent pas PASS. La décision sera conservée avec votre compte local et la date.')}
 if(action==='assign')field('owner','Responsable',d.task.owner);
 if(action==='start'&&(snapshot.providers_error||!Object.keys(snapshot.providers?.providers||{}).length)){$('modal-error').textContent=snapshot.providers_error||'Aucun fournisseur installé ou configuré.';$('modal-error').hidden=false;$('confirm').disabled=true;}
 if(action==='accepted')preview(d.review+'\n\nConfirmer après examen du rapport et des preuves.');
 if(action==='todo')preview('La validation courante sera retirée. L’historique des tentatives restera conservé.');
}
function render(){
 $('title').textContent=snapshot.work.title;$('objective').textContent=snapshot.work.objective;
 $('task-count').textContent=snapshot.work.tasks.length;$('accepted-count').textContent=snapshot.work.tasks.filter(t=>['accepted','waived'].includes(t.status)).length;$('active-count').textContent=snapshot.agents.filter(x=>active(x.agent)).length;$('decision-count').textContent=snapshot.decisions.filter(d=>!d.resolved_at).length;$('pause').textContent=snapshot.paused?'Autoriser les départs':'Suspendre les départs';
 if(tasksKey!==work){$('tasks-body').replaceChildren();tasksKey=work}
 const taskIDs=new Set(snapshot.work.tasks.map(t=>t.id));
 for(const tr of [...$('tasks-body').children])if(!taskIDs.has(tr.dataset.task))tr.remove();
 for(const t of snapshot.work.tasks){
  let tr=[...$('tasks-body').children].find(e=>e.dataset.task===t.id);
  if(!tr){tr=node('tr');tr.dataset.task=t.id;for(let i=0;i<5;i++)tr.append(node('td'));tr.children[0].append(node('strong'),node('small'));tr.children[4].append(button('Piloter',()=>taskDialog(t.id)));$('tasks-body').append(tr)}
  tr.children[0].children[0].textContent=t.title;tr.children[0].children[1].textContent=t.id;tr.children[1].replaceChildren(badge(t.status));tr.children[2].textContent=t.owner||'Non attribué';tr.children[3].textContent=(t.depends||[]).join(', ')||'Aucune';
 }
 const nextAgentsKey=JSON.stringify([work,snapshot.agents]);if(nextAgentsKey!==agentsKey){agentsKey=nextAgentsKey;const focusedAgent=document.activeElement?.closest('[data-agent]')?.dataset.agent;
 $('agents-list').replaceChildren();for(const item of snapshot.agents){const a=item.agent;const c=node('article',undefined,'card');c.dataset.agent=a.id;c.append(node('h3',a.provider+' · '+a.task_id),badge(item.observed_status),node('p','Rôle : '+a.role+' · tentative '+a.attempt_id),node('p',(active(a)?'Activité : ':'Motif enregistré à la fin : ')+a.activity),node('p','État courant de la tâche : '+(labels[snapshot.work.tasks.find(t=>t.id===a.task_id)?.status]||'Inconnu')),node('p','Dernier signal : '+(a.heartbeat||'Non reçu')+' · '+(a.ended?'Fin : '+a.ended:'Début : '+a.started)),node('p','Dernière activité détaillée : '+(a.progress?.detail||a.progress?.action||'Non disponible')),node('p','Outils : '+(a.progress?.tool_calls||0)+' appels / '+(a.progress?.tool_results||0)+' résultats'),button('Piloter cette tentative',()=>taskDialog(a.task_id,a.id)),button('Voir ses journaux',()=>{selectOptions($('log-agent'),snapshot.agents.map(x=>[x.agent.id,x.agent.provider+' · '+x.agent.task_id]),a.id);logCursor=0;logBack=[];showView('logs')}));$('agents-list').append(c)}if(!snapshot.agents.length)$('agents-list').append(node('p','Aucune tentative enregistrée.'));if(focusedAgent)[...$('agents-list').children].find(e=>e.dataset.agent===focusedAgent)?.querySelector('button')?.focus();}
 $('hierarchy').textContent=snapshot.hierarchy;
 const nextDecisionsKey=JSON.stringify([work,snapshot.decisions]);if(nextDecisionsKey!==decisionsKey){decisionsKey=nextDecisionsKey;const focusedDecision=document.activeElement?.closest('[data-decision]')?.dataset.decision;
 $('decisions-list').replaceChildren();for(const d of snapshot.decisions){const c=node('article',undefined,'card');c.dataset.decision=d.id;c.append(node('h3',d.task_id+' · '+d.kind),badge(d.resolved_at?'acknowledged':'submitted'),node('p',d.summary),node('p',d.evidence));if(d.resolved_at)c.append(node('p',d.author+' · '+d.resolved_at+' · '+d.resolution));else c.append(button('Examiner et décider',()=>{openModal('Décision — '+d.task_id,'L’acquittement ne valide pas la tâche et n’arrête pas l’agent.',{action:'decision',decision:d.id});preview(d.summary+'\n'+d.evidence);field('note','Décision motivée','',null,true)}));$('decisions-list').append(c)}if(!snapshot.decisions.length)$('decisions-list').append(node('p','Aucune décision à traiter.'));
if(focusedDecision)[...$('decisions-list').children].find(e=>e.dataset.decision===focusedDecision)?.querySelector('button')?.focus();}
 const previous=$('log-agent').value;selectOptions($('log-agent'),snapshot.agents.map(x=>[x.agent.id,x.agent.provider+' · '+x.agent.task_id+' · '+(labels[x.observed_status]||x.observed_status)]),previous);
 $('resume-text').textContent=snapshot.resume;const b=snapshot.budget;$('budget-info').replaceChildren(node('p',b.policy),node('p','Plafond : '+b.budget.limit_usd+' USD · réservé : '+b.reserved_usd+' USD · imputé estimé : '+b.committed_estimate_usd+' USD'),node('p','Source : '+(b.budget.estimate_source||'Non renseignée')+' · date : '+(b.budget.reference_date||'Non renseignée')));if(b.warning)$('budget-info').append(node('p','Seuil de 80 % atteint.','notice attention'));
 $('usage-list').replaceChildren();for(const {agent:a}of snapshot.agents){const c=node('article',undefined,'card');c.append(node('h3',a.task_id+' · '+a.provider));c.append(node('p',a.usage?('Jetons déclarés : '+a.usage.input_tokens+' entrée / '+a.usage.output_tokens+' sortie · '+a.usage.scope+' · '+a.usage.source+' · '+a.usage.at):'Jetons : indisponibles.'));if(a.usage){for(const [key,label]of [['cache_read_input_tokens','Cache lu'],['cache_creation_input_tokens','Cache créé'],['cached_input_tokens','Entrée en cache']])if(a.usage[key]!==undefined)c.append(node('p',label+' : '+a.usage[key]+' jetons déclarés (non additionnés).'));if(a.usage.provider_reported_cost_usd!==undefined)c.append(node('p','Coût déclaré par le fournisseur : '+a.usage.provider_reported_cost_usd+' USD — facture non vérifiée.'));}c.append(node('p','Coût facturé : indisponible.'));$('usage-list').append(c)}
}
async function refresh(){if(!work||busy)return;busy=true;try{snapshot=await api('/api/v1/snapshot?work='+encodeURIComponent(work));render();$('connection').textContent='Connecté · r'+snapshot.work.revision}catch(e){notice(e.message,true);$('connection').textContent='Connexion interrompue'}finally{busy=false}}
async function chooseWork(){stream?.close();work=$('work').value;logCursor=0;logBack=[];await refresh();stream=new EventSource('/api/v1/events?work='+encodeURIComponent(work)+'&after='+snapshot.work.revision);stream.addEventListener('refresh',()=>{refresh();if(follow&&view==='logs')loadLogs()});stream.onerror=()=>{$('connection').textContent='Reconnexion…'};stream.onopen=()=>{$('connection').textContent='Connecté'}}
function showView(name){view=name;for(const section of document.querySelectorAll('.view'))section.hidden=section.id!==name;for(const b of $('tabs').children){if(b.dataset.view===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')}if(name==='logs')loadLogs()}
async function loadLogs(){const agent=$('log-agent').value;if(!agent){$('log-lines').textContent='Aucune tentative à consulter.';return}try{logPage=await api('/api/v1/logs?'+new URLSearchParams({work,agent,q:$('log-search').value,kind:$('log-kind').value,after:String(logCursor)}));$('log-lines').textContent=logPage.entries.map(l=>'#'+l.seq+' '+l.at+' ['+l.kind+'] '+l.message).join('\n')||'Aucune ligne correspondante.';$('log-position').textContent='Curseur '+logCursor+' → '+logPage.next_cursor+(logPage.retention_gap?' · Début antérieur non conservé':'');$('log-next').disabled=!logPage.more;$('log-prev').disabled=!logBack.length;if(follow&&logPage.more){logCursor=logPage.next_cursor}}catch(e){notice(e.message,true)}}
$('action-form').addEventListener('submit',async event=>{event.preventDefault();if(!modalContext)return;const f=Object.fromEntries(new FormData(event.target));$('confirm').disabled=true;$('modal-error').hidden=true;try{const c=modalContext,a=c.action;
 if(a==='report'){preview((await api('/api/v1/report?'+new URLSearchParams({path:f.path}))).text);return}
 if(a==='gate'&&!c.gatePreview){preview((await act('gate-preview',{task:c.task,path:f.path})).preview);c.gatePreview=true;$('confirm').textContent='Confirmer l’enregistrement';return}
 if(a==='start'&&!f.provider)throw new Error('Aucun fournisseur configuré. Installez Claude ou Codex, puis configurez .swarm/providers.json.');
 if(a==='start')await act('start',{task:c.task,provider:f.provider,role:f.role,workspace:f.workspace,instruction:f.instruction,capture_output:f.capture==='true'});
 else if(['retry','stop','reconcile'].includes(a))await act(a,{agent:f.agent,instruction:f.instruction||'',capture_output:f.capture==='true'});
 else if(['submit','gate'].includes(a))await act(a,{task:c.task,path:f.path});
 else if(['accepted','todo','assign'].includes(a))await act('task',{task:c.task,request:a==='assign'?{owner:f.owner}:{status:a,next:a==='accepted'?'Rapport accepté depuis le cockpit web après revue.':'Tâche rouverte depuis le cockpit web.'}});
 else if(a==='override')await act('override',{task:c.task,note:f.note});
 else if(a==='decision')await act('decision',{decision:c.decision,note:f.note});
 else if(a==='ooda')await act('ooda',{request:{observation:f.observation,orientation:f.orientation,decision:f.decision,result:f.result,next:f.next}});
 else if(a==='budget'){if(!f.limit.trim()||!f.reserve.trim()||!Number.isFinite(Number(f.limit))||!Number.isFinite(Number(f.reserve)))throw new Error('Saisissez des montants numériques finis.');await act('budget',{budget:{limit_usd:Number(f.limit),reserve_per_launch_usd:Number(f.reserve),estimate_source:f.source,reference_date:f.date}});}
 closeModal();notice('Action enregistrée. L’état observé reste visible dans le tableau.');await refresh();
 }catch(e){$('modal-error').textContent=e.message;$('modal-error').hidden=false}finally{$('confirm').disabled=false}});
$('close').onclick=closeModal;$('cancel').onclick=closeModal;$('modal').addEventListener('cancel',()=>{modalContext=null;returnFocus?.focus()});
$('work').onchange=chooseWork;$('refresh').onclick=refresh;$('tabs').addEventListener('click',e=>{const b=e.target.closest('button');if(b)showView(b.dataset.view)});
$('pause').onclick=async()=>{try{await act(snapshot.paused?'unpause':'pause');await refresh()}catch(e){notice(e.message,true)}};
$('log-form').onsubmit=e=>{e.preventDefault();logCursor=0;logBack=[];loadLogs()};$('log-agent').onchange=()=>{logCursor=0;logBack=[];loadLogs()};$('log-next').onclick=()=>{logBack.push(logCursor);logCursor=logPage.next_cursor;loadLogs()};$('log-prev').onclick=()=>{logCursor=logBack.pop()||0;loadLogs()};$('log-live').onclick=()=>{follow=!follow;$('log-live').textContent=follow?'Mettre en pause':'Suivre le direct';loadLogs()};$('log-export').onclick=()=>{if(!logPage)return;const a=node('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(logPage,null,2)],{type:'application/json'}));a.download='swarm-journaux-page.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('ooda').onclick=()=>{openModal('Consigner une boucle OODA','Conservez les faits, votre décision et la prochaine action.',{action:'ooda'});for(const [key,label]of [['observation','Observation'],['orientation','Orientation'],['decision','Décision'],['result','Résultat observé'],['next','Prochaine action']])field(key,label,'',null,true)};
$('budget-edit').onclick=()=>{const b=snapshot.budget.budget;openModal('Régler le budget','Budget estimatif non garanti. Les agents actifs continuent ; les nouveaux départs sont contrôlés.',{action:'budget'});for(const [key,label,value]of [['limit','Plafond USD — 0 pour désactiver',b.limit_usd],['reserve','Réservation estimée par départ, USD',b.reserve_per_launch_usd]]){const e=field(key,label,value);e.type='number';e.min='0';e.step='any';e.required=true;}field('source','Source de l’estimation',b.estimate_source);field('date','Date de référence — AAAA-MM-JJ',b.reference_date)};
$('visit').onclick=async()=>{try{await api('/api/v1/visit?work='+encodeURIComponent(work),{});await refresh();notice('Révision marquée comme vue.')}catch(e){notice(e.message,true)}};
$('help').onclick=()=>{openModal('Utiliser le cockpit','Les états des tâches et des processus sont distincts.',{action:'help'});preview('Piloter ouvre les actions de la tâche. Après la fin d’un agent : lire le rapport, le soumettre, examiner et enregistrer la gate, puis accepter.\n\nLes décisions sont des demandes de revue : leur acquittement ne valide ni n’arrête un agent.\n\nLes journaux sont paginés et soumis à rétention. Une capture complète des sorties reste une option explicite du fournisseur.\n\nLe budget est estimatif. Une durée ou un nombre d’outils ne constitue pas un coût facturé.');$('confirm').hidden=true};
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('swarm-theme',theme);$('theme').textContent=theme==='etat'?'Passer au thème sombre':'Passer au thème clair'}
$('theme').onclick=()=>setTheme(document.documentElement.dataset.theme==='etat'?'sombre':'etat');setTheme(localStorage.getItem('swarm-theme')||'etat');
(async()=>{try{csrf=(await api('/api/v1/session')).csrf;const works=await api('/api/v1/works');selectOptions($('work'),works.map(w=>[w.id,w.title]));if(works.length)await chooseWork();else notice('Aucun travail dans cet espace.')}catch(e){notice(e.message,true)}})();
