'use strict';
const tr_web_cockpit_help_js = source => globalThis.SwarmI18n?.t(source) ?? source;

const cockpitTopics=[
 {id:'prepared-launch',title:tr_web_cockpit_help_js('Reprendre le lancement préparé'),steps:[tr_web_cockpit_help_js('Une copie a été créée, mais le démarrage n’a pas été enregistré. La reprise conserve cette copie, la consigne, le fournisseur et les limites.'),tr_web_cockpit_help_js('Confirmez la reprise après examen des réglages. Le moteur vérifie à nouveau les dépendances, les budgets, le fournisseur et la disponibilité.'),tr_web_cockpit_help_js('Si la tâche ou sa révision Git a changé, la reprise est refusée et la copie reste conservée. N’effacez pas son contenu pour forcer un lancement.')],outcome:tr_web_cockpit_help_js('Une réponse perdue ou un double clic retrouve le même lancement. Le démarrage du fournisseur reste à confirmer dans son journal.')},
 {id:'attempt-extension',title:tr_web_cockpit_help_js('Autoriser une tentative supplémentaire'),steps:[tr_web_cockpit_help_js('Décrivez la cause et ce qui sera différent : preuve manquante, précondition corrigée ou travail partiel à reprendre.'),tr_web_cockpit_help_js('Le moteur ajoute une seule tentative, avec un maximum de trois. Les rapports, avis et limites d’outils sont conservés.'),tr_web_cockpit_help_js('Si l’état a changé, fermez puis rouvrez la décision. Un agent ou une revue en cours doit d’abord se terminer.')],outcome:tr_web_cockpit_help_js('L’autorisation ne lance personne et ne valide pas le résultat. Vérifiez ensuite le formulaire de lancement.')},
 {id:'connections',title:tr_web_cockpit_help_js('Ajouter son modèle et vérifier la connexion'),steps:[tr_web_cockpit_help_js('Dans IA et connexions, Ajouter une IA ouvre le formulaire de votre serveur ou fournisseur compatible. Saisissez son adresse de base et l’identifiant exact du modèle.'),tr_web_cockpit_help_js('Tester la connexion envoie une courte question, sans documents du projet. Une réponse confirme la connexion texte, pas les capacités de travail sur des fichiers ni tous les contrats JSON.'),tr_web_cockpit_help_js('Enregistrez, puis sélectionnez api-identifiant pour préparer ou piloter. Choisissez séparément un agent avec outils pour les exécutants.'),tr_web_cockpit_help_js('La clé reste dans un fichier local réservé à votre compte ; elle ne revient jamais dans les réponses de configuration. Pour changer de destination, renseignez explicitement la clé. Désactiver retire cette IA des prochains choix.')],outcome:tr_web_cockpit_help_js('Une connexion enregistrée ne lance aucun agent et ne change pas les agents déjà démarrés.')},
 {id:'planning',title:tr_web_cockpit_help_js('Confier le besoin et comprendre les décisions'),steps:[tr_web_cockpit_help_js('Sur une mission vide, choisissez le projet, le fournisseur et des contrôles qui démontrent chaque exigence. Le responsable propose des tâches ; il ne peut pas changer ces contrôles.'),tr_web_cockpit_help_js('Chaque tentative écrit dans sa copie du dépôt. Le contrôleur vérifie le résultat intégré avant acceptation. Les responsables reçoivent les retours et décident de la suite.'),tr_web_cockpit_help_js('Les budgets et la limite de deux tentatives restent appliqués. Une pause des décisions ne coupe pas les agents déjà actifs. Le nettoyage exige une mission suspendue et conserve preuves et copies en échec.')],outcome:tr_web_cockpit_help_js('Terminé signifie que les résultats sont vérifiés et que les responsables ont clos leurs périmètres. Le résultat Git est téléchargeable ; le dossier de départ reste intact.')},
 {id:'conduite',title:tr_web_cockpit_help_js('Ce que le moteur fait seul, et ce qu’il vous laisse'),steps:[tr_web_cockpit_help_js('Quand une tentative se termine en ayant produit un rapport lisible sous docs/, le conducteur le relaie : la tâche passe à soumise sans que vous transportiez le fichier. Sinon elle reste bloquée avec son motif.'),tr_web_cockpit_help_js('L’ordonnanceur lance les tâches prêtes dans les créneaux libres, avec le profil enregistré pour la tâche. Une dépendance non acceptée, un budget refusé ou une suspension l’arrêtent.'),tr_web_cockpit_help_js('Deux tentatives automatiques infructueuses sur une même tâche arrêtent les départs automatiques et créent une demande.')],outcome:tr_web_cockpit_help_js('Le contrôleur accepte automatiquement seulement avec des contrôles préautorisés couvrant les critères et des preuves actuelles. Sinon, la revue reste à vous. Un rapport soumis ne suffit pas à valider le résultat.')},
 {id:'autonomie',title:tr_web_cockpit_help_js('Régler l’autonomie et les créneaux'),steps:[tr_web_cockpit_help_js('Manuel : vous lancez et vous relayez. Assisté : le relais d’un rapport prouvé devient automatique. Autonome : les départs le deviennent aussi, dans la limite des créneaux.'),tr_web_cockpit_help_js('Les créneaux bornent le nombre de tentatives vivantes du travail. Un espace de travail déjà occupé ne reçoit pas un second départ.'),tr_web_cockpit_help_js('Suspendre les départs prime sur tout le reste, y compris le niveau autonome. Les tentatives déjà lancées continuent : suspendre n’arrête personne.')],outcome:tr_web_cockpit_help_js('Un changement de niveau ne s’applique pas rétroactivement : une tentative garde le niveau et les limites figés à son départ.')},
 {id:'traiter',title:tr_web_cockpit_help_js('Pourquoi cet écran vous sollicite'),steps:[tr_web_cockpit_help_js('À traiter ne contient que ce qui demande un arbitrage : rapport à examiner, gate bloquée, garde-fou déclenché, tentatives infructueuses, silence d’un agent, seuil de budget ou de coût dépassé.'),tr_web_cockpit_help_js('Un sujet ne donne qu’une carte. Une évaluation plus récente remplace la précédente, qui est close avec son motif plutôt que d’empiler le même texte.'),tr_web_cockpit_help_js('Acquitter une carte n’accepte pas la tâche et n’arrête aucun agent. Pour une gate bloquée, l’acquittement est refusé : il faut de nouvelles preuves.')],outcome:tr_web_cockpit_help_js('Une acceptation dont les preuves ont dérivé plus tard reste visible sur sa tâche sans réclamer de décision. Elle en redemande une dès qu’une tâche non terminée en dépend.')},
 {id:'fil',title:tr_web_cockpit_help_js('Savoir ce qui s’est passé en votre absence'),steps:[tr_web_cockpit_help_js('Le fil d’activité liste les événements du travail du plus récent au plus ancien. Chaque entrée dit qui a agi : le moteur, ou vous. Un liseré reprend cette origine et les entrées arrivées depuis votre visite sont surlignées ; la couleur redouble le mot, elle ne le remplace pas.'),tr_web_cockpit_help_js('Un trait marque votre dernière visite. Tout ce qui est au-dessus est arrivé depuis. Le repère est figé à l’ouverture pour ne pas glisser pendant la lecture.'),tr_web_cockpit_help_js('Décisions seulement ne garde que ce qu’un humain a tranché. Voir plus charge la suite ; le fil dit quand l’historique consultable s’arrête. Le fil se replie sur son titre, qui continue d’annoncer ce qui a changé ; l’état plié ou déplié est conservé d’une visite à l’autre.')],outcome:tr_web_cockpit_help_js('Une origine absente est lue comme humaine : le fil sous-déclare l’autonomie plutôt que de l’exagérer. Le compte du bandeau est borné aux entrées chargées et l’annonce comme un minimum.')},
 {id:'corrective-recovery',title:tr_web_cockpit_help_js('Un essai correctif après trois tentatives'),steps:[tr_web_cockpit_help_js('Relisez le refus indépendant et adaptez la correction proposée. Fermer conserve le plafond actuel et ne lance rien.'),tr_web_cockpit_help_js('La confirmation autorise exactement un quatrième essai. Swarm le prend en charge si la mission est active et si les conditions de lancement sont réunies.')],outcome:tr_web_cockpit_help_js('La pause, les budgets, les contrôles et la revue indépendante sont conservés. Aucun cinquième essai dans ce parcours.')},
 {id:'graphe',title:tr_web_cockpit_help_js('Lire le graphe du travail'),steps:[tr_web_cockpit_help_js('Un nœud par tâche, une arête par dépendance. Chaque nœud est teinté selon son état et une légende dit ce que chaque teinte signifie. L’état reste écrit en toutes lettres : la couleur ne porte jamais seule l’information. Une arête pleine marque une dépendance acceptée, une arête pointillée une dépendance encore en attente.'),tr_web_cockpit_help_js('Une tentative vivante s’attache à sa tâche avec son fournisseur, son action courante, ses appels d’outils et le coût rapporté.'),tr_web_cockpit_help_js('Signal perdu et terminé sont distincts : le premier dit qu’on ne sait plus, le second qu’on a vu la fin. Un nœud s’atteint au clavier et ouvre les actions de sa tâche.')],outcome:tr_web_cockpit_help_js('Un nœud en cours ne prouve pas qu’un processus tourne encore. Un coût inconnu s’écrit non rapporté, jamais 0,00 : ce serait faire passer l’inconnu pour une mesure.')},
 {id:'providers',title:tr_web_cockpit_help_js('Choisir le fournisseur et le niveau du modèle'),steps:[tr_web_cockpit_help_js('Dans Administration fournisseurs, ouvrez Configurer les niveaux. Associez un modèle à Simple, Standard et Exigeant, puis choisissez les défauts des travaux et de l’aide.'),tr_web_cockpit_help_js('Examinez la politique et confirmez son enregistrement. Les connexions et secrets restent gérés par la CLI. Exporter ou importer transporte seulement les politiques.'),tr_web_cockpit_help_js('Au lancement, Automatique applique le défaut de cet usage. Le modèle exact et son effort sont affichés avant confirmation et conservés avec la tentative.'),tr_web_cockpit_help_js('Exigeant demande un choix explicite. Un modèle absent ou refusé produit une erreur ; aucune montée en gamme automatique. Tester avec une question ouvre un aperçu avant tout appel.')],outcome:tr_web_cockpit_help_js('GLM sur site conserve le modèle configuré aux trois niveaux. Sans facture API déclarée ne signifie pas sans ressources : les limites de durée et d’outils restent actives.')},
 {id:'assistant',title:tr_web_cockpit_help_js('Comprendre la page avec l’assistant IA'),steps:[tr_web_cockpit_help_js('Choisissez un élément ciblé et un gabarit, puis Demander à l’IA sur cette page. Claude et Codex utilisent un lancement sans outils de code.'),tr_web_cockpit_help_js('Examinez les faits, la sélection, les omissions et le prompt exact avant de confirmer. Une question active indique son fournisseur, sa durée et son délai.'),tr_web_cockpit_help_js('Lisez les faits et leurs références, puis distinguez l’interprétation et les informations manquantes. Ouvrir le formulaire conserve les contrôles et la confirmation habituels.'),tr_web_cockpit_help_js('Une réponse périmée reste historique : reposer la question avant d’agir. Arrêter la question demande confirmation ; un redémarrage du cockpit conserve sa supervision.'),tr_web_cockpit_help_js('L’historique conserve les questions, réponses ou refus, contextes et versions. Son export JSON contient tous les échanges du travail. Le contexte reste consultable sans IA configurée.')],outcome:tr_web_cockpit_help_js('Une référence valide ne prouve pas que chaque phrase est vraie. Une question ne crée ni tâche de réalisation ni acceptation, et ne relance rien automatiquement.')},
 {id:'plan',title:tr_web_cockpit_help_js('Passer du brief au plan d’action'),steps:[tr_web_cockpit_help_js('Adoptez un brief puis Préparer le plan d’action avec l’IA. Examinez le contexte avant envoi.'),tr_web_cockpit_help_js('Dans la réponse, ouvrez Examiner le plan d’action. Corrigez les missions et répondez aux décisions ouvertes. Le moteur refuse les champs manquants, cycles et dépendances inconnues.'),tr_web_cockpit_help_js('Enregistrez les missions, puis pilotez-les dans Tâches. Les dépendances doivent être acceptées ; les plafonds de tentatives et d’outils sont appliqués.')],outcome:tr_web_cockpit_help_js('Le JSON est imposé à l’IA, mais la revue se fait dans un formulaire. Enregistrer le plan ne lance aucun worker.')},
 {id:'dialogue',title:tr_web_cockpit_help_js('Préparer une mission avec l’IA'),steps:[tr_web_cockpit_help_js('Dans Dialogue IA · APEX, exposez votre besoin ou préparez une demande RETEX.'),tr_web_cockpit_help_js('Choisissez le fournisseur, puis examinez le contexte : quatre échanges récents, brief adopté et pièces jointes.'),tr_web_cockpit_help_js('Confirmez l’envoi. Retrouvez ensuite la réponse et le contexte enregistré dans la conversation.')],outcome:tr_web_cockpit_help_js('Examiner le contexte ne lance rien. Seule la confirmation envoie le message.')},
 {id:'memory',title:tr_web_cockpit_help_js('Retrouver une ancienne décision'),steps:[tr_web_cockpit_help_js('Ouvrez la recherche dans le dialogue et saisissez un mot du sujet recherché.'),tr_web_cockpit_help_js('Lisez la réponse source, puis choisissez Joindre au prochain message.'),tr_web_cockpit_help_js('Vérifiez sa présence dans l’aperçu avant envoi. Les pièces jointes non envoyées sont vidées au changement de travail.')],outcome:tr_web_cockpit_help_js('L’historique conservé est plus large que le contexte transmis à chaque réponse.')},
 {id:'validation',title:tr_web_cockpit_help_js('Terminé ou accepté : que vérifier ?'),steps:[tr_web_cockpit_help_js('Terminé décrit le processus de l’agent. Lisez son rapport pour vérifier le résultat.'),tr_web_cockpit_help_js('Soumettez le rapport, puis examinez et enregistrez la gate de validation.'),tr_web_cockpit_help_js('Acceptez la tâche après revue. Une gate absente ou périmée exige de nouvelles preuves.')],outcome:tr_web_cockpit_help_js('Une tâche acceptée dispose d’une décision de revue. Un simple arrêt d’agent ne suffit pas.')},
 {id:'retex',title:tr_web_cockpit_help_js('Du RETEX à une leçon réutilisable'),steps:[tr_web_cockpit_help_js('Sous une réponse IA, examinez un RETEX : constat, proposition, risque, critère et preuves.'),tr_web_cockpit_help_js('Créez la tâche APEX, puis pilotez sa réalisation et sa validation. La création ne lance pas d’agent.'),tr_web_cockpit_help_js('Qualifiez le constat comme fait démontré et passez le RETEX à Vérifié. Examinez ensuite la leçon et l’index avant publication au Guide.')],outcome:tr_web_cockpit_help_js('Trois propositions maximum par réponse. Une hypothèse ne devient pas automatiquement une leçon.')},
 {id:'blocked',title:tr_web_cockpit_help_js('Un clic refuse l’action ou un agent attend'),steps:[tr_web_cockpit_help_js('Lisez le message dans la modale : révision modifiée, dépendance, budget, espace occupé ou preuve manquante.'),tr_web_cockpit_help_js('Pour une attente, ouvrez Agents et hiérarchie ou Activité, arrêt ou relance, puis consultez les journaux de la bonne tentative.'),tr_web_cockpit_help_js('Arrêtez seulement la tentative choisie si nécessaire. Après une nouvelle preuve, relancez explicitement ou consignez une OODA : observation, orientation, décision, action et résultat.')],outcome:tr_web_cockpit_help_js('Fermer une modale ou le cockpit ne coupe pas les agents. Une dérogation motivée ne transforme pas les tests en PASS.')},
 {id:'storage',title:tr_web_cockpit_help_js('Sauvegarde, export et limites'),steps:[tr_web_cockpit_help_js('Questions, réponses, contextes et fiches sont conservés dans la base locale Swarm.'),tr_web_cockpit_help_js('Exporter les échanges télécharge un Markdown. Exporter le RETEX écrit docs/retex/swarm/<identifiant>.md et indique son état sur la fiche.'),tr_web_cockpit_help_js('Les leçons publiées vont dans .claude/field-guide/. Une modification externe ou un dépassement du budget doit être résolu avant nouvelle publication.')],outcome:tr_web_cockpit_help_js('Une note exportée n’est pas automatiquement publiée au Guide ; la revue reste une étape distincte.')},
 {id:'budget',title:tr_web_cockpit_help_js('Lire les coûts sans confusion'),steps:[tr_web_cockpit_help_js('Budget et consommation distingue réservations, estimations et usages déclarés par le fournisseur.'),tr_web_cockpit_help_js('Les jetons et les durées ne sont pas une facture. Vérifiez la source et la date de toute estimation.'),tr_web_cockpit_help_js('Si un seuil bloque le lancement, examinez le budget et les tentatives réservées avant de modifier le plafond.')],outcome:tr_web_cockpit_help_js('Le score mesure les contrôles de qualité ; le budget mesure les ressources. Ils ne se remplacent pas.')},
 {id:'quotas',title:tr_web_cockpit_help_js('Plafonds de planification et de vérification'),steps:[tr_web_cockpit_help_js('Les plafonds propres aux sous-planificateurs restent inchangés. Les tentatives de production se réautorisent depuis leur tâche, avec une consigne corrective.'),tr_web_cockpit_help_js('Motif de la modification'),tr_web_cockpit_help_js('Prévisualiser les plafonds'),tr_web_cockpit_help_js('Autoriser ces plafonds')],outcome:tr_web_cockpit_help_js('Les consommations sont conservées. Cette modification ne lance aucun agent et ne valide aucun résultat. Une mission active pourra utiliser le nouveau plafond au prochain passage du conducteur.')},
 {id:'pricing',title:tr_web_cockpit_help_js('Tarifs des modèles'),steps:[tr_web_cockpit_help_js('Les tarifs sont propres à un fournisseur, un modèle et une devise. Indiquez leur source et leur date.'),tr_web_cockpit_help_js('Un champ vide signifie inconnu ; zéro signifie gratuit. Les volumes d’entrée hors cache et de cache doivent être distincts.'),tr_web_cockpit_help_js('Chaque modification crée une version conservée. Une estimation utilise une version précise et ne change pas les budgets des missions.')],outcome:tr_web_cockpit_help_js('Le résultat est une simulation, pas une facture. Les tentatives passées ne sont pas recalculées.')},
 {id:'lifecycle',title:tr_web_cockpit_help_js('Ranger ou nettoyer une mission sans surprise'),steps:[tr_web_cockpit_help_js('Archiver crée un ZIP exportable et conserve les données. Restaurer réactive une archive ou récupère la corbeille.'),tr_web_cockpit_help_js('Purger l’historique cible seulement les anciens journaux et sorties selon la durée choisie. Les preuves, reçus et fichiers restent exclus.'),tr_web_cockpit_help_js('Supprimer place les données internes dans une corbeille récupérable. Saisissez le nom exact, examinez les volumes et exclusions, puis confirmez.'),tr_web_cockpit_help_js('Un agent, un conducteur, une intention, un dialogue ou un contrôle actif produit un refus expliqué. Résolvez-le puis demandez un nouvel aperçu.')],outcome:tr_web_cockpit_help_js('Ouvrir l’action ou son aperçu ne modifie rien. Seule la seconde confirmation applique exactement l’aperçu courant.')}
];
function topicForAction(action){if(action==='task-model'||action==='role-model')return 'providers';if(action?.startsWith('pricing-'))return 'pricing';if(action==='authorize-recovery')return 'corrective-recovery';if(action==='resume-launch')return 'prepared-launch';if(action==='extend-attempt')return 'attempt-extension';if(action?.startsWith('planning'))return 'planning';if(['autonomy','dispatch','pause','unpause','profile'].includes(action))return 'autonomie';if(action==='ai-connection')return 'connections';if(action?.startsWith('provider-'))return 'providers';if(action?.startsWith('assist'))return 'assistant';if(action==='plan-review')return 'plan';if(action?.startsWith('retex'))return 'retex';if(['brainstorm','adopt-brief'].includes(action))return 'dialogue';if(['source-read','context-read'].includes(action))return 'memory';if(['stop','retry','reconcile','override','decision'].includes(action))return 'blocked';if(action==='quotas')return 'quotas';if(action==='budget')return 'budget';if(action?.startsWith('lifecycle'))return 'lifecycle';return 'validation'}
function topicCard(topic){const c=node('section',undefined,'help-card');c.dataset.topic=topic.id;c.append(node('h3',topic.title));const list=node('ol');topic.steps.forEach(t=>list.append(node('li',t)));c.append(list,node('p',topic.outcome,'help-outcome'));return c}
function decorateField(label,input,name){
 const wide=input.tagName==='TEXTAREA'||['path','workspace','action','context','agent','note','owner'].includes(name);label.classList.toggle('field-wide',wide);
 const hints={provider:tr_web_cockpit_help_js('Le fournisseur exécute cette tentative avec sa configuration existante.'),workspace:tr_web_cockpit_help_js('Répertoire du projet à examiner ou modifier pour cette mission.'),capture:tr_web_cockpit_help_js('Le journal détaillé est facultatif ; l’activité structurée reste visible.'),nature:tr_web_cockpit_help_js('Un fait exige une preuve consultable. Sinon, conservez Hypothèse.'),proof:tr_web_cockpit_help_js('Indiquez les fichiers ou résultats permettant de vérifier le constat.'),criteria:tr_web_cockpit_help_js('Décrivez un résultat observable, pas seulement une intention.'),instruction:tr_web_cockpit_help_js('Précisez le résultat attendu et les limites de la mission.'),risk:tr_web_cockpit_help_js('Ce qui peut mal se passer, et les limites de la proposition.')};
 if(name==='provider'&&modalContext?.action==='assist')hints.provider=tr_web_cockpit_help_js('Assistant de page : adaptateur Claude, Codex ou Skynet sans outils de code, dans un espace temporaire isolé.');
 if(name==='provider'&&modalContext?.action==='task-model')hints.provider=tr_web_cockpit_help_js('Modèle enregistré pour les prochains départs.');
 if(name==='provider'&&modalContext?.action==='pricing-save')hints.provider=tr_web_cockpit_help_js('Identifiant du fournisseur auquel ce tarif se rapporte. Aucun agent ne sera lancé.');
 if(hints[name]){const h=node('small',hints[name],'field-hint');h.id='hint-'+name;input.setAttribute('aria-describedby',h.id);label.append(h)}
}
function resetModalPresentation(){
 $('modal-rich').replaceChildren();$('modal-rich').hidden=true;$('modal-help').replaceChildren();$('modal-help').hidden=true;$('modal-help-toggle').hidden=false;$('modal-help-toggle').setAttribute('aria-expanded','false');$('cancel').textContent=tr_web_cockpit_help_js('Annuler');updateModalPresentation();
}
function updateModalPresentation(){
 if(!modalContext)return;const a=modalContext.action;
 $('modal').dataset.tone=['stop','override','assist-cancel'].includes(a)?'alert':['decision','retex-status'].includes(a)?'attention':['accepted','retex-guide','adopt-brief'].includes(a)?'success':'info';
 const staged=['brainstorm','gate','retex-guide','assist'].includes(a);$('modal-steps').hidden=!staged;
 if(staged){const reviewing=!!(modalContext.contextHash||modalContext.gatePreview||modalContext.digest);const signature=a+':'+reviewing;if($('modal-steps').dataset.signature!==signature){$('modal-steps').dataset.signature=signature;$('modal-steps').replaceChildren();[tr_web_cockpit_help_js('Préparer'),'Examiner',tr_web_cockpit_help_js('Confirmer')].forEach((title,i)=>{const li=node('li',title);const current=reviewing?2:0;if(i===current)li.setAttribute('aria-current','step');if(i<current)li.className='step-done';$('modal-steps').append(li)})}}
 $('action-form').setAttribute('aria-busy',String($('confirm').disabled));
}
$('modal-help-toggle').addEventListener('click',e=>{if(!e.isTrusted)return;const panel=$('modal-help'),open=panel.hidden;panel.hidden=!open;$('modal-help-toggle').setAttribute('aria-expanded',String(open));if(open){panel.replaceChildren(topicCard(cockpitTopics.find(t=>t.id===topicForAction(modalContext?.action))));panel.scrollIntoView({block:'nearest',behavior:'auto'})}});
function showCockpitHelp(initial=''){
 openModal(tr_web_cockpit_help_js('Bien utiliser le cockpit Swarm'),tr_web_cockpit_help_js('Retrouvez un parcours, comprenez un état et identifiez la prochaine action.'),{action:'help'});$('confirm').hidden=true;$('cancel').textContent=tr_web_cockpit_help_js('Fermer l’aide');$('modal-help-toggle').hidden=true;$('modal-rich').hidden=false;
 const label=node('label',tr_web_cockpit_help_js('Rechercher dans l’aide'),'help-search'),input=node('input');input.type='search';input.id='help-search';label.htmlFor=input.id;input.placeholder=tr_web_cockpit_help_js('Exemple : gate, reprise, RETEX, budget');label.append(input);const state=node('p','',undefined);state.id='help-results-state';state.setAttribute('role','status');const grid=node('div',undefined,'help-grid');$('modal-rich').append(label,state,grid);
 function filter(){grid.replaceChildren();const q=input.value.toLocaleLowerCase('fr');const found=cockpitTopics.filter(t=>(t.title+' '+t.steps.join(' ')+' '+t.outcome).toLocaleLowerCase('fr').includes(q));found.forEach(t=>grid.append(topicCard(t)));state.textContent=found.length?found.length+tr_web_cockpit_help_js(' rubrique(s) disponible(s).'):tr_web_cockpit_help_js('Aucune rubrique. Essayez « autonomie », « conducteur », « fil », « gate » ou « budget ».')}
 input.addEventListener('input',filter);input.value=initial;filter();input.focus();
}
$('brain-help').addEventListener('click',e=>{if(e.isTrusted)showCockpitHelp('')});
new MutationObserver(updateModalPresentation).observe($('confirm'),{attributes:true,childList:true,subtree:true});
new MutationObserver(()=>{if(!$('modal-error').hidden){$('modal-error').scrollIntoView({block:'nearest'});$('modal-error').focus()}}).observe($('modal-error'),{attributes:true,attributeFilter:['hidden']});
// Search controls consume Escape to clear themselves by default. Keep the
// dialog contract predictable: Escape always closes and restores the opener.
$('modal').addEventListener('keydown',e=>{if(e.isTrusted&&e.key==='Escape'){e.preventDefault();e.stopPropagation();closeModal()}},true);
