const tr_web_planning_js = source => globalThis.SwarmI18n?.t(source) ?? source;
/* The ownership tree describes responsibility, separately from task dependencies. */
const Planning = {
 labels:{ready:tr_web_planning_js('Prêt à décider'),waiting:tr_web_planning_js('Attend un retour'),closed:tr_web_planning_js('Terminé et vérifié'),active:tr_web_planning_js('Décision en cours')},
 async change(action,extra={}){const context=modalContext;return api('/api/v1/planning?work='+encodeURIComponent(context.workID)+'&action='+action,{schema_version:1,event_id:crypto.randomUUID(),expected_revision:context.revision,...extra})},
 render(host){
  const p=snapshot.work.planning;
  if(!p){if(!snapshot.work.tasks.length)host.append(Pilot.command(tr_web_planning_js('Confier ce besoin à une équipe autonome'),()=>this.enable()));return}
  const panel=node('section',undefined,'planning-panel');panel.id='planning-ownership';panel.append(node('h4',tr_web_planning_js('L’équipe : qui décide, qui réalise, qui vérifie')));
  this.roles(panel,p);
  panel.append(node('h4',tr_web_planning_js('Responsables et décisions')));
  panel.append(node('p',p.failure|| (p.activations>=p.max_activations||p.decisions>=p.max_decisions?tr_web_planning_js('Plafond de planification atteint. Examinez les décisions pour préparer la suite.'):p.paused?tr_web_planning_js('La planification est en pause.'):p.scopes.every(s=>s.state==='closed')?tr_web_planning_js('Tous les périmètres sont terminés et vérifiés.'):tr_web_planning_js('Les responsables décident de la suite à partir des retours des agents.')),p.failure?'notice alert':'notice info'));
  if(p.model_route)panel.append(node('p',tr_web_planning_js('IA du responsable : ')+p.provider+' · '+p.model_route.model+(p.model_route.effort?tr_web_planning_js(' · effort ')+p.model_route.effort:'')));
  panel.append(node('p',`${p.decisions}/${p.max_decisions}${tr_web_planning_js(' décisions · ')}${p.activations}/${p.max_activations}${tr_web_planning_js(' appels IA · ')}${snapshot.work.tasks.length}/${p.max_tasks}${tr_web_planning_js(' tâches')}`));
  const tree=node('ul',undefined,'planning-tree');const add=(parent,list)=>{for(const s of p.scopes.filter(x=>(x.parent||'')===parent)){const item=node('li');const role=node('p',s.parent?tr_web_planning_js('⑂ Responsable de branche · IA'):tr_web_planning_js('◇ Responsable de mission · IA'),'pilot-role');role.dataset.tone=s.parent?'attention':'info';item.append(role);item.append(node('strong',s.id==='root'?snapshot.work.title:s.objective.split('\n')[0]),node('p',(p.paused?tr_web_planning_js('Suspendu'):s.holder?tr_web_planning_js('Décision en cours'):this.labels[s.state]||s.state)+' · '+s.requirements.length+tr_web_planning_js(' exigence(s) · ')+p.inbox.filter(e=>e.scope===s.id&&!e.decision).length+tr_web_planning_js(' retour(s) à traiter')));const children=node('ul');add(s.id,children);if(children.childNodes.length)item.append(children);list.append(item)}};add('',tree);panel.append(tree);
  panel.append(node('p',p.human_review_authorized?tr_web_planning_js('Vérification : revue humaine autorisée. Chaque résultat attend votre acceptation ; le responsable ne peut pas le valider lui-même.'):tr_web_planning_js('Vérification : avis IA indépendant puis contrôles du moteur selon la politique de chaque tâche.'),'notice info'));
  panel.append(Pilot.command(tr_web_planning_js('Comprendre les décisions'),()=>this.details()));
  panel.append(Pilot.command(p.paused||p.failure?tr_web_planning_js('Reprendre la planification'):tr_web_planning_js('Suspendre la planification'),()=>this.resume(p.paused||p.failure?'resume':'pause')));
  if(p.repository){panel.append(node('p',(p.repository.candidate_commit===p.repository.base_commit?tr_web_planning_js('Révision de départ : '):tr_web_planning_js('Révision vérifiée : '))+p.repository.candidate_commit.slice(0,12)),node('p',tr_web_planning_js('Chaque tentative travaille dans sa copie. Le résultat est conservé dans le dépôt de la mission.')));const a=node('a',tr_web_planning_js('Télécharger le résultat Git'));a.href='/api/v1/planning-bundle?work='+encodeURIComponent(work);a.download='swarm-result.bundle';panel.append(a,Pilot.command(tr_web_planning_js('Nettoyer les copies déjà intégrées'),()=>this.cleanup()))}
  host.append(panel);
 },
 roles(panel,p){
  const flow=node('div',undefined,'team-role-flow');flow.setAttribute('aria-label',tr_web_planning_js('Organisation : responsable, exécutants, vérificateur'));
  const card=(role,title,description,tone)=>{const box=node('section',undefined,'team-role-card');box.dataset.role=role;box.dataset.tone=tone;box.append(node('h5',title),node('p',description));return box};
  const manager=card('planner',tr_web_planning_js('◇ Responsable · ')+p.provider,`${snapshot.paused?tr_web_planning_js('Mission en pause. '):''}${p.decisions}${tr_web_planning_js(' décision(s) enregistrée(s). Décompose le besoin et traite les retours.')}`,'info');
  const workers=card('worker',tr_web_planning_js('⚙ Exécutants'),`${snapshot.work.tasks.length}${tr_web_planning_js(' tâches de production. Réalisent les livrables ; ne valident pas leur propre résultat.')}`,'attention');
  const reviewer=card('reviewer',p.reviewer?tr_web_planning_js('✓ Vérificateur indépendant · ')+p.reviewer.provider:tr_web_planning_js('! Vérificateur indépendant absent'),p.reviewer?`${snapshot.paused?tr_web_planning_js('Mission en pause. '):snapshot.work.tasks.some(t=>t.independent_review?.state==='running')?tr_web_planning_js('Examen en cours. '):tr_web_planning_js('Attend un résultat à examiner. ')}${tr_web_planning_js('Session IA distincte, sans outils de modification. ')}${p.reviewer.calls}/${p.reviewer.max_calls}${tr_web_planning_js(' appels utilisés. Examine chaque résultat avant son acceptation.')}`:(p.reviewer_required?tr_web_planning_js('Organisation incomplète : lancement autonome refusé.'):p.repository?tr_web_planning_js('Contrôleur moteur : tests et intégration Git. Aucune revue IA indépendante.'):tr_web_planning_js('Mission historique : revue humaine ou contrôles enregistrés ; aucun vérificateur IA.')),p.reviewer?'succes':'attention');
  if(p.reviewer?.failure)reviewer.append(node('p',p.reviewer.failure,'notice alert'));
  for(const item of [manager,workers,reviewer]){if(flow.childNodes.length){const arrow=node('span','→','team-role-arrow');arrow.setAttribute('aria-hidden','true');flow.append(arrow)}flow.append(item)}
  panel.append(flow,node('p',tr_web_planning_js('Le vérificateur donne un avis motivé. Les contrôles requis et la décision humaine éventuelle restent obligatoires.')));
  const reviews=snapshot.work.tasks.filter(t=>t.independent_review);
  for(const t of reviews){const r=t.independent_review,state=r.state==='passed'&&snapshot.independent_reviews?.[t.id]?.current===false?'stale':r.state,labels={running:tr_web_planning_js('Examen en cours'),passed:tr_web_planning_js('Avis favorable'),changes_requested:tr_web_planning_js('Corrections ou preuves demandées'),error:tr_web_planning_js('Vérification interrompue'),stale:tr_web_planning_js('Avis périmé')};const box=node('section',undefined,'mission-task');box.append(node('h5','✓ '+t.title+' — '+(labels[state]||state)),node('p',state==='stale'?(snapshot.independent_reviews?.[t.id]?.reason||r.reason):r.reason));box.append(Pilot.command(tr_web_planning_js('Lire la vérification'),()=>{openModal(tr_web_planning_js('Vérification indépendante — ')+t.title,r.reason,{action:'help'});$('confirm').hidden=true;$('cancel').textContent=tr_web_planning_js('Fermer');for(const c of r.criteria||[])$('modal-fields').append(node('p',`${tr_web_planning_js('Critère ')}${c.index} : ${c.verdict==='pass'?tr_web_planning_js('preuve présente'):c.verdict==='fail'?tr_web_planning_js('non satisfait'):tr_web_planning_js('preuve insuffisante')} — ${c.evidence}`));}));if(['error','stale'].includes(r.state)&&t.status==='submitted')box.append(Pilot.command(tr_web_planning_js('Reprendre la vérification'),()=>{openModal(tr_web_planning_js('Reprendre la vérification'),tr_web_planning_js('Un nouvel appel utilisera le budget restant. Décrivez ce qui a changé depuis l’incident.'),{action:'planning-control',planningAction:'retry-review',reviewTask:t.id});field('planning-reason',tr_web_planning_js('Correction apportée'),'',null,true);$('confirm').textContent=tr_web_planning_js('Enregistrer la reprise');}));for(const [i,b]of [...box.querySelectorAll('button')].entries()){b.id='review-'+(i?'retry-':'read-')+t.id;b.dataset.missionAction=b.id}panel.append(box)}
 },
 inspectRole(kind){
  if(kind==='planner'){this.details();return}
  openModal(tr_web_planning_js('Vérificateur indépendant'),tr_web_planning_js('Examine les rapports dans une session distincte. Les tests requis et la validation humaine éventuelle restent obligatoires.'),{action:'help'});$('confirm').hidden=true;$('cancel').textContent=tr_web_planning_js('Fermer');
  const tasks=snapshot.work.tasks.filter(t=>t.independent_review);
  if(!tasks.length)$('modal-fields').append(node('p',snapshot.work.planning?.reviewer?tr_web_planning_js('Aucun avis pour le moment. Le vérificateur attend un rapport issu d’une tentative terminée.'):tr_web_planning_js('Cette mission ne dispose pas de vérificateur IA indépendant.')));
  for(const t of tasks)$('modal-fields').append(node('h4',t.title),node('p',t.independent_review.reason));
 },
 enable(){
  openModal(tr_web_planning_js('Confier le besoin à une équipe autonome'),tr_web_planning_js('Les responsables décomposent le besoin ; les agents réalisent les tâches dans des copies du dépôt. Les contrôles ci-dessous déterminent seuls la validation automatique.'),{action:'planning-enable'});
  field('planning-provider',tr_web_planning_js('IA chargée de planifier'),'', [['',tr_web_planning_js('Choisir…')],...Object.keys(snapshot.providers?.providers||{}).map(x=>[x,x])]);
  addModelFields('planning', ()=>$('field-planning-provider').value);
  field('planning-repository',tr_web_planning_js('Dossier du projet dans son dépôt Git'),snapshot.root);
  field('planning-base',tr_web_planning_js('Point de départ'),'commit',[['commit',tr_web_planning_js('Dernier commit enregistré')],['snapshot',tr_web_planning_js('Inclure aussi les fichiers sélectionnés')]]);
  const files=field('planning-files',tr_web_planning_js('Fichiers modifiés à inclure — un chemin par ligne'),'',null,true);files.parentElement.hidden=true;$('field-planning-base').addEventListener('change',()=>{files.parentElement.hidden=$('field-planning-base').value!=='snapshot'});
  field('planning-tasks',tr_web_planning_js('Maximum de tâches'),'20');field('planning-calls',tr_web_planning_js('Maximum d’appels de planification'),'40');
  const criteria=snapshot.work.criteria||[];
  criteria.forEach((text,i)=>{const box=node('section',undefined,'planning-setup-criterion');box.append(node('h4',tr_web_planning_js('Exigence ')+(i+1)),node('p',text));$('modal-fields').append(box);field('planning-command-'+i,tr_web_planning_js('Programme de contrôle'),'git',[['git','git'],['go','go'],['node','node'],['python3','python3'],['pytest','pytest'],['npm','npm']]);field('planning-args-'+i,tr_web_planning_js('Arguments exacts — un par ligne'),'',null,true);field('planning-why-'+i,tr_web_planning_js('Comment ce contrôle prouve l’exigence'),'',null,true);for(const name of ['command','args','why'])box.append($('field-planning-'+name+'-'+i).parentElement)});
  $('modal-fields').append(node('p',tr_web_planning_js('Choisissez des tests qui démontrent chaque exigence. Les fichiers non sélectionnés et non enregistrés dans Git sont exclus du point de départ. Après activation, les réglages de mission permettent de lancer les agents.'),'notice info'));
  $('confirm').textContent=tr_web_planning_js('Activer cette organisation');
 },
 async submit(){const f=Object.fromEntries(new FormData($('action-form'))),checks={};(snapshot.work.criteria||[]).forEach((text,i)=>{checks['req-'+(i+1)]=[{id:'requirement-'+(i+1),command:[f['planning-command-'+i],...f['planning-args-'+i].split('\n').filter(Boolean)],criteria:[1],justification:f['planning-why-'+i],dir:'.',timeout_seconds:60}]});await this.change('enable',{provider:f['planning-provider'],level:f.level,model_policy_hash:f.model_policy_hash,max_tasks:Number(f['planning-tasks']),max_decisions:Number(f['planning-calls']),max_activations:Number(f['planning-calls']),repository:{path:f['planning-repository'],committed_only:f['planning-base']==='commit',include_dirty:f['planning-base']==='snapshot'?f['planning-files'].split('\n').filter(Boolean):[]},checks});closeModal();await refresh(true);Mission.open(true)},
 resume(action){openModal(action==='pause'?tr_web_planning_js('Suspendre les décisions'):tr_web_planning_js('Reprendre les décisions'),tr_web_planning_js('La reprise conserve les limites et les preuves. Indiquez ce qui a été corrigé si la planification était bloquée.'),{action:'planning-control',planningAction:action});field('planning-reason','Motif',action==='pause'?tr_web_planning_js('Pause demandée'):'',null,true);$('confirm').textContent=action==='pause'?'Suspendre':'Reprendre'},
 async submitControl(){await this.change(modalContext.planningAction,{reason:$('field-planning-reason').value,...(modalContext.reviewTask?{task_id:modalContext.reviewTask}:{})});closeModal();await refresh(true)},
 async cleanup(){openModal(tr_web_planning_js('Nettoyer les copies intégrées'),tr_web_planning_js('Les résultats Git, rapports et preuves restent conservés. Les copies en échec restent disponibles pour examen. La mission doit être en pause et sans agent actif.'),{action:'planning-cleanup'});$('confirm').disabled=true;const context=modalContext;try{const v=await api('/api/v1/planning-cleanup?work='+encodeURIComponent(work),{schema_version:1,expected_revision:snapshot.work.revision});if(context!==modalContext)return;context.cleanup=v;$('modal-fields').append(node('p',v.paths.length+tr_web_planning_js(' copie(s) · ')+Math.ceil(v.bytes/1024)+tr_web_planning_js(' Kio à libérer')));$('confirm').disabled=!v.paths.length;$('confirm').textContent=tr_web_planning_js('Supprimer ces copies intégrées')}catch(e){$('modal-error').hidden=false;$('modal-error').textContent=e.message}},
 async submitCleanup(){const v=modalContext.cleanup;await api('/api/v1/planning-cleanup?work='+encodeURIComponent(work)+'&apply=true',{schema_version:1,expected_revision:v.revision,preview_token:v.preview_token});closeModal();notice(tr_web_planning_js('Copies intégrées supprimées ; livraison et preuves conservées.'));await refresh(true)},
 async details(){openModal(tr_web_planning_js('Décisions et retours de l’équipe'),tr_web_planning_js('Un retour traité est relié à une décision enregistrée. Les résultats doivent encore être validés par les contrôles.'),{action:'help'});$('confirm').hidden=true;$('cancel').textContent=tr_web_planning_js('Fermer');const context=modalContext,host=$('modal-fields'),pending=snapshot.work.planning.inbox;const loading=node('p',tr_web_planning_js('Lecture des décisions enregistrées…'));host.append(loading);try{const history=await api('/api/v1/planning-history?work='+encodeURIComponent(work));if(modalContext!==context)return;loading.remove();for(const d of history.reverse()){const box=node('section',undefined,'mission-task');box.append(node('h4',tr_web_planning_js('Décision du responsable ')+d.scope),node('p',d.reason),node('p',new Date(d.at).toLocaleString()));for(const op of d.operations)box.append(node('p',({task:tr_web_planning_js('Créer la tâche'),delegate:tr_web_planning_js('Confier au responsable'),retry:tr_web_planning_js('Reprendre la tâche'),close:tr_web_planning_js('Clore le périmètre')}[op.kind]||op.kind)+' : '+(op.title||op.id||d.scope)));host.append(box)}}catch(e){loading.textContent=tr_web_planning_js('Décisions indisponibles : ')+e.message}if(modalContext!==context)return;for(const e of [...pending].reverse()){const box=node('section',undefined,'mission-task');box.append(node('h4',e.task||e.scope),node('p',e.message),node('p',(e.decision?tr_web_planning_js('Traité'):tr_web_planning_js('À traiter'))+' · '+new Date(e.at).toLocaleString()));$('modal-fields').append(box)}}
};
