'use strict';
const tr_web_plan_js = source => globalThis.SwarmI18n?.t(source) ?? source;

let plansRenderKey='';
function prepareActionPlan(){
 if(!snapshot.work.planning_brief){notice(tr_web_plan_js('Adoptez d’abord un brief.'),true);return}
 openModal(tr_web_plan_js('Préparer le plan d’action avec l’IA'),tr_web_plan_js('L’IA doit respecter le cadre structuré. Vous relirez les missions avant leur ajout au plan. Aucun worker ne sera lancé.'),{action:'brainstorm',launchEvent:crypto.randomUUID(),planBriefHash:snapshot.work.planning_brief.sha256});
 field('provider',tr_web_plan_js('IA qui prépare le plan'),'',Object.keys(snapshot.providers?.providers||{}).map(k=>[k,k]));field('workspace',tr_web_plan_js('Espace à examiner'),snapshot.root);field('instruction',tr_web_plan_js('Précisions pour le plan'),tr_web_plan_js('Transforme le brief adopté en plan d’action conforme au cadre JSON obligatoire fourni par le moteur. Décompose les missions, leurs dépendances et leurs preuves. Laisse les décisions non résolues à l’opérateur. Ne réalise aucune mission.'),null,true);field('capture',tr_web_plan_js('Capture détaillée'),'false',[['false',tr_web_plan_js('Désactivée')],['true',tr_web_plan_js('Activée')]]);addModelFields('brainstorm');$('confirm').textContent=tr_web_plan_js('Examiner le contexte');
}
function renderPlans(){
 const key=JSON.stringify([work,snapshot.work.plans,snapshot.work.tasks.map(t=>[t.id,t.title,t.status,snapshot.validation?.tasks[t.id]?.state])]);if(key===plansRenderKey)return;plansRenderKey=key;const target=$('action-plans');target.replaceChildren();
 for(const plan of snapshot.work.plans||[]){const box=node('section',undefined,'card');box.append(node('h3',plan.spec.objective),node('p',tr_web_plan_js('Plan enregistré le ')+plan.at+' · '+plan.task_ids.length+tr_web_plan_js(' missions. Les dépendances doivent être acceptées avant lancement.')));for(const id of plan.task_ids){const t=snapshot.work.tasks.find(x=>x.id===id);if(!t)continue;const row=node('div',undefined,'plan-task-line');row.append(node('span',t.title),badge(snapshot.validation?.tasks[t.id]?.state||t.status),button(tr_web_plan_js('Piloter cette mission'),()=>taskDialog(id)));box.append(row)}target.append(box)}
}
async function reviewActionPlan(task){
 openModal(tr_web_plan_js('Examiner le plan d’action'),tr_web_plan_js('Chargement du plan structuré…'),{action:'plan-review',task:task.id});$('confirm').hidden=true;
 try{const review=await act('plan-read',{task:task.id});if(!modalContext||modalContext.task!==task.id)return;modalContext.plan=review;$('modal-description').textContent=tr_web_plan_js('Relisez les périmètres, gates et plafonds. Répondez aux décisions ouvertes. L’enregistrement crée les tâches et leurs dépendances, sans les lancer.');drawPlanEditor(review.spec);$('confirm').hidden=false;$('confirm').textContent=tr_web_plan_js('Enregistrer les missions dans le plan');}
 catch(e){if(modalContext?.task!==task.id)return;$('modal-error').textContent=e.message+tr_web_plan_js(' Aucune mission créée. Fermez cette fenêtre puis utilisez Préparer le plan d’action pour demander une réponse conforme.');$('modal-error').hidden=false;}
}
function drawPlanEditor(spec){
 $('modal-fields').replaceChildren();const intro=node('section',undefined,'plan-editor');intro.append(node('h3',tr_web_plan_js('Objectif et décisions')));
 function input(parent,name,label,value,options=null,multi=false){const e=field(name,label,value,options,multi);parent.append(e.parentElement);return e}
 const objective=input(intro,'plan-objective',tr_web_plan_js('Objectif du plan'),spec.objective,null,true),assumptions=input(intro,'plan-assumptions',tr_web_plan_js('Hypothèses explicites — une par ligne'),spec.assumptions.join('\n'),null,true);
 const questions=spec.questions.map((q,i)=>({question:q.question,input:input(intro,'plan-question-'+i,tr_web_plan_js('Décision à résoudre : ')+q.question,q.answer,null,true)}));$('modal-fields').append(intro);
 const groups=node('div',undefined,'plan-missions');$('modal-fields').append(groups);const missions=[];
 function addMission(t){const box=node('details',undefined,'plan-mission');box.open=true;const summary=node('summary',t.id+' · '+t.title),body=node('div',undefined,'plan-editor');box.append(summary,body);const fields={};
 for(const [key,label]of [['id',tr_web_plan_js('Identifiant local')],['title',tr_web_plan_js('Titre de la mission')],['scope',tr_web_plan_js('Périmètre et exclusions')],['deliverable',tr_web_plan_js('Livrable attendu')],['criteria',tr_web_plan_js('Critères observables — un par ligne')],['depends',tr_web_plan_js('Dépendances — identifiants séparés par des virgules')],['proof',tr_web_plan_js('Preuves attendues')],['entry',tr_web_plan_js('Gate entry — prérequis')],['validation',tr_web_plan_js('Gate validation — vérifications')],['delivery',tr_web_plan_js('Gate delivery — conditions de livraison')],['stop',tr_web_plan_js('Conditions d’arrêt et OODA')]]){let v=t[key];if(Array.isArray(v))v=v.join(key==='depends'?', ':'\n');fields[key]=input(body,'mission-'+missions.length+'-'+key,label,v,null,['scope','criteria','proof','entry','validation','delivery','stop'].includes(key))}
 fields.role=input(body,'mission-'+missions.length+'-role',tr_web_plan_js('Rôle'),t.role,[['worker',tr_web_plan_js('Worker — réalise')],['planner',tr_web_plan_js('Planner — planifie')],['subplanner',tr_web_plan_js('Subplanner — planifie un sous-périmètre')]]);
 for(const [key,label,max]of [['max_attempts',tr_web_plan_js('Tentatives maximum'),3],['max_tool_calls',tr_web_plan_js('Appels d’outils maximum par tentative'),100]]){fields[key]=input(body,'mission-'+missions.length+'-'+key,label,String(t[key]));fields[key].type='number';fields[key].min='1';fields[key].max=String(max)}
 const record={box,fields};missions.push(record);body.append(button(tr_web_plan_js('Retirer cette mission'),()=>{box.remove();record.removed=true}));groups.append(box);
 }
 spec.tasks.forEach(addMission);
 $('modal-fields').append(button(tr_web_plan_js('Ajouter une mission'),()=>{if(missions.filter(m=>!m.removed).length>=8){$('modal-error').textContent=tr_web_plan_js('Huit missions maximum par plan.');$('modal-error').hidden=false;return}addMission({id:'T'+(missions.length+1),title:tr_web_plan_js('Nouvelle mission'),role:'worker',scope:'',deliverable:'',criteria:[],depends:[],proof:'',entry:'',validation:'',delivery:'',stop:tr_web_plan_js('Deux corrections maximum puis OODA et arrêt sur blocage.'),max_attempts:2,max_tool_calls:30})}));
 modalContext.collectPlan=()=>({version:1,objective:objective.value,assumptions:assumptions.value.split('\n').map(v=>v.trim()).filter(Boolean),questions:questions.map(q=>({question:q.question,answer:q.input.value})),tasks:missions.filter(m=>!m.removed).map(({fields})=>{const t={};for(const [k,e]of Object.entries(fields))t[k]=e.value;t.depends=t.depends.split(',').map(v=>v.trim()).filter(Boolean);t.criteria=t.criteria.split('\n').map(v=>v.trim()).filter(Boolean);t.max_attempts=Number(t.max_attempts);t.max_tool_calls=Number(t.max_tool_calls);return t})});
}
async function submitActionPlan(c){const spec=c.collectPlan();await act('plan-commit',{plan:{...c.plan,spec}});closeModal();await refresh();notice(tr_web_plan_js('Plan enregistré : ')+spec.tasks.length+tr_web_plan_js(' missions ajoutées avec leurs dépendances. Sélectionnez une mission pour la lancer.'));showView('tasks');$('action-plans').scrollIntoView({block:'start'});}
