const tr_web_prephase_js = source => globalThis.SwarmI18n?.t(source) ?? source;
import {PreparationMissions} from './prephase-missions.js';
import {PreparationResources} from './prephase-resources.js';
import {PreparationConversion} from './prephase-conversion.js';
import {PreparationDecisions} from './prephase-decisions.js';
import {PreparationDialogue} from './prephase-dialogue.js';
import {PreparationEditor} from './prephase-editor.js';
const $=id=>document.getElementById(id),names={besoin:tr_web_prephase_js('Besoin'),brief:'Brief',plan:tr_web_prephase_js('Plan JSON')};
let csrf='',session=null,kind='besoin',dirty=false,saving=false,timer=null,pending=null,conflict=null,baseText='',methods=[],historyBefore=0,createPending=null,openGeneration=0,editEpoch=0;
const editor=new PreparationEditor(changed);
const dialogue=new PreparationDialogue(api,async()=>{if(dirty||pending){if(!await save())return null;}return saving||conflict?null:session;},async (turn,adopt=false)=>{
 if(saving||dirty||pending||conflict||session?.id!==turn.preparation_id||session.revision!==turn.source_revision)throw new Error(tr_web_prephase_js('Documents modifiés : demandez une proposition actualisée.'));
 saving=true;const epoch=editEpoch;try{const p=await api('preparations/command',request('use-proposal',{turn_id:turn.id,...(adopt?{adopt_brief:true}:{})}));session=p;if(editEpoch!==epoch){message(tr_web_prephase_js('Proposition enregistrée. Votre saisie locale reste dans l’éditeur ; enregistrez-la séparément.'));return;}kind=turn.target==='plan'?'plan':'brief';editor.open(p.id+'/'+kind,kind,p.documents[kind].text);baseText=editor.value();dirty=false;state(kind==='plan'?tr_web_prephase_js('Proposition enregistrée — plan à vérifier'):adopt?tr_web_prephase_js('Brief validé — vous pouvez proposer le plan'):tr_web_prephase_js('Proposition enregistrée — brief à adopter'));context();}finally{saving=false;}
});
const decisions=new PreparationDecisions(api,async()=>{if((dirty||pending)&&!await save())return null;return saving||conflict?null:session;},p=>{session=p;kind='plan';editor.open(p.id+'/plan','plan',p.documents.plan.text);baseText=editor.value();dirty=false;context();state(tr_web_prephase_js('Décisions enregistrées — plan à vérifier'));message('');});
const conversion=new PreparationConversion(api,async()=>{if((dirty||pending)&&!await save())return null;if(decisions.hasDraft())throw new Error(tr_web_prephase_js('Enregistrez les décisions en cours ou abandonnez leur saisie avant de créer les missions.'));return saving||conflict?null:session;},p=>{if(session?.id===p.id){session=p;context();state(tr_web_prephase_js('Missions enregistrées'));}});
const missions=new PreparationMissions(async()=>{if((dirty||pending)&&!await save())return null;return saving||conflict?null:session;},async(source,text)=>{if(saving||conflict||session?.id!==source.id||session.revision!==source.revision)throw Error(tr_web_prephase_js('La préparation a changé. Fermez puis rouvrez les missions pour comparer la version courante.'));if(dirty||pending)throw Error(tr_web_prephase_js('Enregistrez votre texte avant de modifier les missions.'));saving=true;try{session=await api('preparations/command',request('save',{document:'plan',text}));kind='plan';editor.open(session.id+'/plan','plan',text);baseText=text;dirty=false;context();state(tr_web_prephase_js('Brouillon enregistré — plan à vérifier'));}finally{saving=false;}});
const resources=new PreparationResources(api,async()=>{if((dirty||pending)&&!await save())return null;return saving||conflict?null:session;},async r=>{if(saving||conflict)throw new Error(tr_web_prephase_js('Un enregistrement est déjà en cours.'));saving=true;try{const p=await api('preparations/command',r);if(p.receipt_historical){await showConflict();const e=new Error(tr_web_prephase_js('Enregistrement retrouvé, mais une version plus récente existe. Actualisez les documents.'));e.status=409;throw e;}session=p;context();state(tr_web_prephase_js('Enregistré · révision ')+p.revision);}finally{saving=false;if(dirty&&!pending&&!conflict)timer=setTimeout(()=>save(),750);}});
const on=(id,event,fn)=>$(id).addEventListener(event,e=>{if(e.isTrusted)fn(e)});
function message(text){$('error').textContent=text;$('error').hidden=!text;}
function state(text,tone='success'){$('save-state').textContent=text;$('save-state').className='status '+tone;}
async function api(path,data){const opts={signal:AbortSignal.timeout(15000),headers:{}};if(data){opts.method='POST';opts.headers={'Content-Type':'application/json','X-Swarm-CSRF':csrf};opts.body=JSON.stringify(data)}const r=await fetch('/api/v1/'+path,opts);let value;try{value=await r.json()}catch{const e=new Error(tr_web_prephase_js('Session indisponible : rouvrez le lien de session du serveur.'));e.status=r.status;throw e}if(!r.ok){const e=new Error((globalThis.SwarmI18n?.engine(value.error)??value.error)||tr_web_prephase_js('Action refusée.'));e.status=r.status;e.code=value.code;throw e}return value;}
function request(action,extra={}){return {version:1,action,preparation_id:session.id,event_id:crypto.randomUUID(),expected_revision:session.revision,...extra};}
function changed(){editEpoch++;dirty=true;state(tr_web_prephase_js('Modifications non enregistrées'),'attention');updateSize();actionState();clearTimeout(timer);if(!pending&&!conflict)timer=setTimeout(()=>save(),750);}
function updateSize(){if(session){$('plan-template').hidden=kind!=='plan';$('plan-template').disabled=!!editor.value().trim();}const n=new TextEncoder().encode(editor.value()).length;$('size').textContent=n+tr_web_prephase_js(' / 16 000 octets');if(n>16000)state(tr_web_prephase_js('Document trop long — non enregistré'),'alert');}
function briefCurrent(){return !!(session?.adopted_brief&&session.documents.brief&&session.adopted_brief.sha256===session.documents.brief.sha256&&session.adopted_brief.need_hash===session.documents.besoin?.sha256);}
function actionState(){
 if(!session)return;const action=conflict?'compare':dirty||pending?'save':session.plan_ready&&(!session.conversion||session.documents.plan.sha256!==session.conversion.plan_hash)?'convert':session.conversion&&kind==='plan'&&!session.plan_ready?'validate':session.conversion&&kind==='brief'&&!briefCurrent()?'adopt':session.conversion?'pilotage':session.plan_ready?'convert':kind==='besoin'?(briefCurrent()?'plan':'brief'):kind==='brief'?(briefCurrent()?'plan':'adopt'):'validate';
 $('advance').dataset.action=action;$('advance').textContent={compare:tr_web_prephase_js('Comparer les versions'),save:tr_web_prephase_js('Enregistrer mes modifications'),brief:tr_web_prephase_js('Ouvrir le brief'),plan:tr_web_prephase_js('Ouvrir le plan'),adopt:tr_web_prephase_js('Adopter ce brief'),validate:tr_web_prephase_js('Vérifier le plan'),convert:session.conversion?tr_web_prephase_js('Comparer et appliquer la révision'):tr_web_prephase_js('Créer les missions'),pilotage:tr_web_prephase_js('Ouvrir le pilotage')}[action];$('save').disabled=!!conflict;
 if(conflict){$('next-action').textContent=tr_web_prephase_js('Choisissez une version dans la comparaison. Votre texte local est conservé.');$('step-brief').textContent=tr_web_prephase_js('Brief à réexaminer');$('step-plan').textContent=tr_web_prephase_js('Plan à revérifier');}
 else if(dirty||pending)$('next-action').textContent=tr_web_prephase_js('Vos modifications doivent être enregistrées avant de poursuivre.');
}
function context(){
 if(!session)return;dialogue.setSession(session);resources.paint(session);decisions.paint(session);conversion.paint(session);
 $('title').textContent=session.title;$('create-form').hidden=true;$('documents').hidden=false;$('method-section').hidden=false;
 for(const k of Object.keys(names)){$('tab-'+k).setAttribute('aria-selected',String(k===kind));$('tab-'+k).tabIndex=k===kind?0:-1;}
 $('plan-template').hidden=kind!=='plan';$('plan-template').disabled=!!editor.value().trim();
 $('document-panel').setAttribute('aria-labelledby','tab-'+kind);$('document-heading').textContent=names[kind];
 $('step-need').textContent=session.documents.besoin?.text?tr_web_prephase_js('Besoin enregistré'):tr_web_prephase_js('Besoin à rédiger');$('step-brief').textContent=briefCurrent()?tr_web_prephase_js('Brief adopté'):session.adopted_brief?tr_web_prephase_js('Brief à réadopter'):tr_web_prephase_js('Brief à adopter');$('step-plan').textContent=session.plan_ready?tr_web_prephase_js('Plan vérifié'):tr_web_prephase_js('Plan à vérifier');$('step-'+(kind==='besoin'?'need':kind)).className='current';for(const k of ['need','brief','plan'])if(k!==(kind==='besoin'?'need':kind))$('step-'+k).className='';
 if(document.activeElement!==$('method'))$('method').value=session.method;
 const method=methods.find(m=>m.id===session.method);$('method-apply').disabled=!method?.available||($('method').value===session.method&&method.sha256===session.method_hash);$('method-status').textContent=!method?.available?(method?.reason||tr_web_prephase_js('Méthode indisponible ; rédaction possible.')):(method.sha256!==session.method_hash?tr_web_prephase_js('La méthode a changé. Appliquez sa version courante.'):method.phases.join(' → '));
 const adopted=briefCurrent();
 $('advance').textContent=kind==='besoin'?tr_web_prephase_js('Ouvrir le brief'):kind==='brief'?(adopted?tr_web_prephase_js('Ouvrir le plan'):tr_web_prephase_js('Adopter ce brief')):tr_web_prephase_js('Vérifier le plan');
 $('next-action').textContent=session.conversion?tr_web_prephase_js('Modifiez le plan puis vérifiez-le pour comparer et appliquer sa révision aux missions. Les tentatives et l’historique seront conservés.'):session.plan_ready?tr_web_prephase_js('Plan vérifié pour cette version. Vous pouvez maintenant créer les missions.'):kind==='besoin'?(adopted?tr_web_prephase_js('Brief adopté. Ouvrez le plan pour poursuivre, ou demandez une proposition à l’IA.'):session.documents.brief?.text?tr_web_prephase_js('Un brief est enregistré. Ouvrez-le pour le relire et le valider.'):tr_web_prephase_js('Prochaine étape : rédiger le brief à partir de votre besoin.')):kind==='brief'?(adopted?tr_web_prephase_js('Brief adopté. Préparez maintenant le plan.'):tr_web_prephase_js('Relisez le brief avant de l’adopter.')): tr_web_prephase_js('Renseignez un plan JSON v1 : objectif, décisions, missions, dépendances et critères. Les décisions ouvertes bloquent sa vérification.');
 updateSize();actionState();
}
async function list(){const v=await api('preparations');const select=$('sessions');select.replaceChildren(new Option(tr_web_prephase_js('Choisir…'),''));for(const p of v.preparations)select.add(new Option(p.title,p.id));if(session)select.value=session.id;}
async function open(id){if(session?.id!==id&&(decisions.hasDraft()||conversion.hasPending())){message(tr_web_prephase_js('Vos décisions sont encore en cours de saisie. Enregistrez-les ou rechargez le plan depuis le formulaire avant de changer de préparation.'));return false;}if(saving||dialogue.hasPending()||resources.hasPending())return false;if(dirty||pending){if(!await save())return false;}clearTimeout(timer);const generation=++openGeneration,epoch=editEpoch;const p=await api('preparations/show?id='+encodeURIComponent(id));if(generation!==openGeneration)return false;if(epoch!==editEpoch){message(tr_web_prephase_js('Votre saisie a changé pendant la navigation. Enregistrez-la avant de changer de préparation.'));return false;}editor.reset();session=p;kind='besoin';dirty=false;pending=null;conflict=null;$('conflict').hidden=true;editor.open(p.id+'/'+kind,kind,p.documents[kind]?.text||'');baseText=editor.value();state(tr_web_prephase_js('Enregistré · révision ')+p.revision);history.replaceState(null,'','/prepare.html?id='+encodeURIComponent(id));$('sessions').value=id;context();return true;}
async function switchDocument(next){if(saving)return;if(next===kind)return;if(dirty||pending){if(!await save())return;}kind=next;editor.open(session.id+'/'+kind,kind,session.documents[kind]?.text||'');baseText=editor.value();state(tr_web_prephase_js('Enregistré · révision ')+session.revision);context();}
async function showConflict(){conflict=await api('preparations/show?id='+encodeURIComponent(session.id));$('conflict-base').textContent=baseText||'(vide)';$('conflict-server').textContent=conflict.documents[kind]?.text||'(vide)';$('conflict').hidden=false;state(tr_web_prephase_js('Conflit — votre texte est conservé'),'attention');actionState();}
async function save(){
 clearTimeout(timer);if(!session)return true;if(conflict){message(tr_web_prephase_js('Comparez les versions avant de reprendre l’enregistrement.'));return false;}if(saving)return false;if(!dirty&&!pending)return true;
 if(new TextEncoder().encode(editor.value()).length>16000){message(tr_web_prephase_js('Document limité à 16 000 octets. Votre texte reste disponible au téléchargement.'));return false;}
 const sent=pending||request('save',{document:kind,text:editor.value()});pending=sent;saving=true;state('Enregistrement…','info');
 try{let p=await api('preparations/command',sent);pending=null;if(p.receipt_historical){await showConflict();return false;}session=p;baseText=sent.text;dirty=editor.value()!==sent.text;message('');state(dirty?tr_web_prephase_js('Modifications non enregistrées'):tr_web_prephase_js('Enregistré · révision ')+p.revision,dirty?'attention':'success');context();if(dirty)timer=setTimeout(()=>save(),750);return !dirty;
 }catch(e){if(e.status===409){pending=null;await showConflict().catch(err=>message(err.message));}else if(e.status&&e.status<500){pending=null;}if(!conflict)state(tr_web_prephase_js('Non enregistré — réessayer'),'alert');actionState();message(e.message);return false;}finally{saving=false;}
}
async function mutate(action,extra){if(dirty||pending){if(!await save())return;}if(saving||conflict)return;saving=true;try{session=await api('preparations/command',request(action,extra));context();state(tr_web_prephase_js('Enregistré · révision ')+session.revision);message('');}catch(e){message(e.message);}finally{saving=false;if(dirty&&!pending&&!conflict){state(tr_web_prephase_js('Modifications non enregistrées'),'attention');timer=setTimeout(()=>save(),750);}}}
function download(text=editor.value(),name=kind){const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name+(name==='plan'?'.json':'.md');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function theme(value){document.documentElement.dataset.theme=value;try{localStorage.setItem('swarm-theme',value)}catch{}$('theme').textContent=value==='etat'?tr_web_prephase_js('Thème sombre'):tr_web_prephase_js('Thème clair');editor.theme();}
let dialogFocus=null;function showDialog(id){dialogFocus=document.activeElement;$(id).showModal();}for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',e=>{if(e.isTrusted)$(b.dataset.close).close()});for(const d of document.querySelectorAll('dialog'))d.addEventListener('close',()=>d.id==='conversion-dialog'?$('conversion-open').focus():d.id==='decisions-dialog'?$('decisions-open').focus():d.id==='missions-dialog'?$('missions-open').focus():dialogFocus?.focus());
async function historyPage(reset){if(reset){historyBefore=0;$('history-content').replaceChildren();showDialog('history-dialog');}const requested=session.id,documentKind=kind;try{const docs=await api('preparations/history?'+new URLSearchParams({id:requested,document:documentKind,...(historyBefore?{before:historyBefore}:{})}));if(session.id!==requested||kind!==documentKind)return;for(const d of docs){const box=document.createElement('details'),title=document.createElement('summary'),pre=document.createElement('pre');title.textContent=tr_web_prephase_js('Version ')+d.revision+' · '+new Date(d.at).toLocaleString();pre.textContent=d.text;box.append(title,pre);$('history-content').append(box);}if(!docs.length&&!historyBefore)$('history-content').textContent=tr_web_prephase_js('Aucune version enregistrée de ce document.');historyBefore=docs.at(-1)?.revision||0;$('history-more').hidden=docs.length<50;}catch(e){$('history-content').textContent=e.message;}}
on('create-form','submit',async e=>{e.preventDefault();if(saving)return;saving=true;$('create').disabled=true;$('new-title').readOnly=true;$('new-need').readOnly=true;createPending ||= {version:1,action:'create',event_id:crypto.randomUUID(),expected_revision:0,title:$('new-title').value,text:$('new-need').value};try{const p=await api('preparations/command',createPending);createPending=null;saving=false;await open(p.id);await list();message('');}catch(err){if(err.status&&err.status<500)createPending=null;message(err.message+tr_web_prephase_js(' Le besoin reste conservé ici ; réessayez pour vérifier son enregistrement.'));}finally{saving=false;$('create').disabled=false;$('new-title').readOnly=!!createPending;$('new-need').readOnly=!!createPending;}});
on('sessions','change',async()=>{const id=$('sessions').value;if(!id)return;try{if(!await open(id))$('sessions').value=session?.id||'';}catch(e){message(e.message)}});
on('new','click',async()=>{if(decisions.hasDraft()||conversion.hasPending()){message(tr_web_prephase_js('Enregistrez vos décisions ou rechargez le plan depuis le formulaire avant de créer une autre préparation.'));return;}if(saving||createPending||dialogue.hasPending()||resources.hasPending()){message(tr_web_prephase_js('Terminez la vérification de l’enregistrement en attente.'));return;}if(dirty||pending){if(!await save())return;}openGeneration++;session=null;dialogue.setSession(null);editor.reset();$('documents').hidden=true;$('method-section').hidden=true;$('create-form').hidden=false;$('new-title').value='';$('new-need').value='';$('title').textContent=tr_web_prephase_js('Préparer un projet');$('sessions').value='';history.replaceState(null,'','/prepare.html');$('new-need').focus();});
for(const k of Object.keys(names))on('tab-'+k,'click',()=>switchDocument(k));
for(const k of Object.keys(names))on('tab-'+k,'keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const keys=Object.keys(names);const i=keys.indexOf(k);const next=e.key==='Home'?keys[0]:e.key==='End'?keys.at(-1):keys[(i+(e.key==='ArrowRight'?1:2))%3];switchDocument(next).then(()=>$('tab-'+kind).focus());});
on('save','click',save);on('download','click',()=>download());on('download-new','click',()=>download($('new-need').value,'besoin'));on('editor-toggle','click',()=>editor.toggle());on('theme','click',()=>theme(document.documentElement.dataset.theme==='etat'?'sombre':'etat'));on('help','click',()=>showDialog('help-dialog'));on('history','click',()=>historyPage(true));on('history-more','click',()=>historyPage(false));
on('method-apply','click',()=>mutate('method',{method:$('method').value}));
on('advance','click',async()=>{const action=$('advance').dataset.action;if(action==='compare'){$('conflict').scrollIntoView({block:'center'});$('conflict-keep').focus();return;}if(action==='save'){await save();return;}if(action==='brief'||action==='plan')return switchDocument(action);if(action==='convert')return conversion.open();if(action==='pilotage'){location.href='/?work='+encodeURIComponent(session.conversion.work_id);return;}if(action==='adopt')await mutate('adopt-brief',{sha256:session.documents.brief?.sha256||''});else if(action==='validate')await mutate('validate-plan',{sha256:session.documents.plan?.sha256||''});});
on('conflict-keep','click',async()=>{if(!conflict)return;session=conflict;conflict=null;pending=null;$('conflict').hidden=true;dirty=true;await save();});on('conflict-use','click',()=>{if(!conflict)return;session=conflict;conflict=null;pending=null;dirty=false;editor.setText(session.documents[kind]?.text||'');baseText=editor.value();$('conflict').hidden=true;state(tr_web_prephase_js('Version serveur chargée'));context();message('');});
addEventListener('beforeunload',e=>{if(resources.hasPending()||conversion.hasPending()||decisions.hasDraft()||dirty||pending||dialogue.hasPending()||[...dialogue.drafts.values()].some(v=>v.trim())||$('chat-message').value||$('new-need').value&&!session){e.preventDefault();e.returnValue='';}});
addEventListener('keydown',e=>{if(e.isTrusted&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'&&session){e.preventDefault();save();}});
(async()=>{try{if(!globalThis.SecurityUtils)throw new Error(tr_web_prephase_js('Sécurité de page indisponible.'));let saved;try{saved=localStorage.getItem('swarm-theme')}catch{}theme(saved==='sombre'?'sombre':'etat');csrf=(await api('session')).csrf;methods=await api('preparations/methods');for(const m of methods){const option=new Option(m.title+(m.available?'':tr_web_prephase_js(' — indisponible')),m.id);option.disabled=!m.available;$('method').add(option);}await list();await dialogue.init();const id=new URL(location.href).searchParams.get('id');if(id)await open(id);$('connection').textContent=tr_web_prephase_js('Connecté au projet');await editor.initialize();}catch(e){message(e.message);$('connection').textContent=tr_web_prephase_js('Connexion indisponible');$('connection').className='status alert';}})();

on('plan-template','click',()=>{if(kind!=='plan'||editor.value().trim())return;editor.setText(JSON.stringify({version:1,objective:'',assumptions:[],questions:[],tasks:[{id:'T1',title:'',role:'worker',scope:'',deliverable:'',criteria:[],depends:[],proof:'',entry:'',validation:'',delivery:'',stop:'',max_attempts:2,max_tool_calls:30}]},null,2));changed();});

on('refresh','click',async()=>{if(!session||saving)return;if((dirty||pending)&&!await save())return;try{const id=session.id,epoch=editEpoch,fresh=await api('preparations/show?id='+encodeURIComponent(id));if(session?.id!==id||epoch!==editEpoch){message(tr_web_prephase_js('Votre saisie a changé pendant l’actualisation ; elle est conservée.'));return;}session=fresh;editor.open(session.id+'/'+kind,kind,session.documents[kind]?.text||'');baseText=editor.value();state(tr_web_prephase_js('Versions actualisées · révision ')+session.revision);context();message('');}catch(e){message(e.message)}});

on('method','change',()=>{const m=methods.find(m=>m.id===$('method').value);$('method-apply').disabled=!m?.available||(m.id===session?.method&&m.sha256===session?.method_hash);$('method-status').textContent=m?.id===session?.method?(m?.phases.join(' → ')||tr_web_prephase_js('Méthode indisponible')):tr_web_prephase_js('Changer de méthode demandera de revérifier le plan.');});

addEventListener("swarm:language-change",e=>{if(resources.hasPending()||conversion.hasPending()||decisions.hasDraft()||dirty||pending||dialogue.hasPending()||[...dialogue.drafts.values()].some(v=>v.trim())||$("chat-message").value||$("new-need").value&&!session){message(globalThis.SwarmI18n.t(tr_web_prephase_js("Enregistrez ou terminez vos modifications avant de changer de langue.")));e.preventDefault();}});
